### ISSUE TITLE
502: Bad Gateway

### ISSUE THREAD

**Issue by juergenschubert** [hassio-addons/addon-ssh#101]
# Problem/Motivation
When I click on the Open Web UI or the Terminal entry I do get a 502: Bad Gateway

> (Why the issue was filed)

## Expected behavior
get the ssh from the GUI
> (What you expected to happen)

## Actual behavior
when I click on the Terinal entry I to get a 502: Bad Gateway
> (What actually happened)

## Steps to reproduce
Click ont eh Terminal entry on the left side of the HA menue
> (How can someone else make/see it happen)

## Proposed changes
working
> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
my config looks like:
{
  "ssh": {
    "username": "ssh_admin",
    "password": "my_special_password",
    "authorized_keys": [],
    "sftp": false,
    "compatibility_mode": false,
    "allow_agent_forwarding": false,
    "allow_remote_port_forwarding": false,
    "allow_tcp_forwarding": false
  },
  "web": {
    "ssl": true,
    "certfile": "fullchain.pem",
    "keyfile": "privkey.pem"
  },
  "share_sessions": true,
  "packages": [],
  "init_commands": []
}

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] permissions: applying... 
[fix-attrs.d] permissions: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: SSH & Web Terminal
 SSH & Web Terminal access to your Home Assistant instance
-----------------------------------------------------------
 Add-on version: 6.4.0
 You are running the latest version of this add-on.
 System: HassOS 3.5  (armv7 / raspberrypi4)
 Home Assistant version: 0.100.2
 Supervisor version: 189
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] docker.sh: executing... 
[12:29:53] INFO: Docker support has been enabled.
[cont-init.d] docker.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] ssh.sh: executing... 
[12:29:56] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[12:29:56] WARNING: 
[12:29:56] WARNING: Logging in with a SSH password is security wise, a bad idea!
[12:29:56] WARNING: Please, consider using a public/private key pair.
[12:29:56] WARNING: What is this? https://kb.iu.edu/d/aews
[12:29:56] WARNING: 
[12:29:56] NOTICE: RSA host key missing, generating one...
Generating public/private rsa key pair.
Your identification has been saved in /data/ssh_host_rsa_key.
Your public key has been saved in /data/ssh_host_rsa_key.pub.
The key fingerprint is:
SHA256:rJ/nSbzgQa0e7IYxe1ZVDZg9gkbT5p4wj9MQTWxr4mQ root@a0d7b954-ssh.local.hass.io
The key's randomart image is:
+---[RSA 3072]----+
|         .o*.+.o |
|          +.X + .|
|         . = + . |
|       . .E =    |
|        S+.% .   |
|      o+ o= =    |
|      .=*.o.     |
|      o=+*.o     |
|       +*o+      |
+----[SHA256]-----+
[12:30:04] NOTICE: ED25519 host key missing, generating one...
Generating public/private ed25519 key pair.
Your identification has been saved in /data/ssh_host_ed25519_key.
Your public key has been saved in /data/ssh_host_ed25519_key.pub.
The key fingerprint is:
SHA256:8KVnrGWum2CMwRnx1558dSkwPQCN0nQc+sMg25ecFqo root@a0d7b954-ssh.local.hass.io
The key's randomart image is:
+--[ED25519 256]--+
|    .   oo=*+    |
|     o . +oooo  .|
|    . o.ooo. .o..|
|   . o ++**.+... |
|    +  .SoXX.    |
|     +  .Bo..    |
|    . +E. .      |
|     . . o       |
|        +.       |
+----[SHA256]-----+
[cont-init.d] ssh.sh: exited 0.
[cont-init.d] user.sh: executing... 
[cont-init.d] user.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[12:30:06] INFO: Starting the ttyd daemon...
[12:30:06] INFO: Starting NGinx...
[12:30:06] INFO: Starting the SSH daemon...
[12:30:06] INFO: Starting the Home Assistant STDIN service...
Server listening on 0.0.0.0 port 22.
Server listening on :: port 22.
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)

<blockquote><img src="/favicon.ico" width="48" align="right"><div><strong><a href="https://kb.iu.edu/d/aews">Set up SSH public-key authentication to connect to a remote system</a></strong></div><div>On this page:</div></blockquote>
<blockquote><img src="https://avatars0.githubusercontent.com/u/7390180?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/openresty/luajit2">openresty/luajit2</a></strong></div><div>OpenResty's Branch of LuaJIT 2. Contribute to openresty/luajit2 development by creating an account on GitHub.</div></blockquote>
<blockquote><div><strong><a href="https://openresty.org/en/download.html">OpenResty - Download</a></strong></div></blockquote>

**Comment by Black6spdZ** [comment]
still broke with Home Assistant 0.102.2 and plugin 6.4.0

**Comment by sinclairpaul** [comment]
@Black6spdZ Please post your own logs and config under a separate issue.
