### ISSUE TITLE
Cannot ssh into hass with ssh key

### ISSUE THREAD

**Issue by ax42** [hassio-addons/addon-ssh#11]
# Problem/Motivation

> Need to ssh into hass

## Expected behavior

> ssh into hassio works correctly with an ssh key (this worked before)

## Actual behavior

> Client gets error `Permission denied (publickey).`

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

The error message on the server is `Authentication refused: bad ownership or modes for directory /etc/ssh` -- in actual fact it is both /etc and /etc/ssh which have the group write permissions bit set, which is causing the issue.

Connecting to the docker container with a console and changing permissions on those directories to `755` fixes the issue.

**Comment by frenck** [comment]
Hi @ax42,

Thank you for the bug report. There was a bug in version v2.0.0 & v2.0.1 of the add-on that has been fixed in version v2.0.2. 

v2.0.2 fixes the issue you are reporting. Please upgrade.
