### ISSUE TITLE
Show all processes of the hassos system. 

### ISSUE THREAD

**Issue by vandalon** [hassio-addons/addon-ssh#114]
# Problem/Motivation

Is there a way to see all the processed of the hassos system. I noticed the glances addon can show all processes and I wonder if there is a way to get that same result in the ssh addon :)

## Expected behavior

Show all processes running on the hassos system.

## Actual behavior

Current the addon only shows the processes that belong the the docker the addon runs in.

## Steps to reproduce

Use top or ps to show the process list.

**Comment by frenck** [comment]
In theory, yes it could.
Practically, this will merge the PID spaces for the add-on & the host system. There are many risks around this, which I'm not want to put into this add-on.

For glances, this is another story.

**Comment by vandalon** [comment]
how about making it optional with a big warning? :)

**Comment by frenck** [comment]
It would not be optional, so not adding it.
