### ISSUE TITLE
New install, first time for docker and error on startup of addon

### ISSUE THREAD

**Issue by mattlward** [hassio-addons/addon-ssh#116]
# Problem/Motivation

I have installed the addon and it is not working, well not starting.

## Expected behavior

I expected to be able to open a terminal windows.

## Actual behavior

Addon will not start

## Steps to reproduce

Not really sure

## Proposed changes

I have tried with protection on and off.  I do have openssh-server running on the host machine.  
I am attaching the relevant part of the logs.  I have tried changing the port in the config section as well.  I think that the existing openssh server is preventing this from starting.  I am new to docker.
Logs:
[cont-init.d] ssh.sh: exited 0.
[cont-init.d] user.sh: executing... 
[cont-init.d] user.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[21:16:16] INFO: Starting the Home Assistant STDIN service...
[21:16:16] INFO: Starting the ttyd daemon...
[21:16:16] INFO: Starting the SSH daemon...
Bind to port 22 on 0.0.0.0 failed: Address in use.

Bind to port 22 on :: failed: Address in use.

Cannot bind any address.

[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
[21:16:16] INFO: STDIN service was stopped, restarting...
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
/usr/lib/bashio/addons.sh: line 171: printf: write error: Broken pipe
[s6-finish] sending all processes the TERM signal

**Comment by sinclairpaul** [comment]
`Bind to port 22 on :: failed: Address in use.`

The error shown means that 22 is in use on your host.

`I do have openssh-server running on the host machine.`

This is likely the culprit, you can change the port of one of them to get it running.
