### ISSUE TITLE
sshfs compatibility

### ISSUE THREAD

**Issue by zbuh** [hassio-addons/addon-ssh#117]
# Problem/Motivation
sshfs compatibility
This plugin does not allow sshfs mount, as the default one does.

## Expected behavior
Ability to mount a folder. eg: /config via sshfs

## Actual behavior
not connect. error.

## Steps to reproduce
install sshfs in a client machine and run:
sshfs user@hassio:/config ./<local_folder>

## Proposed changes
check ssh server default config for the compatibility issue

**Comment by frenck** [comment]
please share your config (without secrets). Thanks 👍

**Comment by zbuh** [comment]
`{
  "ssh": {
    "username": "nuno",
    "password": "",
    "authorized_keys": [
      "ssh-rsa AAAA(...)cardno:000611073329"
    ],
    "sftp": false,
    "compatibility_mode": false,
    "allow_agent_forwarding": true,
    "allow_remote_port_forwarding": false,
    "allow_tcp_forwarding": false
  },
  "zsh": true,
  "share_sessions": false,
  "packages": [],
  "init_commands": []
}`

**Comment by frenck** [comment]
sshfs needs the sftp protocol, which is disabled in your configuration.
