### ISSUE TITLE
Unable to start, sends TERM to all processes, broken pipe

### ISSUE THREAD

**Issue by rick-cross** [hassio-addons/addon-ssh#119]
## Problem/Motivation
Hi,
I am running Hass.io on synology via docker.
And I need to modify the devices.js file to correct an issue/typo so my thermostat will be fully functional as per this [issue with Zen thermostats](https://github.com/Koenkk/zigbee2mqtt/issues/2652) 

I've been following the docs below to try and get SSH access 
- [how to support new deivces](https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html#hassio-addon)
- [hassio_debugging](https://developers.home-assistant.io/docs/en/hassio_debugging.html) 

I was hoping to use the SSH & Web Terminal addon (via simple username and password since it would be a 1 time thing and i would uninstall afterwards) to log in and follow the instructions described above.

## Expected behavior
add on starts as expected

## Actual behavior
What I see in the logs (full log output is below) is a warning of 

> Permissions 0755 for '/data/ssh_host_rsa_key' are too open.
> It is required that your private key files are NOT accessible by others.
> This private key will be ignored.

And an eventual 'broken pipe' and 'sending all processes the TERM signal'

If the permissions are the issues, I'm not sure how I'm supposed to modify/reduce the permissions within docker /data/ directory if i'm not able to get access via SSH...

## Steps to reproduce
These are the configs I used (password deleted for posting to here), and started the add-on.
ssh:
  username: hassio
  password: <deleted for here>
  authorized_keys: []
  sftp: false
  compatibility_mode: false
  allow_agent_forwarding: false
  allow_remote_port_forwarding: false
  allow_tcp_forwarding: false
zsh: true
share_sessions: false
packages: []
init_commands: []

Any advice/help would be greatly appreciated.
I tried the 'core' SSH server add on also but that wouldn't start at all and it wouldn't even output any logs. I click the start button and it simply highlights blue for 1 second and then highlights red with no log output. 

## Full Log Output

[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Hass.io Add-on: SSH & Web Terminal
 SSH & Web Terminal access to your Home Assistant instance
-----------------------------------------------------------
 Add-on version: 7.0.1
 You are running the latest version of this add-on.
 System: null  (amd64 / qemux86-64)
 Home Assistant version: 0.105.2
 Supervisor version: 199
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] docker.sh: executing... 
[cont-init.d] docker.sh: exited 0.
[cont-init.d] ssh.sh: executing... 
[09:32:57] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[09:32:58] WARNING: 
[09:32:58] WARNING: Logging in with a SSH password is security wise, a bad idea!
[09:32:58] WARNING: Please, consider using a public/private key pair.
[09:32:58] WARNING: What is this? https://kb.iu.edu/d/aews
[09:32:58] WARNING: 
[09:32:58] NOTICE: RSA host key missing, generating one...
Generating public/private rsa key pair.
Your identification has been saved in /data/ssh_host_rsa_key.
Your public key has been saved in /data/ssh_host_rsa_key.pub.
The key fingerprint is: <deleted just in case>
The key's randomart image is: <deleted just in case>
[09:32:59] NOTICE: ED25519 host key missing, generating one...
Generating public/private ed25519 key pair.
Your identification has been saved in /data/ssh_host_ed25519_key.
Your public key has been saved in /data/ssh_host_ed25519_key.pub.
The key fingerprint is: <deleted just in case>
The key's randomart image is: <deleted just in case>
[cont-init.d] ssh.sh: exited 0.
[cont-init.d] user.sh: executing... 
[09:33:00] NOTICE: Session sharing has been disabled!
[cont-init.d] user.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[09:33:00] INFO: Starting the Home Assistant STDIN service...
[09:33:00] INFO: Starting the ttyd daemon...
[09:33:00] INFO: Starting the SSH daemon...
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0755 for '/data/ssh_host_rsa_key' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Unable to load host key "/data/ssh_host_rsa_key": bad permissions
Unable to load host key: /data/ssh_host_rsa_key

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0755 for '/data/ssh_host_ed25519_key' are too open.
It is required that your private key files are NOT accessible by others.

This private key will be ignored.
Unable to load host key "/data/ssh_host_ed25519_key": bad permissions
Unable to load host key: /data/ssh_host_ed25519_key

sshd: no hostkeys available -- exiting.

[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
[09:33:01] INFO: STDIN service was stopped, restarting...
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
**/usr/lib/bashio/addons.sh: line 171: printf: write error: Broken pipe
[s6-finish] sending all processes the TERM signal.**

<blockquote><img src="/favicon.ico" width="48" align="right"><div><strong><a href="https://kb.iu.edu/d/aews">Set up SSH public-key authentication to connect to a remote system</a></strong></div><div>On this page:</div></blockquote>

**Comment by sinclairpaul** [comment]
Please see #110 
I would suggest seeking help on the forums (the link is in the other issue).
