### ISSUE TITLE
Run crond by default

### ISSUE THREAD

**Issue by scop** [hassio-addons/addon-ssh#120]
# Problem/Motivation

> (Why the issue was filed)

crond is installed, but not running by default. I think a fair expectation is that given all the tools are in place, and one can happily edit crontabs etc with `crontab -e`, the jobs would actually run without having to start crond oneself. It shouldn't be that heavy.

## Expected behavior

> (What you expected to happen)

crond running by default

## Actual behavior

> (What actually happened)

``` 
~ $ pidof crond
~ $ # nothing
```

## Steps to reproduce

> (How can someone else make/see it happen)

Use `crontab -e` to add some jobs or add files in /etc/periodic/*, notice that they are not run.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

Have crond running by default

**Comment by frenck** [comment]
Sorry, but I think that is going way out of scope for the add-on.
The add-on runs processes to provide SSH & a Web Terminal, and I strongly believe we should keep it at that.

Nevertheless, you could achieve it using the add-on configuration options provided already.

**Comment by scop** [comment]
Fine, but to be fair, the add-on currently has much much more than just what's needed to provide SSH and web terminal already, and I was previously explained that the core SSH add-on is the bare bones one.

**Comment by frenck** [comment]
This is not about tools that are available, this about running processes, which should kept to the minimum by default, considering low-end devices.
