### ISSUE TITLE
:arrow_up: placeholder in changelog instead of icon?

### ISSUE THREAD

**Issue by jmartens** [hassio-addons/addon-ssh#126]
# Problem/Motivation

Changelog dialog shows `:arrow_up:` ...

## Expected behavior

... instead of (I suspect) an up arrow icon 

## Actual behavior

Observed update notification of 7.3.1 with respect to 7.3 as below:

![image](https://user-images.githubusercontent.com/593327/78167749-3e9df880-744f-11ea-942b-cfe7a82edd14.png)

**Comment by jmartens** [comment]
Most likekly you take your changelogs from guithub where `:arrow_up:`  is rendered as :arrow_up:.

**Comment by frenck** [comment]
That is converted/grabbed from GitHub automatically. Not planning on changing that.
