### ISSUE TITLE
Latest Version Null

### ISSUE THREAD

**Issue by ntilley905** [hassio-addons/addon-ssh#127]
# Problem/Motivation

> (Why the issue was filed)

During start-up, the latest version is listed as null. 

## Expected behavior

> (What you expected to happen)

Latest version is fetched during start-up. 

## Actual behavior

> (What actually happened)

Version null is fetched and the logs recommend I upgrade. 

## Steps to reproduce

> (How can someone else make/see it happen)

Happens on every start/restart. 

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

Applicable Logs: 
```
-----------------------------------------------------------
 Add-on: SSH & Web Terminal
 SSH & Web Terminal access to your Home Assistant instance
-----------------------------------------------------------
 Add-on version: 7.3.1
 There is an update available for this add-on!
 Latest add-on version: null
 Please consider upgrading as soon as possible.
 System: HassOS 3.12  (armv7 / raspberrypi3)
 Home Assistant Core: 0.107.7
 Home Assistant Supervisor: 214
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
```

**Comment by frenck** [comment]
This is a bug upstream and will be resolved on the next upgrade automatically.

Thank you for reporting.
