### ISSUE TITLE
addon start and stop with error

### ISSUE THREAD

**Issue by blademckain** [hassio-addons/addon-ssh#128]
# Problem/Motivation

> I use hassio in a docker enviroment, this is the log when start the plugin from the web UI
`
[17:03:22] INFO: Starting the Home Assistant STDIN service...
[17:03:22] INFO: Starting the ttyd daemon...
[17:03:23] INFO: Starting the SSH daemon...
/var/empty must be owned by root and not group or world-writable.
[services.d] done.
[17:03:23] INFO: STDIN service was stopped, restarting...
/usr/lib/bashio/addons.sh: line 171: printf: write error: Broken pipe
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
/var/run/s6/etc/cont-finish.d/99-message.sh: line 6: S6_STAGE2_EXITED: unbound variable
[cont-finish.d] 99-message.sh: exited 1.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
`
if i execute
docker exec -it addon_a0d7b954_ssh /bin/bash -c "ls -al /var/"
total 32
drwxr-xr-x   14 root     root            15 Mar 29 22:35 .
drwxr-xr-x   26 100000   100000          28 Apr  2 16:44 ..
drwxr-xr-x    4 root     root             4 Mar 23 21:12 cache
drwxr-xr-x    3 root     root             3 Mar 29 22:35 db
dr-xr-xr-x    2 100000   100000           2 Mar 23 21:12 empty
drwxr-xr-x    2 root     root             2 Mar 29 22:35 git
drwxr-xr-x   10 root     root            10 Mar 29 22:35 lib
drwxr-xr-x    2 100000   100000           2 Mar 23 21:12 local
drwxr-xr-x    3 100000   100000           3 Mar 23 21:12 lock
drwxr-xr-x    3 root     root             3 Mar 29 22:35 log
drwxr-xr-x    2 100000   100000           2 Mar 23 21:12 mail
drwxr-xr-x    2 100000   100000           2 Mar 23 21:12 opt
lrwxrwxrwx    1 100000   100000           4 Mar 23 21:12 run -> /run
drwxr-xr-x    3 100000   100000           4 Mar 23 21:12 spool
drwxrwxrwt    2 100000   100000           2 Mar 23 21:12 tmp

seems that /var/empty is owned by user 100000   but not understand why

**Comment by frenck** [comment]
Could you please describe your setup? Used hardware and software? Thanks 👍

**Comment by frenck** [comment]
No response from the issue creator. Closing.
