### ISSUE TITLE
ssh will not start getting error on web ui  error 502: Bad Gateway

### ISSUE THREAD

**Issue by ggrobi** [hassio-addons/addon-ssh#132]
# Problem/Motivation

> (want to access ssh)

## Expected behavior

> (cant get ssh accesss)

## Actual behavior

> (error 502 :Bad Gateway)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Please provide logs.

**Comment by alexinfo2011** [comment]
Hi, change the port to 2022 and restart (work for me)

**Comment by ggrobi** [comment]
Ok, thks will try

**Comment by frenck** [comment]
Closing this issue. Feel free to open one up again if you provide logs. Without it, there is no real answer to give. Thanks!
