### ISSUE TITLE
Detection of new plugin version is not working

### ISSUE THREAD

**Issue by gralin** [hassio-addons/addon-ssh#137]
# Problem/Motivation

Not a big issue but I noticed in the logs that there is a message about new version of the plugin being available. This cought my eye becuase I just installed it and I knew I was using latest one. Next to this message I saw that it prints out that latest version number is `null` and maybe this is the reason why it thinks a new version is available?

## Expected behavior

Information that I am using the latest version.

## Actual behavior

> There is an update available for this add-on!
> Latest add-on version: null 

👇 

```
-----------------------------------------------------------
 Add-on: SSH & Web Terminal
 SSH & Web Terminal access to your Home Assistant instance
-----------------------------------------------------------
 Add-on version: 7.3.2
 There is an update available for this add-on!
 Latest add-on version: null
 Please consider upgrading as soon as possible.
 System: HassOS 3.13  (armv7 / raspberrypi3)
 Home Assistant Core: 0.108.9
 Home Assistant Supervisor: 219
```

## Steps to reproduce

Check your logs.

**Comment by sinclairpaul** [comment]
It's a known issue will be fixed in the next release. #134 #127

**Comment by gralin** [comment]
@sinclairpaul oh ok, I only looked in open issues for possible duplication before reporting this. Thanks!
