### ISSUE TITLE
Missing addon from add-on store screen

### ISSUE THREAD

**Issue by rmatiash** [hassio-addons/addon-ssh#138]
# Problem/Motivation

I can't see addon-ssh in the screen where availabre addons are listed (supervisor - Add-on store - Community Add-ons). I have had this addon installed previously, so most likely reason is I messed something wrong... however it's not installed and I can't find it in order to install it again.

## Expected behavior

I expected to find ssh addon in the listing.

## Actual behavior

Add-on is missing in the add-ons page.

## Steps to reproduce

Not sure, most likely is something I messed around. Any help will be highly appreciated.

**Comment by frenck** [comment]
The SSH add-on is an advanced add-on and will only show up when you user profile is set to advanced mode.

**Comment by rmatiash** [comment]
Wow, thank you for the quick answer.

As I'm trying to troubleshoot a xiaomi gw issue, I started from scratch and I didn't remember that profile option. However I have changed it to advanced, I have logout and I have restarted both homeassistant and hassio_supervisor containers with no luck. I can't see ssh addon.

This is what I get when supervisor restarts:
20-04-26 16:57:08 INFO (MainThread) [supervisor.store.git] Load add-on /data/addons/git/a0d7b954 repository
20-04-26 16:57:08 INFO (MainThread) [supervisor.store.git] Load add-on /data/addons/core repository
20-04-26 16:57:09 INFO (MainThread) [supervisor.store] Load add-ons from store: 65 all - 65 new - 0 remove
20-04-26 16:57:09 INFO (MainThread) [supervisor.addons] Found 2 installed add-ons
20-04-26 16:57:09 INFO (SyncWorker_16) [supervisor.docker.interface] Attach to homeassistant/amd64-addon-configurator with version 5.0.0
20-04-26 16:57:09 INFO (SyncWorker_17) [supervisor.docker.interface] Attach to homeassistant/amd64-addon-check_config with version 3.2.0

And this is what I get when I remove/readd community addons repository:
20-04-26 17:08:14 INFO (MainThread) [supervisor.store.git] Remove custom add-on repository https://github.com/hassio-addons/repository
20-04-26 17:08:14 INFO (MainThread) [supervisor.store] Load add-ons from store: 20 all - 0 new - 45 remove
----
20-04-26 17:09:16 INFO (MainThread) [supervisor.store.git] Clone add-on https://github.com/hassio-addons/repository repository
20-04-26 17:09:18 INFO (MainThread) [supervisor.store] Load add-ons from store: 65 all - 45 new - 0 remove
 
Thank you in advance

**Comment by frenck** [comment]
![image](https://user-images.githubusercontent.com/195327/80314784-cdeebf80-87f3-11ea-802e-f5a60a17c4d6.png)

The last toggle is the only change needed to make it show up. Just checked against beta & latest stable. Both respond correctly with that switch (without restarting).

**Comment by rmatiash** [comment]
Hi, thank you for your feedback: I upgraded to 0.108.9 and it's working as expected. I was on 0.105.4, due to the xiaomi gw. troubleshooting I mentioned. On latest version, xiaomi gw is no longer discovered, however it works perfect on 0.105.4, but that one will be another case still to be opened.

BR
