### ISSUE TITLE
SSH Agent Forwarding doesn't work (disabled in sshd_config)

### ISSUE THREAD

**Issue by gbrayut** [hassio-addons/addon-ssh#14]
# Problem/Motivation

While it is great that the addon persists the .ssh folder, an even better option is to not require the keys to be stored locally and just forward the local SSH Agent using the `ssh -A ...` option. However it looks like this currently doesn't work due to that option being disabled in [sshd_config](https://github.com/hassio-addons/addon-ssh/blob/6222fe9bc7cbcb39490298b15ef7102b9265533b/ssh/rootfs/etc/ssh/sshd_config#L56)

## Expected behavior

Using `ssh-add` to add a key to a local SSH Agent and then `ssh -A ...` to connect should show the same keys inside the new ssh session (can confirm using `ssh-add -l`)

## Actual behavior

```
➜  ~ ssh-add -l
Could not open a connection to your authentication agent.
```
## Proposed changes

I tried updating the /etc/ssh/sshd_config file and sending SIGHUP to the sshd process to reload the config, but I don't that works in the container. `AllowAgentForwarding yes` is the default option on most distributions, and hopefully changing that config option will allow it to work with this add on.

**Comment by frenck** [comment]
@gbrayut Thank you for this great feature request.
I've added it in, and threw in TCP forwarding as well.

It is currently on the master branch and will be released in the next version.
