### ISSUE TITLE
Can't install SSH addon through Home assistant community add-ons or direct with URL

### ISSUE THREAD

**Issue by tono15** [hassio-addons/addon-ssh#141]
# Problem/Motivation
Unable to SSH into HA
> (Why the issue was filed)

## Expected behavior
To have the Monitor in HA as in given image. Can't enter HA  with putty
> (What you expected to happen)

## Actual behavior
See error file attached
> (What actually happened)
It doesn't install SSH
## Steps to reproduce

> (How can someone else make/see it happen)
Don't know until I can correct the the error message in my case.

[foutmelding na install addon.txt](https://github.com/hassio-addons/addon-ssh/files/4545286/foutmelding.na.install.addon.txt)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
Regards Ton O

**Comment by frenck** [comment]
SSH add-ons are considered advanced add-ons. They are hidden by default. To make them show up, make sure you have enabled Advanced Mode in your Home Assistant user profile.
