### ISSUE TITLE
Icon for ssh-Terminal is available but still  error, not functioning.

### ISSUE THREAD

**Issue by tono15** [hassio-addons/addon-ssh#142]
# Problem/Motivation
Franck, thanks for the quick response. 

I can load the Ssh terminal, but error to start the add-on. Have done that and get the error bad gateway 502. Have rebooted, removed the addon installed it again, same results. Reboted several time. Disconected and start up again., same results. In system log an error around Ingress error: Cannot connect to host 172.30.32.1: 62261 ssl: None { connection refused. See attached file
 
[foutmelding  2 na install addon.txt](https://github.com/hassio-addons/addon-ssh/files/4547493/foutmelding.2.na.install.addon.txt)

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

Advise to correct the situation.

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
Please look in the addon startup log, it isn't started

**Comment by frenck** [comment]
No response from issue creator. Closing issue.
