### ISSUE TITLE
Configurator saves malformed SSH key

### ISSUE THREAD

**Issue by rghunter** [hassio-addons/addon-ssh#144]
# Problem/Motivation
Each time I reboot or modify the configuration of the SSH-agent (in the UI), my public key gets mistranslated in the authorized_keys directory.
## Expected behavior
not put a line return after every character in the authorized_keys config

![image](https://user-images.githubusercontent.com/448760/81841321-40f87580-9518-11ea-90eb-a19bf0d57e1d.png)

## Actual behavior
The authorized key file contains all the content of my public key, but there appears to be some character encoding issue as it returns after each character resulting in the key not validating properly.

![image](https://user-images.githubusercontent.com/448760/81841349-4b1a7400-9518-11ea-8e13-f520365c9803.png)

## Steps to reproduce

configure your public key in the UI. Take a look at the authroized_keys file. 

## Proposed changes

Haven't dug into it so I'm completely spitting blind here: Check output each time you re-encode a character string, the problem might be in there.

**Comment by sharkyP** [comment]
i'm also having this issue on version 8.6.0 of the addon

**Comment by DanskerUS** [comment]
Same issue here

**Comment by johanson** [comment]
I can reproduce it with 7.4.1.

Conf:
```
ssh:
  username: hassio
  authorized_keys: ssh-rsa abc
```

Output:
```
➜  ~ cat /etc/ssh/authorized_keys
s
s
h
-
r
s
a

a
b
c
➜  ~ 
```

**Comment by sinclairpaul** [comment]
Can you put it in a list?
```
ssh:
  username: hassio
  authorized_keys:
    - ssh-rsa abc
```

**Comment by johanson** [comment]
List works indeed @sinclairpaul

**Comment by sinclairpaul** [comment]
Glad to hear it, will close it out.

I am guessing the change was caused when the supervisor switched to YAML, and the formatting for it.
