### ISSUE TITLE
Incorrect times between core and SU logs - Not sure if it is system issue or addon

### ISSUE THREAD

**Issue by bschatzow** [hassio-addons/addon-ssh#146]
# Problem/Motivation

> (Why the issue was filed)
Trying to troubleshoot boot issue on updates and noticed a 3 hour time difference between the two log files.
## Expected behavior

> (What you expected to happen)
They should use the same clock
## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)
open up a cli and run ha core logs and ha su logs
## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
The supervisor runs on UTC. This is fixed.
