### ISSUE TITLE
Problem with Network settings

### ISSUE THREAD

**Issue by LussRus** [hassio-addons/addon-ssh#149]
I'm try to fill the field 'Host'  (network settings folder in configuration)

Container | Host | Description
22/tcp |  NaN |

This field doesn't accept any value - always drop back to NaN
Do I need to fill this?

**Comment by frenck** [comment]
just the port number.

**Comment by LussRus** [comment]
Hello Frank,
 
Thank you for answer. Yes, I have solved this problem two days ago. 
But — here aren’t describes that default user name — root and «login»/»username» are not accept by system.
 
С наилучшими пожеланиями,
Денис Владимирович Шишелякин
+7 916 6935476

Mit freundlichen Grüßen,
Denis Shishelyakin

Best regards,
Denis Shishelyakin

**Comment by dako76** [comment]
Hi, in my configuration i see this, and this is really not transparent that i have to add the portnumber there. Can you change the collumn description to something like "Port Enabled"? Thank you for your good work!

![2020-12-27 11_37_44-Supervisor - Home Assistant](https://user-images.githubusercontent.com/20343568/103169018-99c31700-4838-11eb-9113-0711ed68f03f.png)

**Comment by frenck** [comment]
@dako76 An add-on cannot do that, this interfaces it outside of the add-on scope.
