### ISSUE TITLE
Wont start says 502: badgateway

### ISSUE THREAD

**Issue by realjax** [hassio-addons/addon-ssh#154]
Just installed this add on on a fresh HA install.
But starting it give me the 502: badgateway.

The logs say this:
```
20-08-04 07:47:08 INFO (MainThread) [supervisor.addons] Create Home Assistant add-on data folder /data/addons/data/a0d7b954_ssh
20-08-04 07:47:08 INFO (SyncWorker_0) [supervisor.docker.interface] Pull image hassioaddons/ssh-armv7 tag 7.4.1.
20-08-04 07:48:02 INFO (MainThread) [supervisor.addons] Add-on 'a0d7b954_ssh' successfully installed
20-08-04 07:48:11 INFO (MainThread) [supervisor.ingress] Update Ingress as panel for a0d7b954_ssh
20-08-04 07:52:36 INFO (SyncWorker_0) [supervisor.docker.addon] Start Docker add-on hassioaddons/ssh-armv7 with version 7.4.1
20-08-04 07:52:38 INFO (MainThread) [supervisor.api.security] /host/info access from a0d7b954_ssh
20-08-04 07:52:42 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.32.1:64786 ssl:None [Connection refused]
20-08-04 07:52:59 INFO (SyncWorker_0) [supervisor.docker.interface] Clean addon_a0d7b954_ssh application
20-08-04 07:53:02 INFO (SyncWorker_0) [supervisor.docker.addon] Start Docker add-on hassioaddons/ssh-armv7 with version 7.4.1
20-08-04 07:53:04 INFO (MainThread) [supervisor.api.security] /host/info access from a0d7b954_ssh
20-08-04 07:53:05 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.32.1:64786 ssl:None [Connection refused]
20-08-04 07:54:18 INFO (SyncWorker_1) [supervisor.docker.interface] Clean addon_a0d7b954_ssh application
20-08-04 07:54:20 INFO (SyncWorker_1) [supervisor.docker.addon] Start Docker add-on hassioaddons/ssh-armv7 with version 7.4.1
20-08-04 07:54:21 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.32.1:64786 ssl:None [Connection refused]
20-08-04 07:54:22 INFO (MainThread) [supervisor.api.security] /host/info access from a0d7b954_ssh
20-08-04 07:57:24 INFO (SyncWorker_1) [supervisor.docker.interface] Clean addon_a0d7b954_ssh application
20-08-04 07:57:25 INFO (SyncWorker_1) [supervisor.docker.addon] Start Docker add-on hassioaddons/ssh-armv7 with version 7.4.1
20-08-04 07:57:28 INFO (MainThread) [supervisor.api.security] /host/info access from a0d7b954_ssh
20-08-04 07:57:29 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.32.1:64786 ssl:None [Connection refused]
```

**Comment by realjax** [comment]
Never mind.  Turns out it is because my password was not considered adequate by the plugin. Maybe you might want to mention that to a user instead of reporting 'bad gateway' and be done with it, which is so developerish.

**Comment by frenck** [comment]
@realjax That log you are sharing it not by this add-on, but from the supervisor.
The add-on log would have had a normal human-readable message.

**Comment by tristar500** [comment]
Do we have documentation somewhere that tell us what an adequate password is?

**Comment by sinclairpaul** [comment]
@tristar500 Please check the log, it validates your password against https://haveibeenpwned.com/Passwords

**Comment by tristar500** [comment]
@sinclairpaul In step 2 of the installation it says "Configure the username and password/authorized_keys options." Where is this done?

**Comment by vaderj** [comment]
> Never mind. Turns out it is because my password was not considered adequate by the plugin. Maybe you might want to mention that to a user instead of reporting 'bad gateway' and be done with it, which is so developerish.

For future users having this problem - Like everything else in HA, the SSH needs post-install configuring, which no one seems to ever mention.

https://github.com/hassio-addons/addon-ssh/blob/master/ssh/DOCS.md

Adding these two lines made the "Official add-ons" SSH work for me (make sure to remove preceding spaces):

username: homeassistant
password: 'plainTxtPasswordsAreAmateurAF'
authorized_keys:
  - ssh-rsa AASDJKJKJFWJFAFLCNALCMLAK234234.....






![image](https://user-images.githubusercontent.com/5408195/103484570-ab5e6e80-4da4-11eb-927e-cb816be33d8e.png)

**Comment by frenck** [comment]
@vaderj This an old and closed issue, furthermore, your comment is about the official SSH add-on, which is NOT this repository, does your comment does not apply or has anything to do with this repository at all.
