### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by aogriffiths** [hassio-addons/addon-ssh#163]
## Problem/Motivation

I'd like to be able to build addon-ssh locally, as a first step to developing / contributing to the project. However I'm unable to build the project locally (on my Debian machine) or remotely (using supervisor on my home assistant machine).

## Expected behavior

Successful build.

## Actual behavior

```
ERROR: unsatisfiable constraints:
  libuv-dev-1.38.1-r0:
    breaks: .build-dependencies-20201008.160235[libuv-dev=1.37.0-r0]
<< cut for brevity >>
returned a non-zero code: 2
```

## Steps to reproduce

```
git clone https://github.com/hassio-addons/addon-ssh

cd addon-ssh/ssh

docker run --rm -ti --name hassio-builder --privileged \
  -v `pwd`:/data \
  -v /var/run/docker.sock:/var/run/docker.sock:ro \
  homeassistant/amd64-builder -t /data --all --test \
  -i addon-ssh-{arch} -d local
```

**Comment by aogriffiths** [comment]
Just to add changing `libuv=1.37.0-r0` to `libuv-dev-1.38.1-r0` in the Dockerfile fixes the issue I raised but brings in more errors from the build. e.g.

```
  libxml2-utils-2.9.10-r5:
    breaks: world[libxml2-utils=2.9.10-r4]
  mariadb-client-10.4.15-r0:
    breaks: world[mariadb-client=10.4.13-r0]
```

I could keep updating these dependencies but I wondered why this is happening? Doesn't the build work for the core developers? If so why should it fail for me? The build is, after all, done inside docker so my build environment should be identical to the core developers'... shouldn't it?

(For reference I'm running a fresh install of Debian, in VirtualBox, running on a macbook pro and I've used this setup to successfully build the Home Assistant Operating System as per [these](https://github.com/home-assistant/operating-system/blob/dev/Documentation/getting_started_development.md) instructions.)

**Comment by sinclairpaul** [comment]
It's because the Alpine packages have been updated at source.  This addon is generally only built when maintenance is performed (you install it via a pre-built Docker container).

This is expected behaviour.

**Comment by aogriffiths** [comment]
Hi @sinclairpaul, that makes sense but what would you advise for me to be able to build this project on my local machine? I'm not having any trouble installing it in the way you describe, this issue is not being able to build it from scratch. 

The reason I want to build it from scratch is to experiment with some modifications, and hopefully create a pull request and contribute back, but I can't do any of that if I can't build the project and test my changes. 

What do the core developers do?

**Comment by sinclairpaul** [comment]
Update the dependency versions in the Dockerfile as you did previously.  You can run the Docker build directly.

I would also suggest using Discord to seek assistance.

**Comment by aogriffiths** [comment]
Thanks @sinclairpaul
