### ISSUE TITLE
Unable to negotiate

### ISSUE THREAD

**Issue by infernocs** [hassio-addons/addon-ssh#164]
Since the latest update I just can't seem to connect anymore.
I get this error:
Unable to negotiate with xxx.xxx.xxx.xxx port xxxxx : no matching key exchange method found. Their offer: diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,rsa2048-sha256,rsa1024-sha1 [preauth]

This is my config:

authorized_keys: []
password: xxxxxxxxxx
server:
  tcp_forwarding: false
compatibility_mode: true

Running on port 22 and forwarding works properly
But the connection gets terminated.

**Comment by frenck** [comment]
What is the client you are using?
