### ISSUE TITLE
Cannot open WEB UI when hassio embedded in iframe - auth cookie issue

### ISSUE THREAD

**Issue by rossbcan** [hassio-addons/addon-ssh#165]
Hi;

OS: OpenWrt x86_64
hassio, home-assistant: latest versions
hassio docker, installed SSH & Web Terminal via Add-on Store

When accessing hassio directly proxied: vhost hassio.$domain all ok
When accessing all of hassio via iframe proxied (embedded in OpenWrt menu system) everything except WEB UI accessible.
When accessing hassio via iframe proxied (embedded in OpenWrt menu system, open WEB UI), result:
```
Cookie “ingress_session” has been rejected because it is in a cross-site context and its “SameSite” is “Lax” or “Strict”.
```
and session fails due to auth.

here is relevant nginx proxy code:
```
server {
        listen          443;
        listen          [::]:443;
        server_name     hassio.rossco.dynu.com;
        add_header      X-Frame-Options "ALLOW-FROM https://192.168.10.1/ https://$server_name/";
        add_header      Content-Security-Policy "frame-ancestors 'self' https://192.168.10.1 https://$server_name/";
        location / {
                # Comment "#" following lines to allow internet access
                allow 192.168.0.0/16;
                allow 172.16.0.0/12;
                allow 10.0.0.0/8;
                allow 127.0.0.0/8;
                deny all;
                # End comment lines
                # hack, set all cookies to secure, httponly and samesite (strict or lax)
                # Need Nginx 1.19.3+ for this
                proxy_cookie_flags ~ secure httponly samesite=None;
                proxy_hide_header X-Frame-Options;
                proxy_hide_header Content-Security-Policy;
                proxy_pass http://192.168.10.1:8123;
                proxy_set_header Host $host;
                proxy_redirect http:// https://;
                proxy_http_version 1.1;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
        }
        location /api/websocket {
                proxy_cookie_flags ~ secure httponly samesite=None;
                proxy_pass http://192.168.10.1:8123/api/websocket;
                proxy_set_header Host $host;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
        }
}
```
nginx directive "proxy_cookie_flags ~ secure httponly samesite=None;" is supposed to alter cookie flags and works correctly for other proxied containers such as nextcloud.

Any idea what's happening and if I can configure or alter a file to avoid this?
Other suggestions?
FYI: part of www.rossco.org endeavors

Thanks;
Bill

**Comment by frenck** [comment]
Sorry, your method is not supported and have no idea.

**Comment by rossbcan** [comment]
can't you toss me a bone such as what file sets cookies and, config if any?

**Comment by frenck** [comment]
None. It is all handled by Home Assistant, not the add-on.

**Comment by rossbcan** [comment]
HA bug: https://github.com/home-assistant/frontend/issues/6550

**Comment by frenck** [comment]
ok, not sure how that is relevant for this add-on.
This add-on does not have any authentication for the web terminal whatsoever, as that is handled upstream. You are right now creating useless notifications in my inbox. Please don't.
