### ISSUE TITLE
Documentation update: "advanced mode"

### ISSUE THREAD

**Issue by Tahutipai** [hassio-addons/addon-ssh#166]
<Read: Assuming one is new to home assistant>

The installation instructions specific to search the Add-on Store for "SSH...", which fails on a clean install. One must enable advanced mode from the user profile first, which is non-obvious. (A new user would not be aware that such a thing exists)

Suggested updated install instructions:
1. Click your user name (bottom left of the HA screen) and ensure "advanced mode" is enabled.
2. Click "Supervisor", then "Add-on store"
3. Search the store for “SSH & Web Terminal”, and install it.
4. Configure the username and password/authorized_keys options.
5. Start the “SSH & Web Terminal” add-on.
6. Check the logs of the “SSH & Web Terminal” add-on to see if everything
went well.

**Comment by frenck** [comment]
Feel free to do a PR.
