### ISSUE TITLE
Fatal: You need to setup a login! error

### ISSUE THREAD

**Issue by barcik75** [hassio-addons/addon-ssh#167]
# Problem/Motivation

Hi, I am a novice HA user. Before, I used the version installed on the VM on the Raspberry. Recently I bought a second Raspberry (4 with 4GB RAM) especially for HA installations. I burned the disc image (32bit) on the SD card and started the HA. After the initial configuration, I wanted to set up an SSH connection. Found this add-on, installed it, unblocked port 22, and have a problem. On logs I have:

> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] cli: applying... 
[fix-attrs.d] cli: exited 0.
[fix-attrs.d] profile: applying... 
[fix-attrs.d] profile: exited 0.
[fix-attrs.d] ssh: applying... 
[fix-attrs.d] ssh: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] keygen.sh: executing... 
[13:10:48] INFO: Restoring host keys...
[cont-init.d] keygen.sh: exited 0.
[cont-init.d] profile.sh: executing... 
[cont-init.d] profile.sh: exited 0.
[cont-init.d] ssh.sh: executing... 
**[13:10:49] FATAL: You need to setup a login!**
[cont-init.d] ssh.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

I tried in Configuration set
> username: root

but it's not helped
In system logs I have:
> 20-11-13 12:10:43 WARNING (MainThread) [supervisor.addons.validate] Unknown options username
20-11-13 12:10:43 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning addon_core_ssh application

Probably got something wrong. Unfortunately, the manual did not answer my problem.

**Comment by frenck** [comment]
Please refer to the documentation for an example:

<https://github.com/hassio-addons/addon-ssh/blob/master/ssh/DOCS.md>

This is also available in the Home Assistant frontend. When clicking the add-on, a Documentation tab appears.
