### ISSUE TITLE
OS 4.19.127-v7l issue

### ISSUE THREAD

**Issue by Gamerayers** [hassio-addons/addon-ssh#168]
# Problem/Motivation

> After installing 4.19.127-v7l ssh no longer functions correctly.  Cannot connect.  I have tried a number of different methods to get this to work with none working.  Every time it seems to start, but never does.

## Expected behavior

> Use ssh

## Actual behavior

> When I click open webui it says bad port. 502.

## Steps to reproduce

> Upgrade to latest Raspberry Pi 4 Hassio OS

**Comment by sinclairpaul** [comment]
Please share the addon startup logs

**Comment by Gamerayers** [comment]
I am closing this.  So while I've tried it about 100 times and no logs and reinstalled, uninstalled, and finally gave up.  It is now just working and shows the logs.  So I apologize and thank you.

**Comment by sinclairpaul** [comment]
No problem, for future reference I am guessing there would have been an error in the Supervisor log if the addon logs were blank.
