### ISSUE TITLE
pb with Home Assistant Community Add-on: SSH & Web Terminal

### ISSUE THREAD

**Issue by erix22** [hassio-addons/addon-ssh#169]
# Problem/Motivation
since last night update Core 0.118.2 HassOS 4.17 (don't know which one made the difference) the characters on the ssh terminal addon are "blurry", it starts with banner and continue with the promt and all the commands I try to type.
it sounds like a "stty" parameter problem. 
> (Why the issue was filed)

## Expected behavior
normal display of the characters on the terminal
> (What you expected to happen)

## Actual behavior
all characters on the terminal are kind of "blurry", maybe wrong font characters..
> (What actually happened)

## Steps to reproduce
just click on the addon wait for the prompt and see

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

these are the informations inside the addon logfile:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] permissions: applying... 
[fix-attrs.d] permissions: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: SSH & Web Terminal
 SSH & Web Terminal access to your Home Assistant instance
-----------------------------------------------------------
 Add-on version: 7.7.0
 You are running the latest version of this add-on.
 System: HassOS 4.17  (amd64 / qemux86-64)
 Home Assistant Core: 0.118.2
 Home Assistant Supervisor: 2020.11.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] docker.sh: executing... 
[12:06:57] INFO: Docker support has been enabled.
[cont-init.d] docker.sh: exited 0.
[cont-init.d] mosquitto.sh: executing... 
[cont-init.d] mosquitto.sh: exited 0.
[cont-init.d] mysql.sh: executing... 
[cont-init.d] mysql.sh: exited 0.
[cont-init.d] ssh.sh: executing...
[12:07:35] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[12:07:40] WARNING: 
[12:07:40] WARNING: Logging in with a SSH password is security wise, a bad idea!
[12:07:40] WARNING: Please, consider using a public/private key pair.
[12:07:40] WARNING: What is this? https://kb.iu.edu/d/aews
[12:07:40] WARNING: 
[cont-init.d] ssh.sh: exited 0.
[cont-init.d] user.sh: executing... 
[12:08:04] NOTICE: Session sharing has been disabled!
[cont-init.d] user.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[12:08:10] INFO: Starting the ttyd daemon...
[12:08:10] INFO: Starting the Home Assistant STDIN service...
[12:08:10] INFO: Starting the SSH daemon...
Server listening on 0.0.0.0 port 22.

Server listening on :: port 22.

![screenshot 116](https://user-images.githubusercontent.com/7948501/99902418-94acfe00-2cb5-11eb-8282-3a8d15125819.jpg)

**Comment by frenck** [comment]
Might be theme related? I'm on the latest version myself as well...

**Comment by erix22** [comment]
@frenck thank you for your help
I am very new on Homeassistant, I even don't know what is a "theme", I mean I did not change "theme" and I think I am using the standard one.
How can I check this, please ?

**Comment by frenck** [comment]
On the default theming, this should not happen. I've been testing this the last couple of minutes, but I'm not able to reproduce this on my end (on several systems) 😞

**Comment by erix22** [comment]
I've tried to un-install and re-install and it's the same problem..
don't where to search...

**Comment by erix22** [comment]
@frenck 
I have an update. All my previous comments and issues were based on what I am seeing on my opened browser which is in this case is Firefox 83.0 (64 bits) on my Windows 7.
I've opened Chrome (on the same PC) and pointed it to my Homeassistant instance and click on your addon and it's working fine..
does it mean something to you ?

**Comment by erix22** [comment]
@frenck 
I have an update. All my previous comments and issues were based on what I am seeing on my opened browser which is in this case is Firefox 83.0 (64 bits) on my Windows 7.
I've opened Chrome (on the same PC) and pointed it to my Homeassistant instance and click on your addon and it's working fine..
does it mean something to you ?

**Comment by erix22** [comment]
The problem disappeared by itself...

**Comment by frenck** [comment]
Uh?

That is good and not good at the same time! 😟 

Please let me know if it returns!
