### ISSUE TITLE
mancata connessione con putty

### ISSUE THREAD

**Issue by zeroincondotta** [hassio-addons/addon-ssh#172]
# Problem/Motivation
non riesco a collegarmi con putty

my addon conf
ssh:
  username: root
  password: xxxxxxxxx
  authorized_keys: []
  sftp: true
  compatibility_mode: false
  allow_agent_forwarding: false
  allow_remote_port_forwarding: false
  allow_tcp_forwarding: false
zsh: true
share_sessions: false
packages: []
init_commands: []

port 22

**Comment by frenck** [comment]
Please file an issue in English.
