### ISSUE TITLE
I cant connect 

### ISSUE THREAD

**Issue by zeroincondotta** [hassio-addons/addon-ssh#173]
# Problem/Motivationnon

I can't connect by putty

my addon conf
ssh:
username: root
password: xxxxxxxxx
authorized_keys: []
sftp: true
compatibility_mode: false
allow_agent_forwarding: false
allow_remote_port_forwarding: false
allow_tcp_forwarding: false
zsh: true
share_sessions: false
packages: []
init_commands: []

port 22

I have a regular activate on duckdns a external IP like     xxxxxxxx.duckdns.org 
maybe It is not possible to connect by ssh  with  external IP???

**Comment by frenck** [comment]
Does it work on your internal IP when connected to the local network?

**Comment by santosonit** [comment]
Hello @frenck ! Awesome job! Thanks a million.
I haven't been able to connect internally, as well.
When trying it with a username and password, it gives me the following in the logs:
`Connection from 192.168.1.104 port 46150 on 192.168.1.106 port 22 rdomain ""
Connection closed by 192.168.1.104 port 46150 [preauth]`

...and this one on my terminal:
`The fingerprint for the ED25519 key sent by the remote host is
SHA256:key....
Please contact your system administrator.
Add correct host key in /home/antonio/.ssh/known_hosts to get rid of this message.
Offending ECDSA key in /home/antonio/.ssh/known_hosts:1
  remove with:
  ssh-keygen -f "/home/antonio/.ssh/known_hosts" -R "Internal IP"
ED25519 host key for Internal IP has changed and you have requested strict checking.
Host key verification failed.`

I've looked for info and tried a couple of fixes, but no success so far.

The 22 port is configured as per default...

Thanks a lot for any info that may lead me to the solution!

**Comment by zeroincondotta** [comment]
Me I solve with putty key generator and open port 22 on router
Now I connect in ssh in LAN and with external dns

**Comment by frenck** [comment]
This is your client that causes issues. It even gives you the instructions:

`remove with: ssh-keygen -f "/home/antonio/.ssh/known_hosts" -R "Internal IP" ED25519 host key for Internal IP has changed and you have requested strict checking. Host key verification failed.`

**Comment by santosonit** [comment]
It did work! Thanks. I feel a bit stupid as the instruction was right there.
At the same time, it may get a bit overwhelming to noobs, after playing with this for a while.
Cheers!
