### ISSUE TITLE
can not add the addo

### ISSUE THREAD

**Issue by cargial** [hassio-addons/addon-ssh#174]
# Problem/Motivation
I can not see/ intall the addon. 

## Expected behavior

To be able to update o reinstall.

## Actual behavior
I had the old addon and i wanted to update but it didn't allow me.
I resinstall it and try to add it again but it does not apear in the addon store. I tried to add the repository and it does not allow.
The system problem message:

[supervisor.store.data] Can't read repository information from /data/addons/git/319a9065/repository.json

Im runnig home assistant 0.92 (old hassio) on a rpi,

> (How can someone else make/see it happen)

## Proposed changes

It be grate, if you can not fix it, to be added in the repository where thera are more addons fom the comunity. (if this helps, becasuse the ones from the comunity i can see perfectly)
tkx

**Comment by frenck** [comment]
`319a9065` = not this add-on repository, I guess you are mixing things up.
