### ISSUE TITLE
I can not see/ intall the addon.

### ISSUE THREAD

**Issue by cargial** [hassio-addons/addon-ssh#175]
# Problem/Motivation

I can not see/ intall the addon. 

## Expected behavior
(I add more info)
I had the old addon and i wanted to update but it didn't allow me.
I wanted to resinstall it and try to add it again but it does not appear in the addon store. I have this repository added and it does not appear SSH (the other addons yes):
Franck Nijhof <frenck@addons.community>
https://addons.community
I tried to add the repository of ssh on its own and it does not allow. (https://github.com/hassio-addons/addon-ssh)
The system problem message:
21-01-01 13:02:31 ERROR (MainThread) [supervisor.store] https://github.com/hassio-addons/addon-ssh is not a valid add-on repository
21-01-01 13:02:31 ERROR (MainThread) [supervisor.utils.json] Can't read json from /data/addons/git/319a9065/repository.json: [Errno 2] No such file or directory: '/data/addons/git/319a9065/repository.json'

[supervisor.store.data] Can't read repository information from /data/addons/git/319a9065/repository.json

Im runnig home assistant 0.92 (old hassio) on a rpi,

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
`319a9065` is not this repository.

Furthermore, the community add-ons repository is enabled and installed by default.
