### ISSUE TITLE
Configuration file error although using basic confit

### ISSUE THREAD

**Issue by alve89** [hassio-addons/addon-ssh#178]
I just installed the add-on from the store and, after getting configuration file errors - I minimized the code (from the modified example code) to

```
ssh:
  username: homeassistant
  password: 'myPassword'
```

but I still get the following error in Configuration -> Check configuration file:

`Component error: ssh - Integration 'ssh' not found.`

I already restarted the server and the add-on and I also re-installed the add on, but this seems to be a basic problem - or am I doing something wrong?

**Comment by tjorim** [comment]
Seems like you are editing the configuration.yaml file instead of the add-on configuration. Check the config tab of the add-on to set the options.

**Comment by frenck** [comment]
@alve89, @tjorim is correct.

Go to the Supervisor panel, it will show you the dashboard with the installed add-ons. Click on the SSH add-on and next on the Configuration tab shown on the add-on page.

This will bring up an input dialog where the configuration for this add-on can be put into.

If you are still stuck, I can recommend joining our [Discord chat server](https://discord.gg/c5DvZ4e).

👍

**Comment by alve89** [comment]
Perfect, thank you. Maybe you could specify this in the installation guide (DOCS.md)?
But anyway - thanks for this very quick reply and help!

**Comment by frenck** [comment]
The problem is, @alve89, the documentation is next to the Configuration tab 😉

**Comment by alve89** [comment]
Haha, okay, I followed the guide here on GitHub... 🙈 But now I know that there's another configuration for add-ons. 😁
