### ISSUE TITLE
Username configuration case sensitivity

### ISSUE THREAD

**Issue by Salvora** [hassio-addons/addon-ssh#179]
# Problem/Motivation

The username for the configuration is not case sensitive

## Expected behavior

```
ssh:
  username: Paul
  password: '12345678'
```
You cannot ssh into the system with Paul username. 

## Actual behavior

Using "paul" works so I gather, the configuration is not case sensitive. I would expect it to be case sensitive.

## Proposed changes

Can you make the configuration case sensitive? Or is there any other way to force it?

**Comment by frenck** [comment]
The use of uppercase characters in Linux usernames is highly discouraged and, in some cases, will even cause issues.

This is not an add-on limitation.
