### ISSUE TITLE
ssh access to VM with qcow2

### ISSUE THREAD

**Issue by deltabert** [hassio-addons/addon-ssh#188]
# Problem/Motivation

> New to Proxmox, I created my first VM for hassio wth qcow2. Home Assistent Superviser is running OK. Next i would like to access the HA/VM instance via ssh. So i try to install the SSH & Web Terminal from the Supervisor Ad-on-Store.
But it is not available in the ad-on store... 
Is this by design, perhaps it is not possible to have this in a Proxmox VE? Or is this a mistake... 
If it is impossible to have ssh support in qcow2, is there an other way to get ssh access to mu HA instance?

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
Enable Advanced Mode for your HA user.
