### ISSUE TITLE
Persistant configuration customizations

### ISSUE THREAD

**Issue by mmiller7** [hassio-addons/addon-ssh#204]
# Problem/Motivation

> When restarting the addon, any custom entries to ~/.vimrc are lost (for example, I want `set mouse-=a` to not move around when I click windows by default)

## Expected behavior

> I expect changes to my ~/.vimrc config file to persist when the addon or server is restarted

## Actual behavior

> The ~/.vimrc file is erased

## Steps to reproduce

> Create a ~/.vimrc file with something in it
> Restart the addon
> Log into SSH
> Look at ~/.vimrc; the file is gone

## Proposed changes

> Idea 1: make the file persistent or linked to a persistent location (it looks like this may have been done for .bash_history already?)
> Idea 2: add a "configuration" box for the addon to put my custom config for common ~/.vimrc and similar in that will be populated at startup
> Consider also making other common configuration (e.g. ~/.bashrc and any others I'm missing) persistent in the same way

**Comment by frenck** [comment]
The `init_commands` option allows you to customize this in any way you like:

https://github.com/hassio-addons/addon-ssh/blob/main/ssh/DOCS.md#option-init_commands
