### ISSUE TITLE
"Connection Closed" every time Terminal is started.

### ISSUE THREAD

**Issue by clowg** [hassio-addons/addon-ssh#205]
# Problem/Motivation

> I have installed the addon into Home Assistant OS 5.11, core-2021.2.3 running in a Hyper-V VM.  When I start the Terminal under Firefox on Windows 10, I only ever get a grey screen with "Connection Closed" in the middle of the screen.

## Expected behavior

> Get a Logon prompt?

## Actual behavior

> "Connection Closed"

![Terminal Conn Closed](https://user-images.githubusercontent.com/20178585/107693410-f9a34d80-6d12-11eb-956b-b9603a5369d1.png)

**Comment by clowg** [comment]
Here is my config:

ssh:
  username: admin
  password: <my pwd>
  authorized_keys: []
  sftp: false
  compatibility_mode: true
  allow_agent_forwarding: false
  allow_remote_port_forwarding: false
  allow_tcp_forwarding: false
zsh: true
share_sessions: false
packages: []
init_commands: []

**Comment by MisterT87** [comment]
1+ same error here

**Comment by clowg** [comment]
I had to use a non-Firefox browser to get it to work.

**Comment by TroelsS** [comment]
> I had to use a non-Firefox browser to get it to work.

I have the same problem when I use Firefox. Is there any way to fix this?
