### ISSUE TITLE
Since v8.0.2: administrative init commands wont work anymore

### ISSUE THREAD

**Issue by MisterT87** [hassio-addons/addon-ssh#211]
# Problem/Motivation
On v8.0.1: I used this addon (also) with disabled "protection mode" to send administrative init commands at addon start.
These commands changes files on the read only filesystem.
(needed for RPi3 GPIO Pin manipulation).

## Expected behavior
Just normal addon start with disabled protection mode :D

## Actual behavior
Addon wont start up because init_commands cant be executed anymore:
`sh: can't create /sys/class/leds/led0/brightness: Read-only file system`

Also wont work If I try using this command with sudo...

## Steps to reproduce
Use an  RPi3 (dont know If it works the same way on newer/older RPis)
Disable "Protection mode" in hassio
Login to the system with SSH

try the following command: `sh -c 'echo 0 > /sys/class/leds/led0/brightness'`

Anyway thank you for this addon and the good work :)

greetings

**Comment by MisterT87** [comment]
Update: nevermind - found a workaround for it :)

**Comment by denics** [comment]
Hi @MisterT87  do you mind share your workaround? Apparently I got the same problem while trying to mount my boot partition in non protected mode :(

**Comment by MisterT87** [comment]
@denics 
I am assuming you are using Home Assistant OS and you have access to your configuration.yaml.
Home assistant itself has admin rights for sure but mounting /boot partition in home assistant I really dont recommend it !

Thats not for this kind of users u know ? For something like this Home Assistant Supervised edition is more recommended !
You really can break your homeassistant or security keep that and mind.
Can be also that you cant mount /boot partition even with root rights (dont know) for example if the HA devs created a seperated overlay filesystem for /boot -> then youre lost

**! Keep also in mind: Home assistant dont use "a normal linux distro" it using ResinOS thats optimized for docker usage and dont have standard linux commands - so I really hope you know what youre doing !**

*enough** CAUTION text - now the howto :D ->*

- open configuration.yaml and define a shell command (I recommend to use a seperate shell script if u need mor then 3 commands - for clarity)

```
shell_command:
  command_name: mount /dev/example /boot; example --option 'echo example > example.txt'
```
2nd line: command_name you can completly change by yourself (you have to remember) and the second command after " ; " is a wrong shell command... its just to show you can use multiple command in one line - its " ; " seperated.

- save configuration.yaml file
- then go to Home Assistant OS web GUI
- Go to Settings / Server Controll -> Restart Home Assistant (For reload new lines in configuration.yaml)
- After Restart: Go to Settings / Automations / Add Automation -> click on "Start with an empty automation"
- Choose your preffered name under "new automation" and use the following settings:
```
In "new automation" section:
Modus: Single (Default)

"Trigger" section:
Trigger type: Home Assistant
Event: Start

"Conditions" section: nothing - keep it empty !

"Actions" section:
Action type: Service
Service: Here you choose what you have defined in your configuration.yaml - for the example above -> shell_command.command_name
```
- Save it !
- You are done: now under Settings / Server Controll -> Restart Home Assistant again (for testing your autostart commands)

**! WARNING: You can only execute admin commands related for host OS - If you want execute commands in other docker container (Add-Ons) that dont work -> in this case you need another Add-On which also already exists**

**Comment by denics** [comment]
Thanks @MisterT87 , nice workaround. In the meantime, I have found a simpler way: 
```
sudo docker exec –it homeassistant /bin/bash
```

Simply replace homeassistant with the container you want to login and you'll be root. I am facing now another issue and perhaps you can help.

I changed the config.txt file, I wanted to enable rpi camera on my rpi3 so I simply added start_x=1 at the bottom of my config.txt (monted as above) and now my rpi is not booting anymore from the external drive :(

Any idea? am I missing a flag (like boot in /sda1 partition?)

Thanks!

**Comment by denics** [comment]
yep, it was missing the boot flag. I do not know why, when logging in with docker and then mounting, you lose the boot flag
Thanks
