### ISSUE TITLE
Won't start, round 2: 502 Bad Gateway

### ISSUE THREAD

**Issue by igorsantos07** [hassio-addons/addon-ssh#238]
# Problem/Motivation

I'm facing the same issue reported at #154 that was closed without a proper/clear solution.

## Expected behavior

It should work? The add-on doesn't include any visible options screen, settings, nor further instructions.
The original "Terminal & SSH" add-on works fine and I never had to configure anything for it, it worked out of the box.

## Actual behavior

Black screen, no response nor error - got to open the terminal to see a meaningless 502 Bad Gateway response.

## Steps to reproduce

Fresh HA install, include the add-on, try to open it.

## Proposed changes

If this is indeed a lack of configurations, add clear instructions to the readme on how to configure it after installation, if there's no better UI to solve that.
I'm a seasoned web developer and used to Linux usage, but a complete newbie to HA and I'm not even sure how to start debugging this. Not to mention I think I shouldn't _need_ to debug it to understand "what I did wrong", as it seems it was the case in the original issue.

> sorry, I pressed enter by accident at the beginning and ended up creating a blank issue lol

**Comment by frenck** [comment]
Please provide logs.

**Comment by igorsantos07** [comment]
Easy for you that knows where they are - I have no clue and I'm trying to google that information. Any hint on where to find the add-on logs? There's nothing related at Configuration > Logs...

**Comment by igorsantos07** [comment]
AH, THERE ARE TABS ON THE ADD-ON PAGE!!!

**Comment by igorsantos07** [comment]
Yep, it's still the same problem: lack of configurations and having to resort to logging to understand why I was presented with a black page when the main description tells me nothing of what to do.

Suggestions:
1. include a new section at the readme instructing on proper post-install steps (I can PR that if you want)
2. maybe understand why there's an error and provide a more helpful message instead of a 502 error with the standard description, if that's possible - and then bring that into the UI instead of the black screen. Otherwise, instead of the black screen, show a generic message with "common issues" that could point us to the Config tab to check if anything seems missing (according to a link to the docs), and the Logs tab to see further messages.

**Comment by frenck** [comment]
> include a new section at the readme instructing on proper post-install steps  

![image](https://user-images.githubusercontent.com/195327/114063648-2306d280-9899-11eb-8e4a-48f6f8c5e5ec.png)

Already has that.

> maybe understand why there's an error and provide a more helpful message instead of a 502 error with the standard

That is not something an add-on can provide.

**Comment by igorsantos07** [comment]
What about a lack of actually understanding user behavior and stop blaming it all on us?
What about #2 is meaningless and #4 is as well because said user never had to do this for any other add-on before?
What about users read docs but don't understand because the writer knows-it-all and thinks docs is enough for them, but didn't care thinking how a new user would read that?

What about a pinch of courtesy?

And, now that I'm done "responding" to your irony: what about a PR to make that docs more palatable, since it seems this is not the first time the docs fail you?

**Comment by frenck** [comment]
> what about a PR to make those docs more palatable, since it seems this is not the first time the docs fail you?

Actually, honestly, with an estimate of around 100-150K instances active with my add-on, the complaints about that have been neglectable.

But considering this was your first response after I asked for logs:


> Yep, it's still the same problem: lack of configurations and expecting a user to check logging to understand why they were presented with a black page when the main description tells them nothing of what to do.

I completely lost interest in anything else you had to say. Feel free to uninstall the add-on and hate me for it.

**Comment by igorsantos07** [comment]
How would you expect a kind answer to a crude "provide logs" answer? I had already referenced another issue where someone else also had no clue where to find logs, and that wasn't answered either. You shouldn't expect everyone to know everything about HA. If I knew, I wouldn't be opening the issue in the first place since, as you're aware, the logs are clear. Thus, it would be nice enough if you said something like "provide logs, these are at the top bar". That's also what I was going to PR to the main readme.

Again, I'm saying this from a users point of view, and I don't want to hate you - I want to improve this software and the docs opening an issue, providing a PR, and asking some kindness from the dev. Nice, you have tons of active users on your add-ons, but that doesn't grant you the right to be rude with a newbie. A user is a person, just like you are. If you don't like ironic answers, don't be rude or neglect issues in the first place.

**Comment by frenck** [comment]
I wasn't rude in any way. I just asked for the logs. Based on that output I would have just helped you.
You decided to take this route.

As said, I lost interest.

Have a nice day.
