### ISSUE TITLE
Passwords should be auto-generated upon install

### ISSUE THREAD

**Issue by igorsantos07** [hassio-addons/addon-ssh#239]
# Problem/Motivation

Follow-up to #238 and #154, where users had trouble using the add-on for failure to configure it properly after installation.

## Expected behavior

User is supposed to understand docs and configure the add-on properly before use, otherwise they're presented with a black screen with no messages.

## Actual behavior

Users are not expected to understand "developerish" docs and docs should be more palatable. Furthermore, why does the user needs to manually fill in a password that's not used in the add-on? Could that be auto-generated from random words upon installation?

## Proposed changes

- Accept a PR to make docs more readable instead of being rude on the topic.
- Actually discuss the issue, since I was about to ask about auto-generated password and the previous issue got locked.

**Comment by frenck** [comment]
I was clear in my last response. Please stop this. Thanks already 👍

**Comment by igorsantos07** [comment]
Sorry, you weren't clear - just like the docs weren't. I just saw meaningless answers of "you're dumb I don't want to read you anymore".

I had a follow-up and honest question about the issue, and you don't want to talk about it nor accept the PR. I'm honestly trying to leave this to the side and focus on the issues I saw, as a UX developer.

**Comment by igorsantos07** [comment]
Sorry, you weren't clear - just like the docs weren't. I just saw meaningless answers of "you're a user who doesn't know how to read docs and I don't want to read you anymore".

I had a follow-up and honest question about the issue, and you don't want to talk about it nor accept an improvement PR (that I was about to look at how to start). I'm honestly trying to leave this childish discussion to the side and focus on the issues I saw, as a UX developer.

**Comment by frenck** [comment]
> you're dumb I don't want to read you anymore

I didn't say that. And again; not interested; which I am now telling you for the 4th time.

**Comment by igorsantos07** [comment]
That's pretty much how you sounded in the previous issue, with crude answers and blaming us for not "reading the docs properly".

So you're not interested in improving the software to new users because you got a grudge with the way an issue was handled?
I just saw your profile, you're indeed quite assholic at the first sight. Have a nice day and best of luck.
