### ISSUE TITLE
Hello again / sorry / HA description seems outdated

### ISSUE THREAD

**Issue by igorsantos07** [hassio-addons/addon-ssh#240]
> Getting rid of the template so it's easier to get to the point.

First of all, I can see we started with the wrong feet. I was aggressive right from the issue's body after I saw two people were also clueless about the logs and got silenced instead of an answer. I could've been neutral instead, but chose to be passive-aggressive - I'm sorry.
Just like you said, add-ons are not able to give useful error messages on the UI, it's also not the add-on's responsibility to teach users about HA UI. I _never_ saw those tabs at the top with further docs and logs, so I was completely clueless on where to find the logs you requested.

The actual root issue: I skimmed over the readme because I thought it was the same thing I had already seen on the add-on page inside HA - which didn't help me with the issue. **Turns out... it's outdated?** Or is it an outdated copy? Well, the important part is: it's missing the "read the full docs" link, which would take me to the part you screenshotted and solve my issue.
Is that something that can be updated? Or a HA bug somehow?

And, not trying to repeat myself all over again, but do you think it's possible to add something about the install procedure to that first page we see in HA, once it gets updated? Maybe "read the full docs here - it includes post-install instructions". I'd bet I had the same behavior the other guys had - didn't notice the top tabs, read the description twice, didn't find anything, went to GitHub.  
I can PR some changes on that matter, if you allow me.

And again, sorry for that mess. I definitely could be kinder at the start.

**Comment by sinclairpaul** [comment]
I'll chime in here a bit :)

Before you install the addon, there should be an Info and Documentation tab.  Which part do you believe is outdated?, as it show ok on my install.

The challenge with documenting specifics around the HA UI, is that it can and likely will change, also should we document that in every addon, how do we maintain it etc.  I haven't looked at the HA documentation itself around addon installs, but I would suggest if there needs to be clarification it should likely be there.

**Comment by sinclairpaul** [comment]
I'll also just add, the goal is to make addon installation as easy as possible, anything that is marked as advanced (which this is), likely needs more configuration.

**Comment by igorsantos07** [comment]
Yeah! I'm just trying to be clear that I was expecting something that isn't the add-ons responsibility. You're 100% right there. It's confusing but it's HA fault, if ever. I _never_ saw those tabs at the top. My guess is that the eye jumps from the add-on title and below, instead of going up.

What I mentioned as outdated is the Info tab - because I believe that's the same as the repo's README?

And, to make my point clearer, I believe the Info tab (the first one we see) should include some reference to where the installation instructions are (since these would be somewhere else), instead of having to jump to the Docs tab to find these.

**Comment by sinclairpaul** [comment]
The application (HA) splits the info and documentation into different tabs, essentially in the repo there is a readme.md and docs.md, which get presented in the different tabs.

There really isn't much we can do about it from an addon perspective, we can't technically put a link into the docs from the readme and have it displayed in your instance unfortunately.

Again maybe the feedback should go on the HA forums around how and when to display docs (maybe make the Documentation tab bright pink :smile: ), either way there really isn't much we can do on the addon so we should probably close this out.

Maybe we could add to every addon, "click the documentation tab", rather than the generic "check the logs" however this kind of increases maintenance.

**Comment by igorsantos07** [comment]
I'd say call it "check the logs tab" instead of just "check the logs" would be handy for clueless people haha

Also, it's indeed confusing! The add-ons actually have two readme files, the one shown on GitHub and the one from the Info tab!
I'll create an open topic on the HA forum and see if there's any point on improving that UI.

I'm also checking how I got to install other add-ons without ever seeing those tabs:
- "Google Drive backup" does link to the GitHub readme or to the web UI (because they can configure from there, which is not the case here)
- DuckDNS: I don't recall how I found the settings for this one LOL
- I have a faint memory of an "options" button around those "restart" / "open web ui" buttons... but I guess that's a false memory? :joy: 
- other add-ons don't need settings at all to work. So, to be easy on clueless users, I think a link to the "github readme" could be included? Or a mention to "look at the docs tab for further instructions"?

Also, I'd like to bring back my second question from the initial trouble: would it make any sense to have a random, auto-generated password, since that password isn't necessary to use the WebUI? If they want to connect via SSH directly, they would then need to use the settings to configure a key or password, as they do now, but for basic use the add-on would be able to work out of the box.

**Comment by sinclairpaul** [comment]
> "Google Drive backup" does link to the GitHub readme or to the web UI (because they can configure from there, which is not the case here)

They link to Github that I see, which really isn't the best User Experience imho.

In previous releases the logs were shown on the main page.

Again, there is a documentation tab, if it isn't obvious to users it should be a request to the HA project.

The password question is really a separate issue, I will be honest in the fact that the number of issues we get logged on Bitwarden around the token, users generally don't take a note of pre-generated data. 


Can we please close this out?, I don't see that we will be making changes based on this discussion.

**Comment by igorsantos07** [comment]
Yeah, the UX isn't the best but I'm also not sure how to improve that yet.

Thanks for the answers, then :)
