### ISSUE TITLE
Visual issue, font garbled in web front-end

### ISSUE THREAD

**Issue by netweaver1970** [hassio-addons/addon-ssh#242]
# Problem/Motivation
Visual issue, font garbled in web front-end, seems like pixel column is missing

## Expected behavior
crisp font show so clearer to read

## Actual behavior
garbled font shown

## how to reproduce
just open up the web SSH front-end from within HA and see

## Proposed changes
??

Add-on Version 8.1.1
Example screenshot:
![image](https://user-images.githubusercontent.com/18028618/114357450-08bb4600-9b72-11eb-9ef3-d26c8e92a3cf.png)

Thanks.

**Comment by frenck** [comment]
I can't reproduce this. Any specific browser? browser settings? font customizations? zoom?

**Comment by netweaver1970** [comment]
Browser is Brave, no deliberate font changes, zoom on 100%. Never had this behavior in any other program. very weird.
at zoom 140% it's better but still some pixels garbled, clearly right most column.
![image](https://user-images.githubusercontent.com/18028618/114374168-a23f2380-9b83-11eb-9f41-b286dc70220e.png)

**Comment by netweaver1970** [comment]
in Chrome all is fine. At least it's a workaround. I don't need it every day anyway. 

Related to Brave, I've found below link but even with my 2nd screen decoupled, I still get the distortion. https://community.brave.com/t/font-rendering-issues-with-brave-on-windows/121358/14

Seems there were/are more issues with font rendering in Brave, using NVIDIA cards. So most likely nothing HA add-on related. So I'll close the issue.

Cheers.

**Comment by frenck** [comment]
Thanks for letting me know! Always good to keep in mind in case it comes along again.

**Comment by Apocrathia** [comment]
I have the same issue in Brave on MacOS, but I'm not using an Nvidia GPU. This may simply be specific to Brave. Everything looks fine in Safari. I know the issue is closed, but just adding additional information.
