### ISSUE TITLE
Support Prereqs for VSCode SSH Server

### ISSUE THREAD

**Issue by bryantlee** [hassio-addons/addon-ssh#246]
# Problem/Motivation

Hello! VSCode supports native SSH connections to hosts.  Notably to access the file system on a host.  When trying to connect via SSH using this plugin, it appears some dependencies are not available.  See: https://code.visualstudio.com/docs/remote/linux#_remote-host-container-wsl-linux-prerequisites

## Expected behavior

Connecting using the official VSCode SSH Plugin https://code.visualstudio.com/docs/remote/ssh

## Actual behavior

![image](https://user-images.githubusercontent.com/9112254/115145134-1105fc00-a01e-11eb-89a1-6c7b30a11d66.png)

## Steps to reproduce

Connect using https://code.visualstudio.com/docs/remote/ssh

## Proposed changes

Include necessary depends for this found here: https://code.visualstudio.com/docs/remote/linux#_remote-host-container-wsl-linux-prerequisites

**Comment by sinclairpaul** [comment]
The container uses Alpine, as stated on the page you linked, it is not supported for Remote - SSH connections.
