### ISSUE TITLE
init_commands does not work

### ISSUE THREAD

**Issue by mmiller7** [hassio-addons/addon-ssh#257]
# Problem/Motivation

> Need persistent vimrc, recommendation was to use init_commands option

## Expected behavior

> I expect the init_commands option as listed in the documentation example to work

## Actual behavior

> WARNING (MainThread) [supervisor.addons.options] Option 'init_commands' does not exist in the schema for Terminal & SSH (core_ssh)

## Steps to reproduce

> Put the example init_commands from documentation for addon-ssh into the ssh configuration options and restart the addon, then check supervisor system logs
https://github.com/hassio-addons/addon-ssh/blob/main/ssh/DOCS.md#option-init_commands
```
init_commands:
  - ls -la
```

## Proposed changes

> fix init_commands to work correctly, or provide alternative customization for persistent user configuration

**Comment by sinclairpaul** [comment]
> Terminal & SSH (core_ssh)

The error suggests you are using the core SSH addon, not the community one.
