### ISSUE TITLE
Terminal Font is hard to read on Firefox.

### ISSUE THREAD

**Issue by bartdorsey** [hassio-addons/addon-ssh#258]
# Problem/Motivation

> When using the Terminal on Firefox, the font is hard to read. In Chromium based browsers it looks fine

## Expected behavior

> Font should appear like this: 

![image](https://user-images.githubusercontent.com/362049/117467982-d951ec00-af19-11eb-8c24-234d4138d6fc.png)

## Actual behavior

> Font looks like this:

![image](https://user-images.githubusercontent.com/362049/117468035-e7077180-af19-11eb-9dcf-4d2d1b87f650.png)

## Steps to reproduce

> Login and use the web terminal plugin on Firefox

**Comment by Final-Hawk** [comment]
Same issue. Would like to use it but when you can't read the text its hard

**Comment by n8detar** [comment]
Brave Browser (Chrome Based) with Brave Shields (Blocks Ads, Cross-Site Tracking, etc) enabled has the same issue. Disabling fixes the issue.
If it helps the only thing Brave is blocking appears to be (Categorized as: Trackers & ads blocked): homeassistant.example.com/cdn-cgi/apps/head/PJ0CejcXwwUh-WXzsbAYvWi4p_k.js

**Comment by Final-Hawk** [comment]
In my case I have managed to fix this issue by disabling “duckduckgo privacy essentials” addon in firefox.

**Comment by bartdorsey** [comment]
Interesting, is this using a google font and is duckduck go blocking it?

**Comment by frenck** [comment]
This is an issue with TTYd, and is not controlled by this add-on.
If upstream publishes a fix, I'm happy to update.

Closing it at this end.
