### ISSUE TITLE
Error since last update of addon

### ISSUE THREAD

**Issue by DavidFW1960** [hassio-addons/addon-ssh#259]
# Problem/Motivation

> (Why the issue was filed)
Everytime I use the terminal to update Home Assistant I get this error since the last time the addon was updated.
## Expected behavior

> (What you expected to happen)
Expect no errors as before
## Actual behavior

> (What actually happened)
Error every time - doesn't cause any problems and HA updates perfectly. The error comes up almost instantly even before HA restarts with the new image.
error:
```
Post "http://supervisor/core/update": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
## Steps to reproduce

> (How can someone else make/see it happen)
ha core update --version 2021.5.0
## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
This is a problem with the Home Assistant CLI, not the add-on. Please report your issue upstream. Thanks 👍
