### ISSUE TITLE
RFC: Expand addon for advanced users

### ISSUE THREAD

**Issue by ndarilek** [hassio-addons/addon-ssh#26]
# Problem/Motivation

I keep encountering situations where I really need an advanced view under the hood, but I see no easy way of getting one:
 * I want to enable Home Assistant's CEC module to autoselect HDMI inputs on media player events (I.e. if my Chromecast starts, switch to the Chromecast input, otherwise switch to the RPi's input for TTS.) This requires me to use cec-client to scan connected devices, but there is no way to do this via Hassio.
 * I want to run Docker directly to introspect local images, check container status, etc.

## Expected behavior

I'd like some way as an advanced user to look under the hood. I'm fine with Hassio managing things, wiping out containers it doesn't know about, and generally managing the system as it sees fit. But every time I find some "Make your RPi work with X" howto and think "I'll package an addon for that," I find myself battling with how to perform anything more advanced than listing files and interacting with Hassio via its very limited CLI.

## Actual behavior

Hassio prevents me from having any meaningful insight into what it's doing. So I have no way of seeing what hardware is connected and how to address it, no way to identify why Docker builds may be failing, etc.

## Steps to reproduce

Try doing anything more complex than poking Hassio directly. E.g. try [this howto](https://blog.gordonturner.com/2016/12/14/using-cec-client-on-a-raspberry-pi/) to scan for CEC devices in order to configure Home Assistant's hdmi_cec component.

## Proposed changes

I'd like to map all of /dev, and maybe /var/run/docker.sock, into SSH containers. I understand this would enhance the scope of the SSH addon somewhat, but I see no other way to do anything more advanced with Hassio, other than keeping another SD card with Rasbian around and hoping that hardware addresses and other critical details don't change between Rasbian and Resin. I don't know if addon configuration allows mapping arbitrary files and the entire device tree, so maybe it doesn't and this is a dead end idea.

Thanks.

**Comment by frenck** [comment]
@ndarilek Thank you for your suggestion.

For the upcoming major release (v3.0), I'm going to enable everything, that can be enabled.
Nevertheless, for an add-on, it is impossible to get access to the Docker socket.

**Comment by frenck** [comment]
All access possible will be provided in the next release (`v3.0.0`).
Closing this now.
