### ISSUE TITLE
What is the dir and filename for the plug-in configuration?

### ISSUE THREAD

**Issue by rgusick** [hassio-addons/addon-ssh#263]
# Problem/Motivation

Reading instructions from https://github.com/hassio-addons/addon-ssh/blob/main/ssh/DOCS.md it says: "Configure the username and password/authorized_keys options." but gives no additional directions on which file to modify/create

**Comment by sinclairpaul** [comment]
Configuration for addons is common across Home Assistant, and performed at the Configuration tab

![image](https://user-images.githubusercontent.com/24625998/118298128-1172a500-b4ad-11eb-834b-344b10349c49.png)
