### ISSUE TITLE
Service call shell_command not working

### ISSUE THREAD

**Issue by PablexXXXX** [hassio-addons/addon-ssh#264]
# Problem/Motivation

> After puting a shell_comman on the configuration.yaml is possible to call a service shell_command but it isn`t the same as running it from the terminal (it seems the service uses the home assistant core conteiner for the service and not the addon conteiner).
When using the addon in the front end (web interface) everything works, ssh logins etc, but nothing works when calling the service from home assistant so it is not possible to automate anything.

## Expected behavior

> When calling the shell_command service it would be awesome that everything go just like from the addon web interface.

## Actual behavior

> No commands works when calling the shell_command service. In the log appears "code 255"

## Steps to reproduce

> Have a service that let us send commands automaticaly.

**Comment by PablexXXXX** [comment]
Solution here.

In the shell command it must be specified what keys to use.

https://blog.ceard.tech/2020/05/home-assistant-docker-and-using-ssh.html

**Comment by frenck** [comment]
This isn't an add-on issue.
