### ISSUE TITLE
Allow Configurable Shell

### ISSUE THREAD

**Issue by bah2830** [hassio-addons/addon-ssh#27]
# Problem/Motivation
While zsh is great for many it may not be the preferred choice by all. I am old school and use bash for everything. This busybox container has bash installed but it requires it to be started manually after logging in.

## Proposed changes
There should be a way to choose one of the available shells at login from the configuration json. Would also be nice if the .zshrc or .bashrc files would persist across a restart.

**Comment by frenck** [comment]
I like this idea!
I'm going to try to fit it into the upcoming mayor release.

**Comment by frenck** [comment]
I'm not going to make this part of the next major release. I'm going to push this up a little.

**Comment by frenck** [comment]
Don't mark it stale yet... addons-assistant...

**Comment by sjthespian** [comment]
I'll second this request as I'm another old fart and don't want to learn a new shell. :-)

**Comment by casenjo** [comment]
Recently reinstalled this add-on after not updating it for a while. Jumped from ~2.5 to 3.5 and now zsh caught me by total surprise hahaha
Would love to have this option :)

**Comment by casenjo** [comment]
Oh really! Sorry, my bad :)
Then I think something in the configuration is what changed things around
for me haha

**Comment by sjthespian** [comment]
The bot wants to make this a stale issue again... any updates on when you'll have time to add this as an option?

**Comment by frenck** [comment]
I have no idea, this is all done in my spare time. So whenever I feel like it (sorry I know that sounds unfriendly, but that is how it is).

Feel free to open a PR to implement it though!

**Comment by corvy** [comment]
I would also love this! I use nano to edit config files in HA and when I do page-up/down I loose overview and have to close the file. Basically zsh with nano seems to be a horrible solution. I will come back to this great plugin once I can disable zsh ;)

**Comment by josemotta** [comment]
Yes, I endorse this good idea! I got some fuzzy screens opening a ssh session using bash on Windows 10.

**Comment by WhiteNoseThunderPants** [comment]
I would like to have the .zshrc file persistent like the history file currently is. I noticed this file in the build [40-zsh.sh](https://github.com/hassio-addons/addon-ssh/blob/master/ssh/rootfs/etc/cont-init.d/40-zsh.sh), and was wondering if that would be the best way for making the .zshrc file persistent as well. If so, I would be happy to attempt it and submit a PR. I just need some direction @frenck .

**Comment by Dortamur** [comment]
I too would prefer bash.
Would it be possible to have a "shell" config option, to select "zsh" or "bash"?

**Comment by guiguid** [comment]
Hi all, I prefer fish, is the option above can be : "zsh", "bash" or "fish" ? 
Thx
(One people, one shell....)

**Comment by justinmayer** [comment]
I would _**love**_ to be able to choose [Fish](https://fishshell.com) as my default shell! 🐟

**Comment by frenck** [comment]
This is not going to be implemented. Indeed, now bash, next fish.

The `packages` option would allow you to install extra packages like `fish`.
The `init_commands` list allows you to execute commands on startup, which allows you to modify the environment to your liking. Including the default shell.
