### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by neil2048** [hassio-addons/addon-ssh#278]
# Problem/Motivation

> Installation Issue

## Expected behavior

> Install to work

## Actual behavior

> Throws error message

*Failed to install add-on

Can't install ghcr.io/hassio-addons/ssh/amd64:8.2.3: 404 Client Error for http+docker://localhost/v1.40/images/ghcr.io/hassio-addons/ssh/amd64:8.2.3/json: Not Found ("no such image: ghcr.io/hassio-addons/ssh/amd64:8.2.3: No such image: ghcr.io/hassio-addons/ssh/amd64:8.2.3")*

## Steps to reproduce

> Add HASS.io Community Addon's Repo, Install "SSH & Web Terminal" version 8.2.3

![image](https://user-images.githubusercontent.com/39128928/121170990-d5352900-c84d-11eb-96b7-2de4d09e8b5e.png)

**Comment by frenck** [comment]
The image does exist and can be verified yourself here:

<ghcr.io/hassio-addons/ssh/amd64:8.2.3>
