### ISSUE TITLE
Cant remove password login function after setting up private/public key

### ISSUE THREAD

**Issue by Hansie9999** [hassio-addons/addon-ssh#279]
# Problem/Motivation

The log file told me logging in with a username/password is not secure (I agree)
So I set up a private/public key option and tested this, it works,
But at the moment I can also still login with my username and password combination.

The instructions tell me this 
"Option ssh: password

Sets the password to log in with. **Leaving it empty would disable the possibility to authenticate with a password.** We would highly recommend not to use this option from a security point of view."

However, if I leave the password option blank and try to save the configuration, I get this error ;
"Mislukt om add-on configuratie op te slaan, Missing required option 'password' in SSH & Web Terminal"

I also tried completely removing the "password:" option and this also does not help, same error when saving.

I am probably doing something stupid, but I dont know what,

## Expected behavior

Setting up my SSH that I can ONLY log in with my public/private SSH key option.

## Actual behavior

after setting up public/private SSH key, I can now log in with that option, but I can also STILL log in with my username/password combination (and the log file also keeps telling me that this is unsafe)

Please let me know how I have to set this up correctly.

thank you,

Hans

**Comment by frenck** [comment]
This is an upstream bug with Home Assistant, which I've filed an issue for.

As a workaround, you should be able to change it when using YAML mode.

**Comment by Hansie9999** [comment]
Thank you for your extremely fast answer :)

Good to know its not me beeing stupid hehe :)

Now that we are on the subject of me beeing stupid (im realy new to all this) with my build in file editor I only got access to the yaml config files under /config , can you let me know where I can find the SSH addon's config file to manualy edit it ? (perhaps thru the SSH client itself ?)
Or do I have to make a new yaml configuration file to run at startup to overwrite the current SSH addon config file ?

Im kinda noobish so if you would have step by step instructions that would be awesome :)


Hans

**Comment by frenck** [comment]
![image](https://user-images.githubusercontent.com/195327/121783535-735b2300-cbaf-11eb-8cbb-281c365aab76.png)

**Comment by Hansie9999** [comment]
Oh snap :)

I was trying there, but I was leaving it just empty and not two quotes :)

Fixed now,

Thanks alot 👍
