### ISSUE TITLE
No Addon store in supervisor after fresh install of HASSOS on Proxmox 2021.06.0

### ISSUE THREAD

**Issue by Tokn59** [hassio-addons/addon-ssh#281]
# Problem/Motivation

> Installed (twice) the latest HASSOS using whiskerz007 metod on a NUC running proxmox. The add on store is not available and also I cannot add custom repositories such as the Google Drive addon.

Supervisor log : [supervisor.store] Loading add-ons from store: 0 all - 0 new - 0 remove 
No other RED supvisor log entries

## Expected behavior

> Store available in advanced mode

## Actual behavior

> store not available
## Steps to reproduce

> run whiskerz007 script on Poroxmox

## Proposed changes

> Correction/Fix/ Issue explanation ?
> Get it working again

**Comment by Blubbaz** [comment]
I had the same issue, but you need to enable the "Advanced Features". When you search for SSH, there is a hint about that, after activating the switch, I could find it in the latest version.

**Comment by Tokn59** [comment]
Unfortunately that didn't help for me. But I got it solved by doing some manual changes to DNS settings in Proxmox. Weird that overnight it changed to not working ...

**Comment by frenck** [comment]
Looking at this issue, this is not an add-on issue. Add-ons don't manage the store. Please report such issues with the Home Assistant project instead.

Thanks 👍
