### ISSUE TITLE
OTA Webserver wrong?! 

### ISSUE THREAD

**Issue by upwindanderl** [hassio-addons/addon-ssh#285]
# Problem/Motivation

If i wanna down-/upgrade the HA CORE i use `ha os update --version xx.yy`

## Expected behavior

It should work as always and the shell process should download the image

## Actual behavior

"No internet connection?" Connection refused by i don't know
MAYBE its a CORE Problem and not a addon story so first try with this issue.... pls close if i'm wrong here and sorry than

![grafik](https://user-images.githubusercontent.com/51791206/123412195-9de6ac00-d5b1-11eb-81b9-8a73cafb40a8.png)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
That is not an add-on issue, but an issue with the Supervisor / Home Assistant project. Please raise this issue upstream.

Thanks! 👍 

../Frenck
