### ISSUE TITLE
Algorithm negotiation failed

### ISSUE THREAD

**Issue by willsy555** [hassio-addons/addon-ssh#29]
# Problem/Motivation

> When connecting a terminal session with Putty on Windows or JuiceSSH on Android to the Hassio instance, connection fails with an error "Algorithm negotiation failed". The Hassio plugin works fine to connect to terminal.

## Expected behavior

> Connection works ok.

## Actual behavior

> Connection fails

## Steps to reproduce

> Connect using a terminal emulator other than that included with the plugin.

## Proposed changes

> ?

**Comment by frenck** [comment]
The add-on uses a more secure default setting. A lot of "apps" for mobiles don't support that. 

Set the `compatibility_mode` to `true` to enable the default OpenSSH security settings.

**Comment by willsy555** [comment]
Thank you frenck, that worked perfectly. And thanks for your awesome add-on!
