### ISSUE TITLE
ssh connection is refuse

### ISSUE THREAD

**Issue by JKWork3** [hassio-addons/addon-ssh#294]
# Problem/Motivation

> problem with ssh connection

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by JKWork3** [comment]
what i can do to fix it?

**Comment by frenck** [comment]
Please provide logs, installed version, system information and it also helps how you have configured the add-on (please remove secrets from it).

Without this information; it is impossible to help.
