### ISSUE TITLE
Persist .ssh folder (key pairs)

### ISSUE THREAD

**Issue by someinternetguy** [hassio-addons/addon-ssh#3]
## Problem/Motivation

> I use keys to authenticate my git pulls with gitlab.com and every time I have to reboot the host, my keys disappear. 

## Expected behavior

> rsa keypair in ~/.ssh will persist between reboots

## Actual behavior

> Every time the host restarts everything in ~/.ssh is wiped out

## Steps to reproduce

> simply create an rsa key pair and then reboot the host, and when you log back into ssh next time they will be gone

## Proposed changes

> Is there a way to make sure they persist through reboots? sorry, I'm not technical enough to suggest how it should be handled.  Just that it is a pain that the keys are not persistent.
If the entire ~/ directory can be made to be persistent, that would also solve the "known_hosts" file issue what was filed.

**Comment by frenck** [comment]
Thank you for this feedback.
I've added this to the roadmap for v2.0.0, which is currently in development.

**Comment by frenck** [comment]
The feature has been build and merged into the master branch.
Will be included in the next release (which will be v2.0.0).
