### ISSUE TITLE
More options for host access

### ISSUE THREAD

**Issue by colemickens** [hassio-addons/addon-ssh#314]
# Problem/Motivation

1. While it seems I can get the root fs and host net ns, I don't see options for plumbing in the ipc/pid ns.

## Expected behavior

1. The addon requests those permissions and then selectively uses them if the user is running in not Protected mode.

## Actual behavior

(this is a feature request, n/a)

## Proposed changes

Plumb through the config options.

(thanks for this and all of the other HA goodies!)

**Comment by colemickens** [comment]
Rationale:

if I have root fs access, all bets are off, might as well make it easy for (me) to run `htop` and see everything.

**Comment by frenck** [comment]
Addons can't do that.

**Comment by colemickens** [comment]
What is `host_pid` and `host_ipc` for here? https://developers.home-assistant.io/docs/add-ons/configuration/

**Comment by frenck** [comment]
Well sharing IPC or process space is not related to your request here. Sharing those is helpful for some rare cases (eg process/system monitoring in the glances add-on).

**Comment by colemickens** [comment]
Idk what you think my request was, I wrote:

> options for plumbing in the ipc/pid ns.

and like I said, I wanted to see everything in `htop` when I ssh'd in.

But anyway, sounds like you aren't interested, and I know what that means, thanks for considering.

**Comment by frenck** [comment]
Sharing our space has more consequences that I really don't want to provide with this addon. sorry.
