### ISSUE TITLE
Unable to use password from secrets.yaml

### ISSUE THREAD

**Issue by tcm0116** [hassio-addons/addon-ssh#318]
# Problem/Motivation

When configuring this add-on to use a password from secrets.yaml in the format "!secret my_password", that value is used instead of the value stored in secrets.yaml.

## Expected behavior

When the password is specified with the !secret keyword, the password from secrets.yaml should be used.

## Actual behavior

The literal string "!secret my_password" is used as the password.

## Steps to reproduce

Add my_password to secrets.yaml and then configure the add-on to use a password of: !secret my_password

## Proposed changes

Update the add-on to recognize the !secret keyword.

**Comment by tjorim** [comment]
Can you post your configuration here? Should just work.

**Comment by tcm0116** [comment]
When I edit the config in the UI and press save, I noticed that single quotes are added around the password, which is what I think is causing the issue. For example, if I type:

password: !secret my_password

When I press save, it changes to:

password: '!secret my_password'

**Comment by frenck** [comment]
The quotes are correct.

Additionally, secrets are handled by the Home Assistant Supervisor, not the add-on.
If you encounter issues with the use of them, please report the issue with the Home Assistant project. From an add-on perspective, there is not much we can do.

../Frenck
