### ISSUE TITLE
Broken Pipe

### ISSUE THREAD

**Issue by nitobuendia** [hassio-addons/addon-ssh#32]
# Problem/Motivation
SSH does not start.

Logs:
```
s6-maximumtime: warning: unable to wait for child process: Operation timed out
 v3.4.0 / armhf / Resin OS 2.3.0+rev1 / HA 0.76.0[cont-finish.d] 99-message.sh: exited 99.
[cont-finish.d] done.
[s6-finish] syncing disks.
/usr/lib/hassio-addons/modules/api.sh: line 118: echo: write error: Broken pipe
[s6-finish] sending all processes the TERM signal.
```

Message received when trying to connect using ssh: "Connection refused".

## Expected behavior
SSH should start.

## Actual behavior
Service never starts.
Also, if trying to connect; refused connection: "Connection refused".

Logs:
```
s6-maximumtime: warning: unable to wait for child process: Operation timed out
 v3.4.0 / armhf / Resin OS 2.3.0+rev1 / HA 0.76.0[cont-finish.d] 99-message.sh: exited 99.
[cont-finish.d] done.
[s6-finish] syncing disks.
/usr/lib/hassio-addons/modules/api.sh: line 118: echo: write error: Broken pipe
[s6-finish] sending all processes the TERM signal.
```

## Steps to reproduce
Go to interface > Hass.io > SSH & Web Terminal > click start.

For connection:  `ssh -p <port> hassio@<raspberry_ip>`
Although error seems to be on restarting.

# Other details
Using HassOs install on Raspberry Pi. Version: 0.76.0
Checked and there's available space in disk.
SSH & Web Terminal version: 3.4.0

**Comment by frenck** [comment]
Please provide the rest of the logs.
This is not useful.

**Comment by frenck** [comment]
@nitobuendia Not sure why the issue is closed.
I hope your problem is resolved 👍
