### ISSUE TITLE
"Terminal" UI not rendering properly on Safari (Mac OS)

### ISSUE THREAD

**Issue by nickdos** [hassio-addons/addon-ssh#320]
# Problem/Motivation

Apple recently did a major version number release of Safari on Mac OS (version 15.0) and since running that update I've not been able to use the Terminal/SSH UI in Home Assistant. The add-on appears to load as expected but **no text is rendered in the UI.** See screenshot below:

![image](https://user-images.githubusercontent.com/532845/135778192-1992b189-cbdc-4f17-b47f-85461e23acbd.png)

Using a different browser, the UI loads as expected, so I suspect Safari update is the issue. 

I [posted this in the HA forum](https://community.home-assistant.io/t/home-assistant-community-add-on-ssh-web-terminal/33820/400?u=nickdos) and another user has confirmed they see the same thing as me.

## Expected behavior

I expect to see the SSH UI renders with text, including the terminal prompt, etc.

## Actual behavior

I only see the coloured background and blue bar along the bottom, as well as a single white square that moves if I type or click the mouse (randomly). Screenshot included above.

Note: I checked for JS errors in the browser console and there were no errors or warning reported.

## Steps to reproduce

Run HA via Safari version 15.0 or later on Mac OS 11.6 or later

## Proposed changes

N/A

**Comment by mbspears** [comment]
Same on iOS app, all browsers on iOS, and Mac client app.

**Comment by Korte68** [comment]
> Same on iOS app, all browsers on iOS, iPad OS, and Mac client app.

All browser in Apple environment use the safari engine...
