### ISSUE TITLE
unable to use

### ISSUE THREAD

**Issue by martindinicolino** [hassio-addons/addon-ssh#322]
Hello,

thank you very much for creating this add-on.

I tried using it but even after reading through the documentation I have two issues and was wondering if anybody could help me out.

First of all once I open the web ui I can only see text after highlighting it with the cursor - not sure why that it, but it's actually no more than a minor annoyance and I can totally live with that.

Once I highlight the text all I can read is 502: Bad Gateway - I have checked but my HA username and password are right there.

Please excuse any dumb questions, I'm a newbie but I'm willing to learn. Any help would be highly appreciated.

**Comment by sorenfindsen** [comment]
I had issue with 502: bad gateway too and found reason in the logs.
In my case I got bad gateway because ssh password is in "Have I Been pwned database", which I could read in the logs.
After stopping addon, configuring new password and starting again it worked

**Comment by sorenfindsen** [comment]
> Hello,
> 
> thank you very much for creating this add-on.
> 
> I tried using it but even after reading through the documentation I have two issues and was wondering if anybody could help me out.
> 
> First of all once I open the web ui I can only see text after highlighting it with the cursor - not sure why that it, but it's actually no more than a minor annoyance and I can totally live with that.
> 
> Once I highlight the text all I can read is 502: Bad Gateway - I have checked but my HA username and password are right there.
> 
> Please excuse any dumb questions, I'm a newbie but I'm willing to learn. Any help would be highly appreciated.

I had issue with 502: bad gateway too and found reason in the logs.
In my case I got bad gateway because ssh password is in "Have I Been pwned database", which I could read in the logs.
After stopping addon, configuring new password and starting again it worked

**Comment by frenck** [comment]
Anything in the logs?
