### ISSUE TITLE
Can't run the add-on

### ISSUE THREAD

**Issue by Vinz87** [hassio-addons/addon-ssh#325]
# Problem/Motivation

After installing v9.0.1, when I hit the Run button I get this error:
`Image ghcr.io/hassio-addons/ssh/armv7 not exists for addon_a0d7b954_ssh`

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

Home Assistant OS 6.5
supervisor-2021.10.0
core-2021.10.6

installed on a Raspberry Pi 3 Model A+, from the HA OS v6.5 32 bit image.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by Vinz87** [comment]
more specifically, in the log I read this:
`2021-11-01 09:57:21 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/a0d7b954_ssh/start - Image ghcr.io/hassio-addons/ssh/armv7 not exists for addon_a0d7b954_ssh`

**Comment by alexandershalin** [comment]
Same here
