### ISSUE TITLE
After login prompt (username/password) the terminal continiously displays lines with dots.

### ISSUE THREAD

**Issue by prmfeddema** [hassio-addons/addon-ssh#326]
# Problem/Motivation
The issue renders the ssh login useless as the display is continiously showing dots and not allowing any inputs
> (Why the issue was filed)

## Expected behavior
unix shell
> (What you expected to happen)

## Actual behavior
lines with dots are shown causing the screen to fill up and not allowing any input
> (What actually happened)

## Steps to reproduce
just login onto ssh on my HA instance (generic x86 system)
> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
I'm not sure about your description, could you add a screenshot or recording to make it more clear?

**Comment by prmfeddema** [comment]
Frank,

Completely forgot about this. Reinstalling the add-on solved it. It now works fine.

Again: apologies.

Kr,

Pascal

Verstuurd vanaf mijn iPhone

**Comment by frenck** [comment]
Glad is has been solved 👍
