### ISSUE TITLE
Removing Ctrl-A prefix switch.

### ISSUE THREAD

**Issue by bmorgenthaler** [hassio-addons/addon-ssh#341]
# Problem/Motivation

I use Ctrl-B as the prefix on all of my systems with tmux, after every update I have to edit the .tmux.conf to remove the switch from Ctrl-B to Ctrl-A.  How can I override this by default?

**Comment by sinclairpaul** [comment]
The addon has an init_commands option, you should be able to utilise that and perform a string replace.

https://github.com/hassio-addons/addon-ssh/blob/main/ssh/DOCS.md#option-init_commands
