### ISSUE TITLE
502: Bad Gateway

### ISSUE THREAD

**Issue by purcell-lab** [hassio-addons/addon-ssh#342]
# Problem/Motivation

SSH & Web terminal will not start for me.

![image](https://user-images.githubusercontent.com/79175134/142379096-43042387-b092-4c01-89a6-765dbaf81a72.png)

## Expected behavior

'Terminal & SSH addon works fine:

![image](https://user-images.githubusercontent.com/79175134/142379227-afbca196-2209-4b48-a26b-f2ac0702c18d.png)

![image](https://user-images.githubusercontent.com/79175134/142379399-6e9fdf26-34cc-4294-85a5-a664bfd33fe0.png)

## Actual behavior

When I try to start I get a 502: Bad Gateway error.

![image](https://user-images.githubusercontent.com/79175134/142379038-f7354761-b88a-4ced-8a31-5e448c737436.png)

## Steps to reproduce

Start button on two different HA instances reports the same issue:

![image](https://user-images.githubusercontent.com/79175134/142379645-296a8728-8507-4d52-a561-00492e58d212.png)

## Proposed changes

I suspect a component somewhere is missing.

As a workaround I am using the 'Terminal & SSH' addon

**Comment by frenck** [comment]
Anything in the logs?

**Comment by purcell-lab** [comment]
Sorry,

should of included that detail:

Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:109
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 7:23:45 PM (1 occurrences)
Last logged: 7:23:45 PM

Failed to to call /addons/a0d7b954_ssh/stats - Container addon_a0d7b954_ssh
is not running

**Comment by frenck** [comment]
In the add-on logs...

![image](https://user-images.githubusercontent.com/195327/142404940-10206a25-1a87-4f46-8faf-add72784bd1d.png)

**Comment by purcell-lab** [comment]
Here is the add-on logs:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] permissions: applying... 
[fix-attrs.d] permissions: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: SSH & Web Terminal
 SSH & Web Terminal access to your Home Assistant instance
-----------------------------------------------------------
 Add-on version: 9.1.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 6.6  (aarch64 / odroid-n2)
 Home Assistant Core: 2021.11.4
 Home Assistant Supervisor: 2021.10.8
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] docker.sh: executing... 
[cont-init.d] docker.sh: exited 0.
[cont-init.d] mosquitto.sh: executing... 
[cont-init.d] mosquitto.sh: exited 0.
[cont-init.d] mysql.sh: executing... 
[cont-init.d] mysql.sh: exited 0.
[cont-init.d] ssh.sh: executing... 
[22:08:29] FATAL: 
[22:08:29] FATAL: Configuration of this add-on is incomplete.
[22:08:29] FATAL: 
[22:08:29] FATAL: Please be sure to set a least a SSH password
[22:08:29] FATAL: or at least one authorized key!
[22:08:29] FATAL: 
[22:08:29] FATAL: You can configure this using the "ssh.password"
[22:08:29] FATAL: or the "ssh.authorized_keys" option in the
[22:08:29] FATAL: add-on configuration.
[22:08:29] FATAL: 
[cont-init.d] ssh.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by sinclairpaul** [comment]
The log shows the issue, either set a password or SSH key.

For reference the documentation is at https://github.com/hassio-addons/addon-ssh/blob/main/ssh/DOCS.md or on the documentation tab within the addon.

**Comment by purcell-lab** [comment]
This is a usability issue then, can you please reopen so we can discuss.

'Terminal & SSH' addon works out of the box without configuration and presents a root shell.
'SSH & Web Terminal' requires configuration file inclusions.

How is a new HA Blue user able to set a password/ SSH Keys with their first access to the HA CLI?
Are you suggesting they need to login via keyboard/ monitor to set passwords before they can use 'SSH & Web Terminal'?

Also a better error message than '502: Bad Gateway' could also help new users trying to use the addon for the first time.

Happy to assist with development of better documentation about how a first time user accesses the CLI using 'SSH & Web Terminal'

**Comment by frenck** [comment]
> This is a usability issue then, can you please reopen so we can discuss.

I don't agree on that, sorry.

> How is a new HA Blue user able to set a password/ SSH Keys with their first access to the HA CLI?

By reading the documentation.

![image](https://user-images.githubusercontent.com/195327/142512178-800e4e76-1cf8-415a-a8d3-72e625d3c560.png)

> Also a better error message than '502: Bad Gateway' could also help new users trying to use the addon for the first time.

That is not the add-ons domain and cannot be influenced by an add-on. That is a message by Home Assistant.
