### ISSUE TITLE
Ban / block IP addresses after several successless connection attempts

### ISSUE THREAD

**Issue by alve89** [hassio-addons/addon-ssh#345]
# Problem/Motivation

Right after starting the add-on, I'm getting protocol entries that two IP' are trying to connect to my Home Assistant (several times!):
```
Connection from 64.227.99.30 port 44250 on 192.168.1.2 port 22 rdomain ""
Unable to negotiate with 64.227.99.30 port 44250: no matching key exchange method found. Their offer: diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1 [preauth]
Connection from 2.56.59.114 port 56708 on 192.168.1.2 port 22 rdomain ""
Unable to negotiate with 2.56.59.114 port 56708: no matching key exchange method found. Their offer: diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1 [preauth]
```
I'm forwarding the public port 22 to my Home Assistant.

Is there a way to **automatically** ban / block such IP-addresses after they failed to connect to the SSH server for lets say 5 times?
1. on SSH server side (HA)
2. in my router

**Comment by frenck** [comment]
This is not really an issue report for the add-on, but more a support question... so why create an issue?

Nevertheless, no, the add-on does not provide such functionality.
