### ISSUE TITLE
System CPU Usage

### ISSUE THREAD

**Issue by tescophil** [hassio-addons/addon-ssh#360]
# Problem/Motivation

CPU Load average changed from 0.5 to 1.5 after the update to 10.0.1

## Expected behaviour

I expect this to have no impact on CPU usage

## Actual behavior

The Add-on information page within HA shows the 'Add-on CPU Usage' at a constant 25-26%, and 'Add-on RAM Usage' at 0.6%.

Logs:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] permissions: applying... 
[fix-attrs.d] permissions: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: SSH & Web Terminal
 SSH & Web Terminal access to your Home Assistant instance
-----------------------------------------------------------
 Add-on version: 10.0.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 7.1  (aarch64 / raspberrypi3-64)
 Home Assistant Core: 2021.12.8
 Home Assistant Supervisor: 2021.12.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] docker.sh: executing... 
```

## Steps to reproduce

Just upgrade to 10.0.1

## Proposed changes

I have tried rebooting the Add-on and the entire HA system, but this has no impact on the persistent CPU usage

**Comment by frenck** [comment]
Which process is causing that for you?

**Comment by tescophil** [comment]
No idea, as I'm running supervised Home Assistant OS which obfuscates all useful information/data from the user...

**Comment by frenck** [comment]
> No idea, as I'm running supervised Home Assistant OS which obfuscates all useful information/data from the user...

? So that is not true and incorrect. Just run `top` inside the add-on and see what is going on.

**Comment by tescophil** [comment]
Apologies if that's the case, but if there is a guide on how to do this, then it's well hidden.  I am able to do very little from the SSH command prompt, and cannot find anything in the HA documentation that explains how to access parts of the subsystem/add-ons.

**Comment by frenck** [comment]
Please run `top` in the terminal or SSH prompt so we can identify this issue.

Any other discussion about the capabilities of the platform or how to general manage other things, it not really relevant to this issue.

**Comment by tescophil** [comment]
So here is a screenshot to htop.., as you can see, there is no CPU activity, however, the load average is 1.4. If I stop the addon running, the load drops to 0.6.

![image](https://user-images.githubusercontent.com/59442445/148770345-4062c623-98a9-4996-946d-cc6c05254750.png)

**Comment by frenck** [comment]
![image](https://user-images.githubusercontent.com/195327/148770683-fe819f4a-d092-4a75-943e-b8201f06843e.png)

In that case, the issue is not the add-on, as there is no process in the container consuming your CPU.

**Comment by frenck** [comment]
Please note, you are using quite a bit of swap. So you are hitting machine limits.

**Comment by tescophil** [comment]
Understood, and like I said, no useful information. I'm also not hitting the machine limits, I'm hitting the inadequate swap file limits which is there is no way to increase (searching for this issue on the forums, the consensus is that 1--% swap usage is 'normal' for Home Assistant OS)

**Comment by frenck** [comment]
> Understood, and like I said, no useful information.

? I'm not sure what you base that on. The information is useful, as it shows this is not an add-on issue (for which you filed an issue against).

Therefore this issue has been resolved and can be closed.

**Comment by tescophil** [comment]
Not exactly, its an issue with the addon that is not understood.., turn it on and CPU load doubles, turn it off and it halves, that's the issue I raised, which is still there, by all means close the issue, but is is not 'resolved'

**Comment by tescophil** [comment]
And in there lies the rub, are you able to suggest where it does belong ?

**Comment by frenck** [comment]
I dunno, as I don't know your system. We've just eliminated the add-on from the root cause as you provided information on that. From the add-on perspective, this is an invalid issue.

**Comment by tescophil** [comment]
QED
