### ISSUE TITLE
SSH connection - PUTTY

### ISSUE THREAD

**Issue by thunderj27** [hassio-addons/addon-ssh#361]
# Problem/Motivation

Hi,

I open this issue to report that ssh connection using PUTTY does not seem to work anymore since the last update (10.0).

## Expected behavior

With the same private key: Impossible to establish a connection whereas it is ok with a standard SSH (Terminal - Linux).

## Actual behavior

PUTTY gives the errors : "Server refused our key" & "No supported authentification methods availalble (server  sent: publickey)".

## Steps to reproduce

Open a ssh connection by using PUTTY and your private key.

## Proposed changes

N/A

**Comment by sinclairpaul** [comment]
Please see #354 the issue is the same.

**Comment by thunderj27** [comment]
@sinclairpaul : Thanks for your help. I missed this issue, my bad.
