### ISSUE TITLE
How to save crontab changes for reboot ?

### ISSUE THREAD

**Issue by michapr** [hassio-addons/addon-ssh#364]
# Problem/Motivation

- After reboot the crontab script was deleted
- After reboot the custom crontab (10 minutes) was removed

## Expected behavior

- settings should be safe

## Actual behavior

- custom settings deleted

## Steps to reproduce

add any script and/or modify crontab (using crontab -e) and reboot.

## Proposed changes
-?

----------------------------------------------------------

Is there any way to make these changes permanent, so that will not be deleted after reboot?

Thanks!

**Comment by frenck** [comment]
> Is there any way to make these changes permanent, so that will not be deleted after reboot?

There is no possibility for that. In general, this is an add-on for Home Assistant... most use Home Assistant to schedule things 😉

**Comment by michapr** [comment]
> In general, this is an add-on for Home Assistant... most use Home Assistant to schedule things

Yes, right, I wanted to add some system cron jobs.
But for what kind of tasks it can be used? Or is it useless, better forget about the crond here ?
