### ISSUE TITLE
not able to access the ssh terminal

### ISSUE THREAD

**Issue by weemaba999** [hassio-addons/addon-ssh#365]
# Problem/Motivation

not running

## Expected behavior

running

## Actual behavior

error when trying to open in homeassistant : 502: bad gateway

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Anything in the logs?

**Comment by voltage84** [comment]
Hi,

same issue here. The log says: [19:16:55] WARNING: SSH port is disabled. Prevent start of SSH server. 

I have no idea how to enable the port.

**Comment by voltage84** [comment]
For me it helped to configure username and password, and after that in the "Configuration" tab, in the "Network" section I just typed 22 and restarted the service.

**Comment by calisro** [comment]
I'm seeing this as well.  It is intermittant though. If I keep clicking the terminal side bar it shows the terminal and says '502: bad gateway' randomly. I have the password set and the network tab set as @voltage84 mentioned.

**Comment by frenck** [comment]
> For me it helped to configure username and password, and after that in the "Configuration"

So, you mean as written in the documentation?

<https://github.com/hassio-addons/addon-ssh/blob/main/ssh/DOCS.md#installation>

![image](https://user-images.githubusercontent.com/195327/152060145-30a628e5-bb1d-4615-b5b6-339299e78147.png)

**Comment by frenck** [comment]
> If I open chrome dev tools, you can see the connections not going through. Almost seems like there can be one connection at a time open and it gets blocked on the refresh.

That sounds like a different issue (although unknown at this point).

**Comment by calisro** [comment]
I don't know if this helps debug where its happening but....  If the current session is exited (type exit) before clicking on the terminal again, the connection works fine every time the next.

**Comment by anatoliykant** [comment]
@weemaba999 
Try changing port **22** to **622** in the Network section at the bottom of the Configuration tab.
It helped me.

**Comment by calisro** [comment]
@weemaba999  Tried changing the port but that doesn't address the behavior.
