### ISSUE TITLE
About /etc/hosts can't save

### ISSUE THREAD

**Issue by hanzch** [hassio-addons/addon-ssh#369]
# problem/motivation

> I tried to modify the /etc/hosts file to make DNS resolution take effect but found that the Add-on disappeared after restarting

>Oracle VM VirtualBox
>HAOS:  7.2
>Protected mode : false

## Expected behavior

> Saved previous changes

## Actual behavior

> disappeared

## steps to reproduce

> vim /etc/hosts
140.82.113.4    GitHub.com
:wq

## Proposed changes

> (If you have suggested changes, workarounds or fixes,
> describe the rationale behind it)

**Comment by frenck** [comment]
That is correct, in the add-on world, only the `/data` folder is persistent.
