### ISSUE TITLE
Cant use on a mobile device like android

### ISSUE THREAD

**Issue by calisro** [hassio-addons/addon-ssh#371]
# Problem/Motivation

When attempting to use on android, I believe the autosuggestions cause the misery.  Unfortunately, modifying the .zshrc doesn't persist and I am not sure how to address.  

## Expected behavior

usable on a mobile device like android.

## Actual behavior

when typing a command that has a suggestion and then back spacing, it will add the entire command and end up garbled.

## Steps to reproduce

Should be very obvious when opened on an android device.

## Proposed changes

There may already be a way to do this, but it would be helpful to either disable the zsh autosuggestions or whatever is causing it and be able to configure the addon to allow for options to enable or disable certain items like this.

**Comment by frenck** [comment]
I have no interest in supporting mobile devices for a tool like this.

I'm happy to accept PRs that improve the situation (as long as the intended use case remains intact).

**Comment by calisro** [comment]
Fair enough.  For others who would like to use it on a mobile. setting "zsh: false" in the configuration would default to bash instead.  Seems to work fine.
