### ISSUE TITLE
Access denied with correct password

### ISSUE THREAD

**Issue by sillvva** [hassio-addons/addon-ssh#376]
# Problem/Motivation

I was able to reach the SSH terminal from PuTTY, but when I entered my username and password, it says "Access denied." I know for a fact, that I entered the correct password. I even tried multiple times and even tried changing the configured password.

## Expected behavior

It should let me sign in.

## Actual behavior

It says "Access denied".

## Steps to reproduce

1. Install add-on.
2. Configure username and password.
3. Turn on all options and start add-on.
4. Access HA IP in PuTTY
5. Enter username and password.

**Comment by frenck** [comment]
Try lowercasing your username

**Comment by sillvva** [comment]
That was it. I had to use lowercase in PuTTY. Thanks!
