### ISSUE TITLE
ssh-rsa not in PubkeyAcceptedAlgorithms

### ISSUE THREAD

**Issue by Wubarius** [hassio-addons/addon-ssh#379]
# Problem/Motivation

> putty ssh access no longer possible, I switched from version 9.1.1 to 10.0.2 yesterday

## Expected behavior

> ssh access with my valid ssh-rsa key

## Actual behavior

> userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]

## Steps to reproduce

> ----

## Proposed changes
Add-on version: 10.0.2
You are running the latest version of this add-on.
System: Home Assistant OS 7.4  (amd64 / qemux86-64)
Home Assistant Core: 2022.2.9
Home Assistant Supervisor: 2022.01.1

sshd -T|egrep "pubkeyauthentication|pubkeyacceptedkeytypes"
pubkeyauthentication yes
no "pubkeyacceptedkeytypes" types listed

**Comment by frenck** [comment]
This is not caused by the add-on, but by the newer version of OpenSSH.

> This release disables RSA signatures using the SHA-1 hash algorithm
by default. This change has been made as the SHA-1 hash algorithm is
cryptographically broken, and it is possible to create chosen-prefix
hash collisions for <USD$50K [1]

<https://www.openssh.com/txt/release-8.8>
