### ISSUE TITLE
Can we configure font size used by the terminal?

### ISSUE THREAD

**Issue by skotekar** [hassio-addons/addon-ssh#380]
# Problem/Motivation
> Fonts are not rendered correctly at certain resolution when rendered in the browser. I use this on my 2K monitor and the text is garbled beyond recognition.

## Expected behavior

> Text is readable and legible

## Actual behavior

> Text is garbled and not legible at all
![image](https://user-images.githubusercontent.com/628453/155581622-b58780f4-6cf4-41bd-83e9-40435aa85fd5.png)

## Steps to reproduce

> This happens to be on my 2K (1440p) monitor with display scaling set to 125% in windows. Using microsoft edge browser.

## Proposed changes

> If the zoom level of the browser is increased, at certain zoom level the text becomes legible again. Leads me to think that if there is an option to control the font size used by the terminal, users can increase it to work on their device.
> This should also help with accessibility?

**Comment by PDXUser** [comment]
This  only happens with Firefox, using Chrome based browsers do not present this issue at least on my machine which is using Arch Linux.

**Comment by skotekar** [comment]
Right, it works fine on google chrome. I have this issue on Edge browser on windows 10

**Comment by VDRainer** [comment]
I see this in firefox too.
