### ISSUE TITLE
Does not start on Odroid C2

### ISSUE THREAD

**Issue by kreisklasse** [hassio-addons/addon-ssh#40]
# Problem/Motivation

> After install add-on does not start up on 
>**Odroid C2**
>**HassOS 2.2 / Deployment | development / Supervisior V135**

## Expected behavior

> normal start

## Actual behavior

> After pressing START button, it tries to startup for 2-3 seconds, then button returns to START
no log is written in the add-on.

>but system log shows:

>18-10-10 09:02:09 INFO (MainThread) [hassio.misc.hardware] No audio devices found
18-10-10 09:02:09 INFO (MainThread) [hassio.misc.hardware] No audio devices found
18-10-10 09:02:09 INFO (MainThread) [hassio.misc.hardware] No audio devices found
18-10-10 09:02:09 INFO (MainThread) [hassio.misc.hardware] No audio devices found
18-10-10 09:02:10 INFO (MainThread) [hassio.misc.hardware] No audio devices found
18-10-10 09:02:10 INFO (MainThread) [hassio.misc.hardware] No audio devices found
18-10-10 09:02:09 INFO (MainThread) [hassio.misc.hardware] No audio devices found  
18-10-10 09:02:15 INFO (MainThread) [hassio.misc.hardware] No audio devices found
18-10-10 09:02:15 INFO (SyncWorker_15) [hassio.docker.interface] Clean hassioaddons/ssh-aarch64 Docker application
18-10-10 09:02:15 INFO (SyncWorker_15) [hassio.misc.hardware] No audio devices found
18-10-10 09:02:15 INFO (SyncWorker_15) [hassio.misc.hardware] No audio devices found
18-10-10 09:02:15 INFO (SyncWorker_15) [hassio.misc.hardware] No audio devices found
18-10-10 09:02:15 INFO (SyncWorker_15) [hassio.misc.hardware] No audio devices found
18-10-10 09:02:15 ERROR (SyncWorker_15) [hassio.docker] Can't start addon_a0d7b954_ssh: 500 Server Error: Internal Server Error ("linux runtime spec devices: error gathering device information while adding custom device "/dev/snd": no such file or directory")
18-10-10 09:02:15 INFO (MainThread) [hassio.misc.hardware] No audio devices found
18-10-10 09:02:15 INFO (MainThread) [hassio.misc.hardware] No audio devices found
18-10-10 09:02:15 INFO (MainThread) [hassio.misc.hardware] No audio devices found
18-10-10 09:02:15 INFO (MainThread) [hassio.misc.hardware] No audio devices found

## Steps to reproduce

>NIL

## Proposed changes

> NIL

**Comment by frenck** [comment]
This is an error with Hass.io.
Please create an issue at https://github.com/home-assistant/hassio
