### ISSUE TITLE
Failure to upgrade to 9.5.0

### ISSUE THREAD

**Issue by Beylie** [hassio-addons/addon-ssh#419]
# Problem/Motivation
There is an update available to version 9.5.0 of Terminal & SSH. When I click update, it fails with "[547690012000] Error updating Terminal & SSH: Can't install homeassistant/aarch64-addon-ssh:9.5.0: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=9.5.0&fromImage=homeassistant%2Faarch64-addon-ssh&platform=linux%2Farm64: Not Found ("manifest for homeassistant/aarch64-addon-ssh:9.5.0 not found: manifest unknown: manifest unknown")" I've tried restarting HA, but I get the same.

Also if Start On Boot is set after attempting the upgrade, it cannot start and the logs show:
 Failed to to call /store - and /store return code 500

> (Why the issue was filed)
I wanted to upgrade to the latest version when it became available.

## Expected behavior

I expected the upgrade to be successful.

## Actual behavior

There is an update available to version 9.5.0 of Terminal & SSH. When I click update, it fails with "[547690012000] Error updating Terminal & SSH: Can't install homeassistant/aarch64-addon-ssh:9.5.0: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=9.5.0&fromImage=homeassistant%2Faarch64-addon-ssh&platform=linux%2Farm64: Not Found ("manifest for homeassistant/aarch64-addon-ssh:9.5.0 not found: manifest unknown: manifest unknown")" 

## Steps to reproduce

Try to upgrade to 9.5.0 of the add-on.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Wrong repository. This is the issue tracker of the community SSH add-on. Your issue is about the official SSH add-on.

You can find more people experiencing your issue for that add-on here: <https://github.com/home-assistant/addons/issues/2577>

**Comment by Beylie** [comment]
Apologies, frenck. And thank you for pointing me in the right direction.

**Comment by frenck** [comment]
Don't worry! No problem 👍
