### ISSUE TITLE
Font/display distorted

### ISSUE THREAD

**Issue by theFork** [hassio-addons/addon-ssh#424]
# Problem/Motivation
I can't read the terminal in the webview, it looks like that:
![image](https://user-images.githubusercontent.com/3392579/179922951-1d05ec06-ef70-4f90-974c-73afa8e41631.png)

## Steps to reproduce
For me, this occurs, independent of the browser (firefox, brave), OS (debian, manjaro, win10) and screen resolution.

Addon-Versions 9.0.1, 10.0.2, 11.0.2, 12.0.0
Home Assistant 2022.7.4, 2022.8.1
Supervisor 2022.07.0
Operating System 8.2, 8.4
Frontend 20220707.0, 20220802.0

**Comment by theFork** [comment]
I just restored some older addon version (see above) to test if they are affected. They are, but I'm sure that there have been versions without the issue in the past. Most likely in the time before HA offered to backup before updating an addon.

**Comment by Cartache** [comment]
Hi,

what browser are you using?

I think this has nothing to do withe the add-on.

**Comment by theFork** [comment]
I can reproduce the issue with both Firefox and Brave.

**Comment by Cartache** [comment]
Did you try disabling or reducing fingerprinting in the privacy settings?

**Comment by theFork** [comment]
This solves it, thanks for the hint! IMO, we should add a short note on this in the Readme. Maybe sth like that?

---

### Known Issues
* If the terminal font looks distorted or is not readable, try disabling or reducing fingerprinting in the privacy settings of you browser.

---

Or would it be possible to detect and circumvent the issue by using a font already installed? If this is doable, I would prefer this approach.

**Comment by disconn3ct** [comment]
As a specific example, the duckduckgo privacy essentials plugin was the culprit here. (FFX set to strict, ghostery on fairly vigorous, etc etc is fine once DDG is disabled.)
