### ISSUE TITLE
rsa is not accepted anymore by the addon, remove from example and please add to documentation

### ISSUE THREAD

**Issue by The-Fons** [hassio-addons/addon-ssh#426]
# Problem/Motivation

> Connection with previously used RSA 4096 SHA256 failed. DOC.md suggests it should work.

## Expected behavior

> A working ssh connection and docs to help me achieve that.

## Actual behavior

> No connection with a RSA 4096 SHA256 key. DOC.md suggests it as an configuration.

## Steps to reproduce

> Try a RSA 4096 SHA256 key, no connection,  create a "ecdsa" key and connection succeeds.

## Proposed changes

> Please update update the example and also the docs to reflect what is accepted or not accepted. 
> Some ssh sites still contain examples of ssh-rsa, the community support page has some entries of users trying to find the right key type, would be nice if the homeassistant docs show you to do it right the first time.
> And many thanks for this addon. :-)

**Comment by jsahoka** [comment]
I ran in to the same issue. 
Kept getting "userauth_pubkey: signature algorithm ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]" with my RSA key.
ECDSA does work.

**Comment by frenck** [comment]
> DOC.md suggests it as an configuration.

Works fine on my end...

I think you are misunderstanding how SSH works.

From the OpenSSH release notes:

```
Potentially-incompatible changes
================================

This release disables RSA signatures using the SHA-1 hash algorithm
by default. This change has been made as the SHA-1 hash algorithm is
cryptographically broken, and it is possible to create chosen-prefix
hash collisions for <USD$50K [1]

For most users, this change should be invisible and there is
no need to replace ssh-rsa keys. OpenSSH has supported [RFC8332](https://tools.ietf.org/html/rfc8332)
RSA/SHA-256/512 signatures since release 7.2 and existing ssh-rsa keys
will automatically use the stronger algorithm where possible.
```

You are assuming all RSA isn't considered safe anymore and not working; that however, isn't true.

See my SSH config for my machines:

![image](https://user-images.githubusercontent.com/195327/185757988-f8a8135e-5b5a-4dfc-aaa1-64dfb6c5fbf9.png)

Use rsa4096 GPG keys in my case (stored on a hardware token):

![CleanShot 2022-08-20 at 18 55 02](https://user-images.githubusercontent.com/195327/185758129-87d99726-89af-410f-b97d-368b87c9509e.png)

The documentation is, at this point, thus correct.

../Frenck

**Comment by The-Fons** [comment]
Agree, thanks for providing a succesful case. Back to the testlab.
