### ISSUE TITLE
Feature Request: add possibility to call scripts from within home assistant automations and scripts

### ISSUE THREAD

**Issue by quarcko** [hassio-addons/addon-ssh#43]
# Problem/Motivation
I am running home assistant in default hass.io environment.
Generally i'm happy with this docker-container setup for the most part.
But recently i hit a brick wall with such simple things that needs to be done...

Thing 1)
I have and UPS, and i can monitor it's state.
I can make an automation that triggers when UPS battery goes down to (lets say) 10%.
After hitting this i want to issue a command 'hassio host shutdown';
i can do it via SSH addon... but i cannot do it inside a automation....

Thing 2)
My whole setup runs on 4G router. Some times (once a week or so)
My 4G just breaks and i need to restart the router, so...
i can add a 'ping' sensor to home assistant, to ping some known host.
i can add an automation that checks if ping was OK...
but i cannot issue a command like:
'ssh root@router.local 'reboot''; (but i can do it via SSH plugin itself...)

> (Why the issue was filed)
Just thinking for expanding functionality, as these features seem
so obvious and useful to anybody, who
1) want to protect their setup from data corruption on power outage
2) want to restart their router without "calling wife to go and power-cycle router, damn we are talking about a AUTOMATIC home system........"

## Expected behavior
These things to work...
> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes
Maybe there is possibility to create a home assitant component
that can interact with SSH addon?
For example:

1) create some scripts in predefined directory of SSH container (that's already possible)
2) have a component that can be configured via 'configuration.yaml':
ssh_component:
  command1:
  - path: /config/restart_router.sh
  command2:
  - path: /config/shutdown_hassio.sh

and then just use service: ssh_component.command1 in automation!!! :)

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Hi there, that is not something an add-on can provide.
A proper way to solve this / do this is to execute commands over SSH.
