### ISSUE TITLE
SSH & Web Terminal: no time in logs in UI

### ISSUE THREAD

**Issue by Masterz69** [hassio-addons/addon-ssh#433]
# Problem/Motivation

Hard to troubleshoot failed login attempts f.e., as soon Add-on log in UI have no time for records.

## Expected behavior

To see human-raedable timestamp for records.

## Actual behavior

```
Connection from 192.168.1.250 port 25699 on 192.168.1.11 port 22 rdomain ""
Accepted password for hass from 192.168.1.250 port 25699 ssh2
User child is on pid 435
Starting session: shell on pts/0 for hass from 192.168.1.250 port 25699 id 0
```
But don't ses when it hapened.

## Steps to reproduce

Just install Add-on.

## Proposed changes

Put human-raedable timestamp for records.

**Comment by frenck** [comment]
> Connection from 192.168.1.250 port 25699 on 192.168.1.11 port 22 rdomain ""
> Accepted password for hass from 192.168.1.250 port 25699 ssh2
> User child is on pid 435
> Starting session: shell on pts/0 for hass from 192.168.1.250 port 25699 id 0

That is the raw output from the OpenSSH deamon, there is not much I can do about that from an add-on perspective.

**Comment by frenck** [comment]
Closing this as per above.
