### ISSUE TITLE
init_commands doesn't work

### ISSUE THREAD

**Issue by llhotka** [hassio-addons/addon-ssh#441]
I tried the `init_commands` option with this configuration:
```
init_commands:
  - ls -la
```
It doesn't do anything. Upon a closer inspection, it seems that the script `/etc/cont-init.d/user.sh` isn't executed at all.

My versions are:
- Home Assistant OS 9.0
- HA Core 2022.9.4
- SSH & Web Terminal 12.0.2

**Comment by tjorim** [comment]
Not sure what makes you say that, I have custom commands and it works just fine.
`cont-init: info: running /etc/cont-init.d/user.sh`
Please submit your logs.

**Comment by llhotka** [comment]
Hmm, I see this in the log:
```
...
cont-init: info: running /etc/cont-init.d/user.sh
[18:02:11] NOTICE: Session sharing has been disabled!
total 28
drwxr-xr-x    5 root     root          4096 Sep 16 18:02 .
drwxr-xr-x    4 root     root          4096 Sep 16 18:02 ..
drwxr-xr-x    3 root     root          4096 Sep 16 18:02 data
drwx-ws--T    2 root     root          4096 Sep 16 18:02 event
-rw-r--r--    1 root     root             2 Sep 16 18:02 notification-fd
-rwxr-xr-x    1 root     root           419 Sep 16 18:02 run
srwxrwxrwx    1 root     root             0 Sep 16 18:02 s
-rw-------    1 root     root             0 Sep 16 18:02 s.lock
drwx------    2 root     root          4096 Sep 16 18:02 supervise
cont-init: info: /etc/cont-init.d/user.sh exited 0
...
```
It looks like the output of `ls -la` goes to the log. Is it how it is supposed to work? I expected to see the output in the terminal window after logging in.

[Sorry, I am new to HA.]
