### ISSUE TITLE
Sending a command to NUT for my ups

### ISSUE THREAD

**Issue by cartman-sp69** [hassio-addons/addon-ssh#444]
# Problem/Motivation

Unable to get my automation to work to send commands to NUT addon for my ups.
i use to use the following 

action:
  - service: hassio.addon_stdin
    data:
      addon: a0d7b954_ssh
      input: sh /config/boff.sh

and the command in the script was 
docker exec addon_a0d7b954_nut upscmd -u xxx -p xxx Cabinet_UPS@localhost beeper.toggle

Worked flawlessly until the hassio.addon_stdin was removed from the addon.
i'm not well versed in SSH so since then i have not been able to find a solution other than running the command manually on the terminal.

I hope there is someone who can assist me as getting no joy on homeassistant's discord server.

## Expected behavior

Send a command to disable beeper on my ups 

## Actual behavior

Nothing happens when using the past configuration.

## Steps to reproduce

action:
  - service: hassio.addon_stdin
    data:
      addon: a0d7b954_ssh
      input: sh /config/boff.sh

## Proposed changes

Don't have any or bring back hassio.addon_stdin support or make it an option in the config for people to accept the risk and decide for themself if they are willing to accept the apparent security risk

**Comment by frenck** [comment]
Use the `ssh` command from the Home Assistant container to executes remote commands over SSH.
This is a standard SSH feature, that has always been available.

**Comment by cartman-sp69** [comment]
Wow thanks for the quick response, my issue is i have no idea how to use that

**Comment by frenck** [comment]
Sorry to hear that, the `ssh` command is extensively documented and tons of information is provided about it on the internet in general. It is one of the most commonly used commands in the world.
