### ISSUE TITLE
Failed To Start

### ISSUE THREAD

**Issue by bobmoran00** [hassio-addons/addon-ssh#447]
Image ghcr.io/hassio-addons/ssh/aarch64:12.0.2 does not exist for addon_a0d7b954_ssh

> 2022.6.6
Rebooted and reinstalled no change

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
> Image ghcr.io/hassio-addons/ssh/aarch64:12.0.2 does not exist for addon_a0d7b954_ssh

This is often caused by corruption that is not in control/caused by the addon. There is a repair tool for it, run the following command from a terminal:

`ha supervisor repair`

../Frenck
