### ISSUE TITLE
I want to disable pwned in initialization. What  I do.

### ISSUE THREAD

**Issue by educastellini** [hassio-addons/addon-ssh#45]
I want to use the this add-on and others with a same user name and password I use in the all add-ons I have.

What I do to disable pwned check in the initializing off add-ons.

I try use the option in the end of config but dont works, and the add-on initialization stops.

My config:

{
  "log_level": "info",
  "ssh": {
    "enable": true,
    "port": 22,
    "username": "root",
    "password": "xxxxxxxxx",
    "authorized_keys": [],
    "sftp": true,
    "compatibility_mode": false,
    "allow_agent_forwarding": false,
    "allow_remote_port_forwarding": false,
    "allow_tcp_forwarding": false
  },
  "web": {
    "enable": true,
    "port": 7681,
    "username": "xxxxxxx",
    "password": "xxxxxxxxx",
    "ssl": false,
    "certfile": "fullchain.pem",
    "keyfile": "privkey.pem"
  },
  "share_sessions": true,
  "packages": [
    "python",
    "python-dev",
    "py-pip",
    "build-base"
  ],
  "init_commands": [
    "pip install virtualenv",
    "pip install yamllint"
  ],
  "leave_front_door_open": true,
  "i_like_to_be_pwned": false
}

The initialization PWNED error:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 10-hassio: applying... 
[fix-attrs.d] 10-hassio: exited 0.
[fix-attrs.d] 50-ssh: applying... 
[fix-attrs.d] 50-ssh: exited 0.
[fix-attrs.d] 51-sudoers: applying... 
[fix-attrs.d] 51-sudoers: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: SSH & Web Terminal v3.5.1
 SSH & Web Terminal access to your Home Assistant instance
 From: Community Hass.io Add-ons
 By: Franck Nijhof <frenck@addons.community>
-----------------------------------------------------------
 aarch64 / HassOS 2.3 / HA 0.82.1 / SU 140 / stable
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 02-updates.sh: executing... 
INFO: You are running the latest version of this add-on
[cont-init.d] 02-updates.sh: exited 0.
[cont-init.d] 10-requirements.sh: executing... 
WARNING: Logging in with root use is security wise, a bad idea!
WARNING: Logging in with a SSH password is security wise, a bad idea!
WARNING: Please, consider using a public/private key pair
WARNING: Password is in the Have I Been Pwned database!
WARNING: Password appeared 9323 times!
FATAL: Please choose a different SSH password, this one is unsafe!
[cont-init.d] 10-requirements.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.
 
 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] syncing disks.

Some clue to help me here...?

**Comment by tjorim** [comment]
You didn't disable the password check, read the documentation again: https://github.com/hassio-addons/addon-ssh/blob/master/README.md#option-i_like_to_be_pwned

**Comment by educastellini** [comment]
-Like I see in the topic of the other add-on I have the same problem: 
-The 2 options for disable pwned in configuration don't disable if you see in configuration I post here I put both of then in and don't work.

  "i_like_to_be_pwned": false,
  "leave_front_door_open": true

-Any one disable the option?
-How its used?

-I put the options in the beginning, in the middle of config and the system put automatically in the end the options but, don't really disable the pwned in the initialization of add-ons.

-Any one here really knows how to disable the pwned in the initialization of the add-on?
