### ISSUE TITLE
Default shell is very alien to bash users

### ISSUE THREAD

**Issue by freekvh** [hassio-addons/addon-ssh#46]
# Problem/Motivation

> When I ssh into my Hass.io install using this ssh server I enter a completely alien environment, I can't tab-complete, I can't select lines and middle-click-paste even the mouse remains a pointer when hoovering over text (in stead of a text selector. I can't get my public key out, I can cat it, after completely typing over the filename (first time I even had to do this). I can't ctrl-shift-C copy as well. There is also no right click paste anymore.

I understand the shell is different (zsh if I'm correct) but I spend my days on the CLI and I am completely lost here. Even running /bin/bash does not allow normal Linux copy-paste.

## Expected behavior

> Enter a Bash environment or, be able to switch to bash (and use select-middle-click-paste) simply.

## Actual behavior

> I am unable to do even basic things.

## Steps to reproduce

Just ssh to you hass.io box.

## Proposed changes

> Add a way to enter a more familiar environment in s simple way

**Comment by frenck** [comment]
I understand the frustration, but I would appreciate a serious and descriptive title.
Thanks.

**Comment by frenck** [comment]
I think you are mixing up things to be honest.
ZSH is nearly Bash compatible, so that is not the issue.
The copy & pasting differences are caused by tmux.

Will check if this behaviour can be adjusted.

**Comment by freekvh** [comment]
Like this? Sorry, It took me some time today, the normal ssh addon forget /root/.ssh every reboot so I went with this addon, which has other issues :)

**Comment by frenck** [comment]
Ow, PS, the behavior by tmux can be overridden using the shift key (or option key on mac) while selecting the text.

**Comment by freekvh** [comment]
Ah, great, yes that did the trick, key is in gitlab, everything pushed. Thanx for the swift help! Am I correct in assuming this plugin retains my keys?

**Comment by frenck** [comment]
Yes, the `.ssh` user folder is retained across add-on restarts.

**Comment by freekvh** [comment]
Ok, I prefer clean bash but, other than the copy-pasting I have no issues then. Apologies for my initially a-bit-frustrated-sounding-title. You do nice work. Thank you.
