### ISSUE TITLE
grep does not appear to be working

### ISSUE THREAD

**Issue by diginfo** [hassio-addons/addon-ssh#470]
I cant seem to get grep to work at all, it just seems to hang whenever I do a simple search i.e.

```
cd /config
grep -r "sensor"

```

**Comment by frenck** [comment]
You might want to google and find the manual on `grep`, as your command is missing the input (e.g., the folder you want to run grep on).

../Frenck

**Comment by diginfo** [comment]
Thanks so much for helping, but if I run that command on any of my other linux boxes, it runs successfully:

```
# echo -e "sensor" > test.txt
# grep -r "sensor"
test.txt:sensor
```
