### ISSUE TITLE
Doesn't work on VirtualBox default HA install

### ISSUE THREAD

**Issue by dougransom** [hassio-addons/addon-ssh#471]
# Problem/Motivation
Installed HA on virtualbox following the instructions
https://www.home-assistant.io/installation/windows.

> (Why the issue was filed)

## Expected behavior
> (What you expected to happen)
Click start, then open web ui.  shell starts.

## Actual behavior
Click start, then open web ui.  shell starts.
"SSH & Web Terminal:  Add-on is not running.   please start it first".

> (What actually happened)
Click start, then open web ui.   
See this  "SSH & Web Terminal:  Add-on is not running.   please start it first".
Go back to SSH & Web Terminal.  Hit refresh.    start is available again.

## Steps to reproduce
insstall ha on virtual box per https://www.home-assistant.io/installation/windows.
attempt to start ssh & Web Terminal.

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
Can you please look at the addon log for issues?

**Comment by frenck** [comment]
This issue happens when you are too fast. As per add-on installation instructions, check the logs for details and to make sure everything is running fine. Once startup has been completed (and no errors in the logs are shown), Ingress will work as expected.

../Frenck
