### ISSUE TITLE
opening a port

### ISSUE THREAD

**Issue by BentEngbers** [hassio-addons/addon-ssh#472]
# Problem/Motivation
First of all thanks for this amazing tool!
I am probably overlooking something simple, but I cannot reach the server running inside this addon.
I would like to run iperf3 in server mode inside this addon, to test my local network. Installing it inside the container of this addon seems to be the quickest way to do this. 
If there is another addon that allows iperf to be run in server mode, please let me know!
## Expected behavior

I expect, when i run the command `iperf3 -s` that iperf3 server running on port `5201` can be reached from within my LAN.

## Actual behavior

When i try to connect to the server it returns the following message:
```log
iperf3: error - unable to connect to server: Connection refused
```
When i tried scanning the ip adress of homeassistant for open ports using rustscan, it did not indicate that port 5201 was open.

If i run the server on my local machine, and use the ssh connection to homeassistant it does work.

## Steps to reproduce

The following is my config file. 
```yaml
authorized_keys:
  - >-
    *********
password: ""
apks:
  - iperf3
server:
  tcp_forwarding: true
```
The command to start the server is:
```shell
iperf3 -s
```
The command to connect as client is:
```shell
iperf3 -c <ip address of server> -p <port>
```
## Proposed changes
perhaps I am overlooking some documentation, but a short section on how to open ports would be helpful.

**Comment by frenck** [comment]
```yaml
apks:
  - iperf3
```

This add-on does not have such a configuration. You are mixing up this community add-on with the Core maintained add-on.

../Frenck
