### ISSUE TITLE
SCP requires setting username to root

### ISSUE THREAD

**Issue by BioSehnsucht** [hassio-addons/addon-ssh#477]
# Problem/Motivation

Unable to SCP with default configuration

## Expected behavior

SCP should work

## Actual behavior

SCP gives permission denied:
```
# scp /etc/letsencrypt/live/example.org/*.pem hassio@homeassistant:/ssl/.
scp: /ssl//cert.pem: Permission denied
scp: /ssl//chain.pem: Permission denied
scp: /ssl//fullchain.pem: Permission denied
scp: /ssl//privkey.pem: Permission denied
```

## Steps to reproduce

Attempt to SCP files with any username other than root

## Proposed changes

Documentation should include mention that in order to perform SCP of files, username must be `root`. I assume this is the same requirement for enabling SFTP support, but SCP works with SFTP turned off once username is set to `root`, and the documentation makes no mention of SCP. This is probably the cause of the previously opened SCP issues (which got closed after  being marked inactive even though they were never addressed by anyone).

Of course the ideal solution would have SCP working regardless of the username used, but that may not be possible. Documenting the work-around at a minimum though should be done to prevent others from running into this issue.

**Comment by BioSehnsucht** [comment]
Related issues:
https://github.com/hassio-addons/addon-ssh/issues/77
https://github.com/hassio-addons/addon-ssh/issues/76

**Comment by frenck** [comment]
> Documentation should include mention that in order to perform SCP of files, username must be root.

![image](https://user-images.githubusercontent.com/195327/207583365-04b0775d-282a-42db-821b-8187e738c382.png)

☝️ It already does say that since the first version of the add-on.

../Frenck

**Comment by BioSehnsucht** [comment]
SFTP and SCP are not precisely the same thing.  Since I was searching for anything related to SCP in the issues and such, and it didn't originally occurr to me to search for SFTP, I didn't even notice that SFTP usage note for a while. That's why I suggested mentioning SCP as well.
