### ISSUE TITLE
Config file for ssh 

### ISSUE THREAD

**Issue by SoniaMalki** [hassio-addons/addon-ssh#488]
Hi !
I read the guide about the shell_command + this ssh add on for HomeAssistant. I understand you said in the guide to keep everything in /config folder to keep the files because they will be wiped on each update.

So I have a question regarding this. I am using a config file stored /root/.ssh/ named simply config. In this file there is a multitude of hosts saved with their parameters. 

If I use the terminal with SSH I can successfully run “ssh hostname” and connect in a simple command. However this file is not persistent by your explanation + the shell_command does not have access to /root thus to this command and return a 255 error code.

I saw on guide online that a new location can be configured if the proper ssh file is configured in /etc/ but I am afraid it won’t be persistent either. 

Could you help me please ? 

Thank you

**Comment by SoniaMalki** [comment]
Hello, 

Little update, I managed to make it work. I just don't know if it will be persistent. Here is the step to reproduce:

1) Connect in SSH into the homeassistant machine
2) Add my config file for ssh into the folder /config/.ssh
3) docker exec -it homeassistant bash
4) Change the ssh_config file to include my config file : "echo "Include /config/.ssh/config >> /etc/ssh/ssh_config"
5) I checked with cat if it was added at the end, "cat /etc/ssh/ssh_config", it was indeed.
6) I tried to use the config file by connecting via ssh "ssh hostinfile". And it worked, the ssh instance was including my config file.

My questions is, is it persistent? Could you add the include as an option for your addon, that could be easier to do than my steps. The config file is very nice because I can just type "ssh hostname" and then connect easily with all the specific parameters (the keys, the known_host path, ...) in the config file, without having to type a loooong line.

Thanks

**Comment by frenck** [comment]
This has nothing to do with these add-ons:

![CleanShot 2023-01-12 at 14 46 02](https://user-images.githubusercontent.com/195327/212083096-dcc9c91f-c1ab-4ea8-98d2-9bd3a5741b26.png)

Your question is about using Home Assistant integrations/commands in general.

Closing the issue on this end, because its unrelated.

../Frenck

**Comment by SoniaMalki** [comment]
Why ? I executed this command to have access to the ssh_config file, as you said in your help thread.
