### ISSUE TITLE
Be able to run commands as root

### ISSUE THREAD

**Issue by He-Man321** [hassio-addons/addon-ssh#492]
# Problem/Motivation

I was trying to mount a device on HAOS running on a Pi4, and you just get permission denied.  I tried Protected mode on\off and putting it in init_commands: but all failed.

## Expected behavior

To be able to mount a device.

## Actual behavior

mount: permission denied (are you root?)

## Steps to reproduce

mount /dev/mmcblk0p1 /tmp/mnt

## Proposed changes

Is the Protected mode option broken?  Should there be another way to enable it to run as root? In the end I had to hook up a keyboard to the Pi and run it from the terminal there, which does work, but a lot of hassle.

**Comment by frenck** [comment]
This has nothing to do with being root or not. This is a container, which does not have this level of access.

../Frenck

**Comment by He-Man321** [comment]
Ah, so SSH & Web Terminal is running in a container that does not have this level of access? Is there any way to give the container a higher level of access?  What is Protected mode protecting you from, if it cannot do anything outside of its own container anyway?

**Comment by frenck** [comment]
> Is there any way to give the container a higher level of access? 
No.

> What is Protected mode protecting you from

Multiple things, like access to the Docker sockets.

If you need things like mounting drives, the installation you are running might not be the right fit for you. Consider running the Home Assistant Container installation method on your own OS instead.

../Frenck
