### ISSUE TITLE
Missin option in the config but it's there

### ISSUE THREAD

**Issue by viciovb** [hassio-addons/addon-ssh#493]
When I try to change the configuration I get an error that one option is missing even it's present.

This is the config I use, a very basic one:

> ssh:
>   username: hassio
>   password: ''
>   authorized_keys: []
>   sftp: false
>   compatibility_mode: false
>   allow_agent_forwarding: false
>   allow_remote_port_forwarding: false
>   allow_tcp_forwarding: false
> zsh: true
> share_sessions: false
> packages: []
> init_commands: []

And this is the error:

`Failed to save add-on configuration, Missing option 'allow_tcp_forwarding' in ssh in SSH & Web Terminal (a0d7b954_ssh). Got {'init_commands': [], 'packages': [], 'share_sessions': False, 'ssh': {'ssh': {'username': 'hassio', 'password': '', 'authorized_keys': [], 'sftp': False, 'compatibility_mode': False, 'allow_agent_forwarding': False, 'allow_remote_port_forwarding': False, 'allow_tcp_forwarding': False}, 'zsh': True, 'share_sessions': False, 'packages': [], 'init_commands': []}, 'zsh': True}`

I really don't understand what's going on.

**Comment by mrohner** [comment]
I have the same problem:

log_level: info
ssh:
  sftp: false
  compatibility_mode: false
  allow_agent_forwarding: false
  allow_remote_port_forwarding: false
  allow_tcp_forwarding: false
  username: xxxxxxx
  password: "yyyyyy"
  authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDQp4Rwg....
zsh: true
share_sessions: false
packages: []
init_commands:
  - ls -la

Failed to save add-on configuration, Missing option 'allow_agent_forwarding' in ssh in SSH & Web Terminal (a0d7b954_ssh). Got {'init_commands': [], 'packages': [], 'share_sessions': False, 'ssh': {'log_level': 'info', 'ssh': {'sftp': False, 'compatibility_mode': False, 'allow_agent_forwarding': False, 'allow_remote_port_forwarding': False, 'allow_tcp_forwarding': False, 'username': 'xxxxxx', 'password': 'yyyy', 'authorized_keys': ['ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDQp4Rwg+lSEEM...
