### ISSUE TITLE
Unable to connect via SSH using Apache Guacamole

### ISSUE THREAD

**Issue by Corrado-possieri** [hassio-addons/addon-ssh#495]
# Problem/Motivation

Unable to connect via ssh using Apache Guacamole

## Steps to reproduce

 I am running Apache Guacamole in a Docker container.

The setup is as follows:

>Apache Guacamole is version 1.4
>Add-on version: 13.0.2
>System: Home Assistant OS 9.4 (aarch64 / raspberrypi4-64)
>Home Assistant Core: 2023.1.7
>Home Assistant Supervisor: 2022.12.1

The configuration of the add-on is
>allow_agent_forwarding: false
>allow_remote_port_forwarding: false
>allow_tcp_forwarding: false
>compatibility_mode: false
>sftp: false

The logs of the add-on report

>Connection from XXX.XXX.XXX.XXX port XXX on XXX.XXX.XXX port 22 rdomain ""
>Unable to negotiate with XXX.XXX.XXX port XXX: no matching host key type found. Their offer: ssh-rsa,ssh-dss [preauth]

## Proposed changes

 I tried to set compatibility_mode to true, but I am still unable to connect via Guacamole. 
Is there a way to connect properly, possibly using one of the extensions available in Guacamole 1.4?

**Comment by frenck** [comment]
I'm not aware what Apache Guacamole supports :)

**Comment by Corrado-possieri** [comment]
This is the list of extensions

auth-duo
auth-header
auth-jdbc-mysql
auth-jdbc-postgresql
auth-jdbc-sqlserver
auth-json
auth-ldap
auth-quickconnect
auth-sso-openid
auth-sso-saml
auth-sso-cas
auth-totp

**Comment by frenck** [comment]
Not sure how that relates to connecting to SSH 🤷
