### ISSUE TITLE
Configuring the log level doesn't seem to work

### ISSUE THREAD

**Issue by erkr** [hassio-addons/addon-ssh#500]
# Problem/Motivation

Thanks for this life saving add-on ;-) It is really great. I try to limit logging load to prevent system overhead.
I configured Warning for the log level but the setting doesn't seem to work. I see the same amount of informational logging.

## Expected behavior

No informational logging

## Actual behavior

> (What actually happened)

## Steps to reproduce

I defined warning as log level in the configuration, but it seems to be ignored. snap shot from the log:
```
Log level is set to WARNING
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-user: starting
s6-rc: info: service init-ssh: starting
s6-rc: info: service init-mysql: starting
s6-rc: info: service init-mosquitto: starting
...
```
And for every new connection:
```
Starting session: command for <usr> from 192.168.178.xxx port 42198 id 0
Close session: user <usr> from 192.168.178.xxx  port 42198 id 0
Received disconnect from 192.168.178.xxx  port 42198:11: disconnected by user
Disconnected from user <usr> 192.168.178.xxx  port 42198
Connection from 192.168.178.xxx  port 56098 on 172.30.32.1 port 22 rdomain ""
Accepted key RSA SHA256:<the key............................> found at /etc/ssh/authorized_keys:1
Postponed publickey for <usr> from 192.168.178.xxx  port 56098 ssh2 [preauth]
Accepted key RSA SHA256:<the key............................> found at /etc/ssh/authorized_keys:1
Accepted publickey for <usr> from 192.168.178.xxx  port 56098 ssh2: RSA SHA256:<the key............................>
```
## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by erkr** [comment]
Not solved

**Comment by frenck** [comment]
> I defined warning as log level in the configuration, but it seems to be ignored. snap shot from the log:

That part is of the init system, and I can't suppress that.

> And for every new connection:

Those are logs from SSH, not the add-on. The log controls are for the add-on logs.

When the add-on logs are set to debug/trace, it allows applications to hook into that and go into debug themselves as well, in this case, SSH does that. But that is only if debug is enabled on the add-on. Other controls have indeed no effect (and by design).

../Frenck

**Comment by erkr** [comment]
Thanks for explaining :-)
