### ISSUE TITLE
/addons mount in ssh addons not the good one...

### ISSUE THREAD

**Issue by mcarbonneaux** [hassio-addons/addon-ssh#503]
# Problem/Motivation

i cannot acces to /mnt/data/supervisor/addons/ from ssh addons like /mnt/data/supervisor/config and /mnt/data/supervisor/data (respectively in /config and /data) in the ssh container.

## Expected behavior

to have access to /mnt/data/supervisor/addons in /addons directory of the container.

## Actual behavior

/addons are mounted to /mnt/data/supervisor/addons/local

## Steps to reproduce

in ssh terminal windows

```
# ls -al /addons
```
not list content of /mnt/data/supervisor/addons (where all addons configurations are) but of /mnt/data/supervisor/addons/local.

and in docker inspect i see (in hostconfig/bind) the /addons are mount of /mnt/data/supervisor/addons/local :
- "/mnt/data/supervisor/addons/local:/addons:rw"

**Comment by frenck** [comment]
> I cannot acces to /mnt/data/supervisor/addons/ from ssh addons like 

That is correct. Add-ons do not have access to those.

../Frenck

**Comment by mcarbonneaux** [comment]
why ?
we are oblige to use docker exec to enter in supervisor container (from ssh container) to acces it or use ssh on the host... 
but without all the necessary tool (that exist on ssh container)...

for exemple i need to reset password on nginx proxy manager, and do sql request on sqlite file... but nor nginx proxy manager, supervisor or host contain sqlite3 command...

**Comment by frenck** [comment]
> why ?

You are asking this in the wrong place. This is an add-on, that has access to what it is given.
Can't change that from the add-on perspective.

../Frenck

**Comment by mcarbonneaux** [comment]
is manager by supervisor by default way of starting (and mounting) a add on ?

**Comment by mcarbonneaux** [comment]
> You are asking this in the wrong place. This is an add-on, that has access to what it is given.

i whant place i must ask ?

**Comment by frenck** [comment]
You are not understanding those docs you quoted.

**Comment by mcarbonneaux** [comment]
> You are not understanding those docs you quoted.

my understand, is for me each addon has its configuration file which defines how it will be executed.
this file is config.yaml, for ssh addon: https://github.com/hassio-addons/addon-ssh/blob/main/ssh/config.yaml

and in section `map`, you define what directory while be mapped in the container of the addon.

the possible value are: config, ssl, addons, backup, share or media

but no explain on what `addons` value `map` in reality (/mnt/data/supervisor/addons/local or /mnt/data/supervisor/addons/).

is my understand...

if is wrong explain me...

**Comment by frenck** [comment]
`addons` is the source of custom add-ons. Not other add-ons data folders.

**Comment by mcarbonneaux** [comment]
> 



> `addons` is the source of custom (local) add-ons. Not other add-ons data folders.

yes is what i have understanded at the final (is why /local at the end of the bind), and is not well explained in the documentations...

but i think is need a new value in map section the map the other add-ons data folders...

**Comment by frenck** [comment]
> and is not well explained in the documentations...

🤷 I do not fully agree, but that is (again) not related to this add-on.

> but i think is needed a new value in map section to map the other add-ons data folders (/mnt/data/supervisor/addons/)..

I don't agree on that. Add-on should not have access to each other's data IMHO.

**Comment by frenck** [comment]
> nd is the role of Protection mode flag to enable/disable this access...

It is not.

**Comment by mcarbonneaux** [comment]
what is the principal usage of ssh add on ?

**Comment by frenck** [comment]
Different from yours apparently.

The issue is, you are approaching this from an OS level, which this is not.

If you want access to an OS, this installation method is not what you should be using in the first place.

**Comment by mcarbonneaux** [comment]
no i don't whant to access to the os, if i need that i use the host ssh access with key.

is not the idea of hsos, i think.

but majority of the configuration are accesible by different addon like ssh addon and file editor addon, samba addon, but only permit access to the base configuration file.

in addon you have generaly some configuration file (like in nginx proxy manager sqlite database) the are backed up (with ha backup by the supervisor) but cannot be accesible like other ha configuration.

my answer is to be abel to access to this file to for exemple correct problem on this configuration file (like my first problem, the lost of password of nginx proxy manager).

i find the way of doing it (by entering in docker container of nginx proxy manager, and adding sqlite package) ... 

but i think while be normal to be abel to access to this file this type of admin addons config.... to avoid the make complex manipulation to access it...

**Comment by frenck** [comment]
> my answer is to be abel to access to this file to for exemple correct problem on this configuration file

If that happens, I will deprecate all my add-ons and stop creating them.
It will cause people to work around things and mess with stuff that will become a support nightmare.

Hence, I do not agree with your stance.

**Comment by mcarbonneaux** [comment]
> If you want to have that level of control, you are running the wrong installation method/environment. Home Assistant offers other installation types for those advanced use cases.

i think that haos installation method is the best method... all other are not stable than this...

and i think while very usefull for advanced user to be abel to unlock the haos to manage this type of situation...

**Comment by frenck** [comment]
I strongly do not agree, as you can see in my previous response.

Sorry.

**Comment by mcarbonneaux** [comment]
don't lock the usage, permit the unlock for advanced user, i think the community in contrario while send back contribution.

more i learn how to ha is working more i like.
and more i whan to contribute.

and for me the installation with standard linux is not the good way. the good way is haos way. that strenthen the os like a rock.
all other open source iot plateform are using standard linux as base...  and is source of instability.... and complexity...

limiting complexity in doing light os is the good way for me.
and the use of container for separating thing is very advanced and secure way of doing.

**Comment by mcarbonneaux** [comment]
i see many exchange on this theme in fact on supervisor: 
- https://github.com/home-assistant/supervisor/issues/1842

**Comment by frenck** [comment]
That is not the same, that RFC still provides a separation between internal and user-configurable data.

**Comment by mcarbonneaux** [comment]
is the same: "Every Add-on have a differen aproach to solve the issue if people need to be able to edit files."

the problem is to be abel to edit addons config files like core config files...

**Comment by mcarbonneaux** [comment]
ok, if i misunderstand, explain me.

but at the end the need is to be abel manage the configuration files in addons like in core product from ha ui admin panel (as you can configure homeassistant.conf for exemple).
