### ISSUE TITLE
How to use a different directory for ~/.ssh?

### ISSUE THREAD

**Issue by jclsn** [hassio-addons/addon-ssh#525]
I would like to share keys between containers. Since ``shell_command`` services are executed in the homeassistant container, I would need it to use the same keys as the host. Atm the default locations is ``/root/.ssh``and this directory is not shared between containers. So I want to change it to ``/config/.ssh``

**Comment by frenck** [comment]
The add-on does not provides an option to that. You can try setting up such things using the `init_commands` option, that maybe adds a symlink or adjusts the SSH configuration to use a different path.
