### ISSUE TITLE
502 Bad Gateway: Can‘t set user password

### ISSUE THREAD

**Issue by superpower10** [hassio-addons/addon-ssh#535]
Installed plugin. 

Was looking for a way to insert username and password. But can’t find it:
![IMG_0652](https://user-images.githubusercontent.com/20533966/230783148-924c21a9-f2d0-48a5-a750-5a37f33f137f.jpeg)

Doesn‘t start without. Getting „502 Bad Gateway“ as error

How do I configure it? Didn‘t find any answer in the documentation. Tried different browsers. 

Home Assistant Version 2023.04.2

**Comment by Billabongodysee** [comment]
I'm having a similar issue. I can see the configuration area but when trying to put a secure password in between the double quotes it will not save it. I enter a password, click save, go to the log tab to see that things are okay and it says no password is entered. I go back to the configuration tab and everything is at the defaults. If I start the service first then try to add the password, when I hit save it knows the config has changed and it tells me it needs to restart but again it erases the password and doesn't start leaving me stuck with the 502 gateway error. Running core 2023.4.1 and lastest OS build.

**Comment by superpower10** [comment]
@Billabongodysee 
I don‘t see the fields for entering username or password! 

Your problem is different

**Comment by superpower10** [comment]
Found the error. The Add-On-Fields are not compatible with iOS/MacOS Safari and WebKit (which is used in the Companian App).

I had to use Windows with Chrome/Firefox to see the fields and enter them.

This should be fixed. It’s definitely an bug/issue.
