### ISSUE TITLE
SSH & Web Terminal  bug? ssl": false" open web ui  goes to https://

### ISSUE THREAD

**Issue by vMeph** [hassio-addons/addon-ssh#54]
# Problem/Motivation

Was wondering why when setting the ```"web":``` to ```"ssl": false,``` and the you click the Open Web Ui it will got to ```https:// xxx.xxx.x.xx```

## Expected behavior

if ```"ssl": false,```  go to ```http://```  when you click Open Web Ui

## Actual behavior

```"ssl": false,```  goes to ```https://```  when you click Open Web Ui

## Proposed changes

```"ssl": false,```  goes to ```http://```  when you click Open Web Ui
```"ssl": true,```  goes to ```https://```  when you click Open Web Ui

**Comment by timmo001** [comment]
This is an unfortunate bug in hass.io. To put it simply, because the `"ssl": false,` is nested under another object in the JSON config, this cannot be picked up from hassio. Due to this, ssl is always enabled (since it is encouraged)
