### ISSUE TITLE
Doesn't do anything

### ISSUE THREAD

**Issue by rwb196884** [hassio-addons/addon-ssh#546]
![image](https://user-images.githubusercontent.com/12090617/235319018-c45eae4c-a5b7-4055-8ae8-b539f5e8e904.png)

Clicking _START_ does nothing.

The page at Settings -> Add-ons says
> You don't have any add-ons installed yet. Head over to the add-on store to get started!

How do you install this?
How can you tell if it's installed?
How do you use it after it's been installed?

**Comment by frenck** [comment]
> The page at Settings -> Add-ons says

> You don't have any add-ons installed yet. Head over to the add-on store to get started!

That is an issue with the Home Assistant frontend, please report the issue with them. Sometimes a couple of browser refreshes fixes it.

Closing the issue on this end, as the UI reporting an issue on, is not controlled by the add-on.

../Frenck
