### ISSUE TITLE
Addon v14 keeps crashing

### ISSUE THREAD

**Issue by g1za** [hassio-addons/addon-ssh#551]
# Problem/Motivation

> Following update to v.14 the addon keeps crashing. Addon and system was rebooted several times. As there was a breaking change in the name of the addon I preferred to uninstall and re-install. This is happening on 2 HA instances I have. Attached the logs from one of them.

[ha instance.zip](https://github.com/hassio-addons/addon-ssh/files/11367539/ha.instance.zip)

**Comment by frenck** [comment]
Thanks for those, that is definitely an issue.
I will try to look at that as soon as I can.

../Frenck

**Comment by SkepticNerdGuy** [comment]
Good evening, fresh install of Home Assistant OS on generic X86-64. Just tried installing add-on and it fails to start. Strangely I have it updated and running with no issues on my current in production RPI-4 install.

I believe that #552 is the same issue. The highlighted error seems to be something common among reports. 

```
s6-rc: info: service init-mosquitto successfully started
/etc/s6-overlay/s6-rc.d/init-user/run: line 55: /data/.ssh/environment: No such file or directory
[19:45:06] FATAL: Failed to set Supervisor API token in env
s6-rc: warning: unable to start service init-user: command exited 1
```
My log attached. 
[Advanced SSH & Web Terminal.txt](https://github.com/hassio-addons/addon-ssh/files/11368712/Advanced.SSH.Web.Terminal.txt)

respectfully,
Skeptic

**Comment by sinclairpaul** [comment]
I think we need to just jump the commands down a bit:

<https://github.com/hassio-addons/addon-ssh/blob/e8d5f73b36dc3b8b87937e8b4dda5e6d6fea75e9/ssh/rootfs/etc/s6-overlay/s6-rc.d/init-user/run#L55>

<https://github.com/hassio-addons/addon-ssh/blob/e8d5f73b36dc3b8b87937e8b4dda5e6d6fea75e9/ssh/rootfs/etc/s6-overlay/s6-rc.d/init-user/run#L58>
