### ISSUE TITLE
FATAL: Failed to set Supervisor API token in env

### ISSUE THREAD

**Issue by kdre** [hassio-addons/addon-ssh#554]
# Problem/Motivation

I am running the latest HA OS version on a rpi 4 and wanted to ssh into the box using this addon (version v14.0.0). I changed user and passwd using the "edit in yaml" menu. Unfortunately, the addon does not start. Also tried to reboot the device without success.

Two days ago there were no problems. So probably v14.0.0 breaks something?

## Expected behavior

Addon should start without error messages and enable ssh login.

## Actual behavior

The add on does not start due to the following error:

/etc/s6-overlay/s6-rc.d/init-user/run: line 55: /data/.ssh/environment: No such file or directory
[10:18:42] FATAL: Failed to set Supervisor API token in env
s6-rc: warning: unable to start service init-user: command exited 1

## Steps to reproduce

* Install latest HA OS on a rpi 4
* Install ssh addon
* Try to start the addon

**Comment by frenck** [comment]
Closing as a duplicate, see issue history.

../Frenck
