### ISSUE TITLE
I can't install any plugins and updates

### ISSUE THREAD

**Issue by fschenkun22** [hassio-addons/addon-ssh#556]
# Problem/Motivation
I have tried to install homeassistant in various ways, but only the Raspberry Pi succeeded once. The reason for the success is that I can use SSH for proxy and HOSTS settings, because I am in China, and the network in China is very poor, and I cannot access python pip normally  and github aosl, so now it's embarrassingly I can't proceed with system updates and other plugin installations
> because i'm in china
## Expected behavior
because i'm in china
> The network proxy server can be turned on before the system initialization starts, so that I can update and use it normally
## Actual behavior
Has been unable to install any updates or plugins
> I'm so sorry I can't connect using SSH, I can only take screenshots in the terminal
![image](https://user-images.githubusercontent.com/13625213/235902339-0699cddc-d087-4375-ad50-f5ad9b2ee6f0.png)

## Steps to reproduce

> You come to China to try

## Proposed changes
All plug-ins or updates downloaded via network installation require the network proxy to be enabled before updating, but the current system does not have any options to configure them. So now the installation is tough and always fails for network reasons. So now it will be easier if you can successfully turn on the web proxy before installing。
I think it is also a way to adjust the docker source URL. Thank you very much！

**Comment by frenck** [comment]
>  but the current system does not have any options to configure them.

Sorry, can't help you with this. Add-ons cannot provide such options.

../Frenck
