### ISSUE TITLE
Add-On starts and stops again

### ISSUE THREAD

**Issue by henfri** [hassio-addons/addon-ssh#558]
# Problem/Motivation

The Add-On starts and after few seconds (and reload of the addon-page) it restarts

## Expected behavior

To start and permanently stay started

## Actual behavior

it stops seconds after starting

## Steps to reproduce

Install, then start the add on

Unfortunately, nothing is visible in the logs. I understand that you cannot help me with the above information...
Is there a way to increase the log-level of the Add-On?

Best regards,
Hendrik

**Comment by craigmcfly** [comment]
Experiencing the same, but I've never tried to use it before 2023.5.

**Comment by frenck** [comment]
There must be something in the logs... otherwise, please check the logs of the host OS or Supervisor to see if there if more information available.

../Frenck

**Comment by henfri** [comment]
Hi Frenck,

thanks for your reply.
There really ist nothing in Home-Assistent.log.

I am using the HA-VM. I am familiär with Linux, but habe No clue how to Check the OS logs - and which ones could Help?

**Comment by frenck** [comment]
The logs of all parts of the system can be found in the settings menu of the Home Assistant:

**Settings** -> **System** -> **Logs**

Once there, there is a selector in the top right to switch between al the different parts.

../Frenck

**Comment by craigmcfly** [comment]
I agree with henfri that there are no logs

**Comment by frenck** [comment]
> I agree with henfri that there are no logs

If that is truly the case, then I can't help 🤷  I unfortunately don't own a crystal ball 😬

**Comment by craigmcfly** [comment]
Okay, I did some poking around, and it was the lack of password causing a problem. I had forgotten to change the settings it comes with. I would have expected it to log something by default if you try to start the addon without a password.

**Comment by frenck** [comment]
> I would have expected it to log something by default if you try to start the addon without a password.

It does, it is even part of the installation instructions documented:

**Comment by craigmcfly** [comment]
There were definitely no logs or errors thrown.

**Comment by frenck** [comment]
I'll set up a fresh system and try to reproduce, brb.

**Comment by frenck** [comment]
Seems to work just fine; reproduced on an ODROID N2+, with Home Assistant OS:

<img width="1425" alt="image" src="https://user-images.githubusercontent.com/195327/236646412-170c7f56-dcda-4ef7-980a-cec17d4dd305.png">

**Comment by craigmcfly** [comment]
Oh, I was looking here

> The logs of all parts of the system can be found in the settings menu of the Home Assistant:
> 
> **Settings** -> **System** -> **Logs**
> 
> Once there, there is a selector in the top right to switch between al the different parts.
> 
> ../Frenck

**Comment by frenck** [comment]
> Oh, I was looking here

Sure, that works too:

<img width="1555" alt="image" src="https://user-images.githubusercontent.com/195327/236646602-9a7c5de7-baa5-44ea-a444-419a77cb71c2.png">

**Comment by craigmcfly** [comment]
Is that 2023.5? I can't find my way to that screen.

**Comment by frenck** [comment]
> Is that 2023.5? I can't find my way to that screen.

Yup, also, in older versions of Home Assistant, this is not new.

It is in Settings -> System -> Log. You can select any log there, from many parts of the system.

../Frenck

**Comment by craigmcfly** [comment]
No matter what I do I can't find it, but at least now I know to look in the individual add-on logs :) Thanks for the assist.

**Comment by henfri** [comment]
OK, for me, it was the Missing Password. But when installing via the add on Store, one does Not See the Docs telling to Set a Password.

Would be good to Show an Info If IT IS unser and trying to start the add on.

Thanks for your Help!
