### ISSUE TITLE
Advanced SSH & Web Terminal wont start

### ISSUE THREAD

**Issue by zimba7768** [hassio-addons/addon-ssh#559]
# Problem/Motivation 
> (Why the issue was filed)

## Expected behavior

> (What you expected to happen) I expect when I hit start, it will start

## Actual behavior - After I hit start, it shows that it starts but when I hit terminal, it says it is not started

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Anything in the logs?

**Comment by zimba7768** [comment]
The logs are blank for Advanced SSH & Web Terminal

**Comment by schelv** [comment]
Maybe it is the same problem as here?
https://github.com/hassio-addons/addon-ssh/issues/558

**Comment by zimba7768** [comment]
Thank you for posting this. I could not find anything in there to help. It wont start and there are no logs to look at.

**Comment by frenck** [comment]
I cannot reproduce the missing logs in any of my setups, see also #558 for multiple screenshots from logs in multiple places.

Wish I could help out on this one, but I'm lost on the reports received.

../Frenck

**Comment by erwanclx** [comment]
Same issue

**Comment by zimba7768** [comment]
I just figured it out. I used the add-on called Advanced SSH & Web Terminal. I then clicked on the configuration tab at the top. I put in a password, saved it. Now it shows up in the logs and started correctly. Hope that helps others.

**Comment by frenck** [comment]
> I just figured it out. I used the add-on called Advanced SSH & Web Terminal. I then clicked on the configuration tab at the top. I put in a password, saved it. Now it shows up in the logs and started correctly. Hope that helps others.

You mean, that what is exactly written in the installation instructions? 😬

**Comment by RandyTidd** [comment]
FWIW, I ran into the same issue.  Installed Add-on and did not notice the tabs along the top.  Tried starting it w/ same symptoms in zimba7768.  

Nothing in the logs, so I read the content on the Info tab.  I scanned the github readme for instructions.  Was about to give up and solve my problem another way when I decided to search and found this issue report.

This is my first add-on I've had to configure, so now I've learned those tabs exist. 

The webui doesn't require log in, so could a random default password be generated so the server starts and allows access there?  Otherwise, seems worth a log entry and possibly a mention on the info tab.

**Comment by schelv** [comment]
@RandyTidd That basically describes the same experience I had.
For some reason the tabs at the top are easy to miss.

A possible mention in the info tab seems like a good idea.
currently there is no mention of installation instructions between the button for installing of the add-on and the button for starting the add-on.

**Comment by anubis-code** [comment]
I am getting 502: Bad Gateway when I try to open the WebUI, I have put in a password into the configuration and restarted but get this when I try to open

**Comment by frenck** [comment]
> The info page should mention that a password must be configured

The documentation/installation page already states that.

> A random password could be created automatically

Add-on cannot do that.

> Logs could show that the password was blank.

They already do that.

../Frenck
