### ISSUE TITLE
Use cloudflare subdomain tunnel to logon to Home assistant add-on Advanced SSH & Web Terminal.

### ISSUE THREAD

**Issue by brettw02** [hassio-addons/addon-ssh#563]
# Problem/Motivation

>Looking for a way to connect to advanced ssh & web terminal via cloudflare subdomain tunnel

## Expected behavior

>Connect without having to open ports

## Actual behavior

> Unable to logon to HA ssh session via subdomain tunnel created on cloudflare using cloudflared add-on

My apologies if this is the incorrect place to post this question!!

**Comment by sinclairpaul** [comment]
I would suggest you look at the Cloudflare documentation, this isn't an issue with this addon as it provides both a web interface, and ssh server.
