### ISSUE TITLE
addon eventually crashes, no logs, need to restart every 4-5 hours 

### ISSUE THREAD

**Issue by maxandersen** [hassio-addons/addon-ssh#58]
# Problem/Motivation
ssh-addon crashes after a while of running. 
> (Why the issue was filed)

## Expected behavior
don't crash :)
> (What you expected to happen)

## Actual behavior
it crashes.
> (What actually happened)

## Steps to reproduce
just start it, I have both web and ssh works.
> (How can someone else make/see it happen)

## Proposed changes
I would like to propose something but no logs so not sure where to start.

any way to inspect why the addon crashed ? 

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
I have multiple instances running for long periods of time on different machines.
(cool thing of this add-on, is that I need it to work on all the test machines).

So I'm unfamiliar with the issues tbh. The only thing I can think of, is pushing the device over the edge? (memory wise)? Is that a possibility?

Nevertheless, I would need logs... or anything to grab on?
Supervisor logs, add-on logs, host OS system logs?

**Comment by maxandersen** [comment]
Yeah, I don't expect it to be a common issue as all other addons I have running seem to survive just fine.

Memory wise the memory sensor in homeassistant reports 51.3% when not running the ssh.

Now I was about to start it again to see what difference there is but now it is not starting since it seems it lost all my config for it - weird. Been using it for a while now (got used to restart it :) and the config did survive those - but not know. 

I'll try and get it reconfigured and see how it goes.

from system logs I have pages and pages of this:

```
19-02-11 20:23:02 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states access from a0d7b954_appdaemon3
```

and when I start the addon lines similar to this: 
```
19-02-11 20:33:02 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states access from a0d7b954_appdaemon3
19-02-11 20:43:03 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states access from a0d7b954_appdaemon3
19-02-11 20:43:04 INFO (MainThread) [hassio.homeassistant] Updated Home Assistant API token
19-02-11 20:53:04 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states access from a0d7b954_appdaemon3
19-02-11 20:53:21 INFO (SyncWorker_9) [hassio.docker.interface] Clean hassioaddons/ssh-armhf Docker application
19-02-11 20:53:23 INFO (SyncWorker_9) [hassio.docker.addon] Start Docker add-on hassioaddons/ssh-armhf with version v3.7.1
19-02-11 20:53:29 INFO (MainThread) [hassio.api.security] /addons access from a0d7b954_ssh
19-02-11 20:53:31 INFO (MainThread) [hassio.api.security] /addons access from a0d7b954_ssh
19-02-11 20:53:33 INFO (MainThread) [hassio.api.security] /supervisor/info access from a0d7b954_ssh
19-02-11 20:53:35 INFO (MainThread) [hassio.api.security] /host/info access from a0d7b954_ssh
19-02-11 20:53:36 INFO (MainThread) [hassio.api.security] /homeassistant/info access from a0d7b954_ssh
19-02-11 20:53:37 INFO (MainThread) [hassio.api.security] /supervisor/info access from a0d7b954_ssh
19-02-11 20:53:39 INFO (MainThread) [hassio.api.security] /supervisor/info access from a0d7b954_ssh
```

but no visible trace on when it goes down.

add-on logs are always empty or at least not shown in the UI as the addon is no longer running. does hassio save the logs somewhere ? 

About host OS system logs - how do I best get those for a hass.io PI3B+ machine/setup ?

**Comment by frenck** [comment]
I have not been able to reproduce on an any machine. Furthermore, I have not received any other reports for this.

Is this still an issue for you? If so, I would need to have a reproduction scenario.

**Comment by maxandersen** [comment]
It haven't happened with recent updates. 

I would love to know the answers to the questions I asked on how to collect the info to in the future report better info in case similar happens again.

So far I haven't found a way to get logs for crashed hassio containers nor how to get the system logs for hassio based installs. 

But this specific issue I would consider closed.

**Comment by frenck** [comment]
There is not much where I can go from when it just stops working without logs.
About the only thing that can do that is the OOM killer, nevertheless, you've mentioned that memory wasn't an issue 🤷‍♂️ .

Closing issue for now.
