### ISSUE TITLE
nmcli changes ssh fails with "ipv4.dns-data: unknown property"

### ISSUE THREAD

**Issue by MarcHagen** [hassio-addons/addon-ssh#583]
# Problem/Motivation

Im trying to add a custom route and route metric to one of the interfaces in my homeassistent.
This is a valid and supported way to route traffic, however there seems to be a difference between the nmcli version within the container and the nmcli on the "host" (VM console through proxmox)

```
➜  ~ nmcli connection modify "Supervisor enp6s19" ipv4.route-metric 1
Error: Failed to modify connection 'Supervisor enp6s19': ipv4.dns-data: unknown property
```

I can run this exact command through the VM console (so on the "host") and it applies the settings correctly.
But SSHed into this container it fails.

## Expected behavior

nmcli applying the change

## Actual behavior

SSH addon nmcli fails to apply config

## Steps to reproduce

Home Assistant 2023.6.3
Supervisor 2023.06.4
Operating System 10.3
Frontend 20230608.0 - latest
Advanced SSH & Web Terminal v15.0.2

- Install HASS (dunno if the VM setup is related)
- Install SSH addon and enable it
- SSH into the container
- Try to run any nmcli command from SSH connection

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
> , however there seems to be a difference between the nmcli version within the container and the nmcli on the "host"

That is possible, however, there is nothing I can do about that from an add-on perspective.

../Frenck
