### ISSUE TITLE
401: Unauthorized

### ISSUE THREAD

**Issue by eagle00789** [hassio-addons/addon-ssh#587]
# Problem/Motivation

when using the addon i get the message: 401: Unauthorized

## Expected behavior

get an ssh terminal to hassio

## Actual behavior

got an error: 401: Unauthorized

## Steps to reproduce
Update to latest supervisor (2023.07.1) and the latest HA 2023.7.0
i even enabled compatability mode to try and fix this

## Proposed changes

none

## Relevant Logs:
`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------
 Add-on: Advanced SSH & Web Terminal
 A supercharged SSH & Web Terminal access to your Home Assistant instance
-----------------------------------------------------------
 Add-on version: 15.0.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.3  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.7.0
 Home Assistant Supervisor: 2023.07.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
Log level is set to INFO
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-user: starting
s6-rc: info: service init-ssh: starting
s6-rc: info: service init-mysql: starting
s6-rc: info: service init-mosquitto: starting
s6-rc: info: service init-docker: starting
s6-rc: info: service init-docker successfully started
s6-rc: info: service init-mosquitto successfully started
[23:41:06] NOTICE: Session sharing has been disabled!
s6-rc: info: service init-user successfully started
s6-rc: info: service ttyd: starting
s6-rc: info: service ttyd successfully started
[23:41:06] INFO: Starting the ttyd daemon...
[23:41:07] WARNING: 
[23:41:07] WARNING: Logging in with a SSH password is security wise, a bad idea!
[23:41:07] WARNING: Please, consider using a public/private key pair.
[23:41:07] WARNING: What is this? https://kb.iu.edu/d/aews
[23:41:07] WARNING: 
s6-rc: info: service init-mysql successfully started
[23:41:08] NOTICE: SSH is running in compatibility mode!
[23:41:08] WARNING: Compatibility mode is less secure!
[23:41:08] WARNING: Please only enable it when you know what you are doing!
s6-rc: info: service init-ssh successfully started
s6-rc: info: service sshd: starting
s6-rc: info: service sshd successfully started
s6-rc: info: service legacy-services: starting
[23:41:08] INFO: Starting the SSH daemon...
Server listening on 0.0.0.0 port 22.

Server listening on :: port 22.

s6-rc: info: service legacy-services successfully started`

**Comment by sinclairpaul** [comment]
The logs show the addon running, I'm assuming that the error is when you access the addon via the web interface, which is likely to do with something in your browser blocking the auth.  Please post the output from a browser dev console.

**Comment by eagle00789** [comment]
Ok. problem found. i was experimenting with the SSL Certificates just before the upgrade. i still had the old certificate (self-signed) as an exception in my browser. this caused the issue.
