### ISSUE TITLE
Found the error. The Add-On-Fields are not compatible with iOS/MacOS Safari and WebKit (which is used in the Companian App).

### ISSUE THREAD

**Issue by lpw** [hassio-addons/addon-ssh#618]
Found the error. The Add-On-Fields are not compatible with iOS/MacOS Safari and WebKit (which is used in the Companian App).

I had to use Windows with Chrome/Firefox to see the fields and enter them.

This should be fixed. It’s definitely an bug/issue.

_Originally posted by @superpower10 in https://github.com/hassio-addons/addon-ssh/issues/535#issuecomment-1501646518_

**Comment by lpw** [comment]
Not sure why this issue was closed.  After new install of latest home-assistant and this addon, same issu - 502 Bad Gateway.  Adding password to fix also fails, silently.  Thanks to @superpower10 for their comment I was able to save and restart under Safari and all's well.

**Comment by frenck** [comment]
Please report this issue with the Home Assistant frontend project. This is not something an add-on can change or improve on.

../Frenck
