### ISSUE TITLE
Copy does not work anymore in Chrome on Win11

### ISSUE THREAD

**Issue by bortek** [hassio-addons/addon-ssh#624]
# Problem/Motivation

Copy in the HASS terminal not working

## Expected behavior

This has worked for about 2 weeks ago. 

I am on Win11 and latest Chrome , latest Hass core-2023.10.2
Advanced SSH & Web Terminal Current version: 15.1.0 (Changelog)

## Actual behavior

Selecting with SHIFT key selects text in GREY color  but nothing is comin into the clipboard. I think previously when it worked, when releasing SHIFT key there was a sort of scissors icon showing. This is no longer the case.

I tried to enable clipboard on unsecure sites in Chrome extensions, also tried adding the URL of the site to allow content on non https sites but it still does not work.

## Steps to reproduce

SHIFT select the text

## Proposed changes

You tell me

**Comment by bortek** [comment]
I have another Hass installation with the SSH add on v 15.0.8 and that one still works. All the other versions (Hass, Core, Supervisor) are the same lates ones. I can see the scissors when copying :) 

Something must have broken with the versions after that one.

**Comment by frenck** [comment]
I don't own a Windows machine (or can access a windows machine) myself. So can't test or debug this.

**Comment by bortek** [comment]
Well that's good. It's nothing one should have.

Do you happen to have a Linux box? I could test that it on the Linux box. Oe do you only have Macs?

**Comment by bortek** [comment]
I just tested it on Ubuntu 23 with XFCE and latest Chrome with the same result. No Copying works.

Could you test make some tests on whatever OS you have available and let us know the results?

**Comment by tjorim** [comment]
Could you provide more info about your install method? The banner in the add-on logs might help.

**Comment by bortek** [comment]
Sure, here it comes.

This is where it still works on Host A
```
-----------------------------------------------------------
 Add-on: Advanced SSH & Web Terminal
 A supercharged SSH & Web Terminal access to your Home Assistant instance
-----------------------------------------------------------
 Add-on version: 15.0.8
 There is an update available for this add-on!
 Latest add-on version: 15.1.0
 Please consider upgrading as soon as possible.
 System: Home Assistant OS 11.0  (amd64 / qemux86-64)
 Home Assistant Core: 2023.10.3
 Home Assistant Supervisor: 2023.10.0
-----------------------------------------------------------

Host B where it no longer works
-----------------------------------------------------------
 Add-on: Advanced SSH & Web Terminal
 A supercharged SSH & Web Terminal access to your Home Assistant instance
-----------------------------------------------------------
 Add-on version: 15.1.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.0  (amd64 / qemux86-64)
 Home Assistant Core: 2023.10.5
 Home Assistant Supervisor: 2023.10.0
-----------------------------------------------------------


Host C where no longer works
-----------------------------------------------------------
 Add-on: Advanced SSH & Web Terminal
 A supercharged SSH & Web Terminal access to your Home Assistant instance
-----------------------------------------------------------
 Add-on version: 15.1.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.5  (amd64 / qemux86-64)
 Home Assistant Core: 2023.10.2
 Home Assistant Supervisor: 2023.10.0
-----------------------------------------------------------

**Comment by sfortis** [comment]
I've the same problem in windows 11/EDGE.

**Comment by amichaelwagner** [comment]
Having the same issue. Windows 11 with Chrome 119.0.6045.160.

**Comment by bortek** [comment]
Anyone know why it has stopped working or any indication of what has broken? Would be glad to troubleshoot and fix if I get some direction where to look.

I dont see any errors in the Debug mode in Chrome though.

**Comment by bortek** [comment]
This is still an issue last time I checked. So let's keep it open till we find a solution.

**Comment by lecourtb** [comment]
> This is still an issue last time I checked. So let's keep it open till we find a solution.

I also confirm with Chrome Version 120.0.6099.111 (64 bits)

**Comment by smoki3** [comment]
also not able to copy anything

**Comment by mspiridakis** [comment]
Same here. Used to work in the past Windows 11. Addon version 17.0.4. Microsoft Edge Version 120.0.2210.144 (Official build) (64-bit)

**Comment by Onl1ne1373** [comment]
AddOn version 17.1.0. Copy Paste only works in the Terminal with middle button click.
But not with Cmd+C, Cmd+V
MacOS with Safari 17.3.

**Comment by bortek** [comment]
middle mouse button is non-existent nowadays.

tested with 17.1.o on Win11 and latest Chrome. Still does not work. Tried all sorts of combination of SHIFT, CTRL, ALT. But version 15.X still works.

**Comment by smoki3** [comment]
Also in MacOS it is not working

**Comment by loopy321** [comment]
Copy stopped working a few months ago for me too.  Addon version 17.1.1
Holding shift key while selecting in terminal used to work (showing weird scissors), but does not anymore.

**Comment by loopy321** [comment]
> tested with 17.1.o on Win11 and latest Chrome. Still does not work. Tried all sorts of combination of SHIFT, CTRL, ALT. But version 15.X still works.
@bortek can you please share how you downgraded to 15.X?

**Comment by amordicus** [comment]
COPY and PASTE doesn't work in web terminal on Mac OS Ventura and Big Sur using HomeAssistant url  nor HA Companion.  But in a web browser (Firefox or Safari) the right mouse button displays the terminal's popup menu underneath the browser's popup menu which makes it extremely difficult to use.

**Comment by sorenisanerd** [comment]
Filed #721 to address this. Until then, you can use "Ctrl-A : set mouse off".
