### ISSUE TITLE
Cannot install version 15.1.0

### ISSUE THREAD

**Issue by flbsoft** [hassio-addons/addon-ssh#627]
# Problem/Motivation
Cannot install version 15.1.0 (also cannot upgrade to 15.0.1 from previous versions)
## Actual behavior
When installing I get the following error: "Can't install ghcr.io/hassio-addons/ssh/aarch64:15.1.0: 500 Server Error for http+docker://localhost/v1.43/images/ghcr.io/hassio-addons/ssh/aarch64:15.1.0/json: Internal Server Error ("readlink /mnt/data/docker/overlay2/l: invalid argument")"
## Proposed changes

**Comment by frenck** [comment]
> readlink /mnt/data/docker/overlay2/l: invalid argument

This is not an add-on issue, but an issue with your system (if you have an SD-card, it could be failing).

Anyways, you can try to fix it by running `ha supervisor repair` in a terminal window 👍 

../Frenck

**Comment by flbsoft** [comment]
Thanks Frenck.

I'll try the command you suggest me and I keep you informed.

Thanks,
Francesco
