### ISSUE TITLE
addon wont start. says passwd not set even though it is

### ISSUE THREAD

**Issue by hunleyd** [hassio-addons/addon-ssh#63]
# Problem/Motivation

Addon will not stay running. Says a password must be set, but one is set. It even tells me 'congrats, passwrd is not in the pwned db'

## Expected behavior

Addon to boot and function

## Actual behavior

Addon starts up, checks passwd in pwned db, says passwd is fine, then tells me no passwd is set and shuts down

## Steps to reproduce

I only noticed this after upgrading hassio to 0.89.1, but now it is 100% reproducible here. Removing and re-adding via the HA ui does not resolve the issue. Log output:

```
INFO: You are running the latest version of this add-on
[cont-init.d] 02-updates.sh: exited 0.
[cont-init.d] 10-requirements.sh: executing...
WARNING: Logging in with a SSH password is security wise, a bad idea!
WARNING: Please, consider using a public/private key pair
INFO: Password is NOT in the Have I Been Pwned database! Nice!
FATAL: You need to set a password!
[cont-init.d] 10-requirements.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing...
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.

 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Comment by frenck** [comment]
@hunleyd 

`FATAL: You need to set a password!`

**Comment by hunleyd** [comment]
Yes, but it *is* set

**Comment by frenck** [comment]
both?

**Comment by hunleyd** [comment]
crap, you're right. my bad. sorry for the noise.

**Comment by frenck** [comment]
Hehe, that is fine! That error message definitely needs more detail!
