### ISSUE TITLE
Terminal does not start after putting in password and save

### ISSUE THREAD

**Issue by marclombardi11** [hassio-addons/addon-ssh#630]
# Problem/Motivation

> Image ghcr.io/hassio-addons/ssh/aarch64:15.1.0 does not exist for addon_a0d7b954_ssh

## Expected behavior

> Terminal would start

## Actual behavior

> error

## Steps to reproduce

> try adding terminal to a fresh install home assistant 2023.11.1

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by ingus16** [comment]
Same, done with fresh install and same error 502 bad gateway. Shocking that not work straight away with fresh install

**Comment by sinclairpaul** [comment]
The error you see means that the image doesn't exist locally when the addon tries to start, which means your system was unable to download/pull it correctly.  The image definitely exists online here <https://github.com/hassio-addons/addon-ssh/pkgs/container/ssh%2Faarch64/137551410?tag=15.1.0> as you can see it has over 65000 downloads.

I would suggest validating your DNS settings, and possibly seeking help on the Home Assistant forums or Discord.
