### ISSUE TITLE
VSCode Remote extensions disappear 

### ISSUE THREAD

**Issue by soloam** [hassio-addons/addon-ssh#635]
# Problem/Motivation

When I use VSCode to access home assistant config by VSCode Remote, if I install extensions, they are installed on the remote machine (home assistant) and this is overwritten when home assistant is updated.

## Expected behavior

It would be nice if we could have the vscode extensions configuration on a folder that is maintained outside of docker, so that its able to restore the extensions when home assistant is updated.

## Actual behavior

On every home assistant update the extensions disappear and must be installed again.

## Steps to reproduce

- configure vscode to use home assistant as a remote server
- install a extension
- update home assistant

## Proposed changes

Allow the vscode extension folder to be persistent across docker container updates.

------

Thank You

**Comment by frenck** [comment]
Good one! that should be fairly easy to do :)
Will add it to my list!

**Comment by soloam** [comment]
That would be great! Tks for the feedback and looking forward to it!

Best regards and thank you for all the time that you spend with this and other things related with HA

**Comment by ds-sebastian** [comment]
This would really help to have the YAML extension persistent when I restart HA after using it 😅

**Comment by frenck** [comment]
Shipped v17.0.0, containing this feature.

Thanks for the suggestion! 👍

**Comment by soloam** [comment]
Thanks for adding this and for all your work and time!

Thank you and Merry Crismistmas

**Comment by frenck** [comment]
You are welcome!

Merry Christmas to you too 🎄
