### ISSUE TITLE
Adding to the VirtualBox image

### ISSUE THREAD

**Issue by rwb196884** [hassio-addons/addon-ssh#638]
I think I installed it but it doesn't work/
Do I need to put for username/password/authorized_keys? What? Where do I get the values from?

I tried changing `hassio:` to the username and password I set up but that doesn't work.

I _am_ clicking `SAVE` but when I go back to the _Configuration_ page the settings have always reverted.

Do I have to make the private key into one line? How?

**Comment by frenck** [comment]
> Do I need to put for username/password/authorized_keys? What? Where do I get the values from?

You decide your username & password. There is nowhere to get them from. You can use an authorized keys in case you like to use your keypair (if you have one).

> I tried changing hassio: to the username and password I set up but that doesn't work.

Not even sure what that means.

> I am clicking SAVE but when I go back to the Configuration page the settings have always reverted.

Sorry, that is not something the add-on provides. If you have issues using the Home Assistant UI, please report such cases with Home Assistant.


> Do I have to make the private key into one line? How?

No, that is not needed.

../Frenck
