### ISSUE TITLE
Web Terminal throwing HTTP 400 error on v4.x

### ISSUE THREAD

**Issue by Hackashaq666** [hassio-addons/addon-ssh#64]
# Problem/Motivation

Cannot open Web Terminal when SSL is enabled.

## Expected behavior

To see the terminal

## Actual behavior

The webpage throws a HTTP 400 error.

## Steps to reproduce

- Install add-on
- Enable SSL
- Open the Web Terminal frontend (e.g., using the "Open Web UI" button).

## Proposed changes

n/a

**Comment by Hackashaq666** [comment]
Just updated the ssh plugin, now cannot log in, getting 400 error. Previous versions have worked without problem for months.  Thank you!

**Comment by Hackashaq666** [comment]
`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 10-permissions: applying... 
[fix-attrs.d] 10-permissions: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: SSH & Web Terminal
 SSH & Web Terminal access to your Home Assistant instance
-----------------------------------------------------------
 Add-on version: 4.0.0
 You are running the latest version of this add-on.
 System: HassOS 2.10  (armv7 / raspberrypi3)
 Home Assistant version: 0.90.0b4
 Supervisor version: 148
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in e.g, GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 10-requirements.sh: executing... 
[16:57:35] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[16:57:38] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[16:57:40] WARNING: 
[16:57:40] WARNING: Logging in with a SSH password is security wise, a bad idea!
[16:57:40] WARNING: Please, consider using a public/private key pair.
[16:57:40] WARNING: What is this? https://kb.iu.edu/d/aews
[16:57:40] WARNING: 
[cont-init.d] 10-requirements.sh: exited 0.
[cont-init.d] 20-user.sh: executing... 
[cont-init.d] 20-user.sh: exited 0.
[cont-init.d] 30-link-common-dirs.sh: executing... 
[cont-init.d] 30-link-common-dirs.sh: exited 0.
[cont-init.d] 40-zsh.sh: executing... 
[cont-init.d] 40-zsh.sh: exited 0.
[cont-init.d] 50-ssh-config.sh: executing... 
[cont-init.d] 50-ssh-config.sh: exited 0.
[cont-init.d] 51-host-keys.sh: executing... 
[cont-init.d] 51-host-keys.sh: exited 0.
[cont-init.d] 52-authorized-keys.sh: executing... 
[cont-init.d] 52-authorized-keys.sh: exited 0.
[cont-init.d] 53-user-ssh-folder.sh: executing... 
[cont-init.d] 53-user-ssh-folder.sh: exited 0.
[cont-init.d] 54-share-sessions.sh: executing... 
[cont-init.d] 54-share-sessions.sh: exited 0.
[cont-init.d] 60-docker.sh: executing... 
true[cont-init.d] 60-docker.sh: exited 0.
[cont-init.d] 80-user-packages.sh: executing... 
[cont-init.d] 80-user-packages.sh: exited 0.
[cont-init.d] 81-user-scripts.sh: executing... 
[cont-init.d] 81-user-scripts.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[16:57:46] INFO: Starting the SSH daemon...
[16:57:46] INFO: Starting the ttyd daemon...
Server listening on 0.0.0.0 port 22.
Server listening on :: port 22.
[2019/03/17 16:57:47:6849] ERR: lws_tls_server_vhost_backend_init: SSL_CTX_load_verify_locations unhappy
[2019/03/17 16:57:47:7357] ERR: Unable to load SSL Client certs file from  -- client ssl isn't going to work`

**Comment by frenck** [comment]
Got a second report on the community forum:
https://community.home-assistant.io/t/community-hass-io-add-on-ssh-web-terminal/33820/141?u=frenck

**Comment by frenck** [comment]
Confirmed the issue on my end. Will pick this up with high priority.

**Comment by frenck** [comment]
Just released v4.0.2 of the add-on, fixing this issue.
