### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by Emerica** [hassio-addons/addon-ssh#643]
# Problem/Motivation
![image](https://github.com/hassio-addons/addon-ssh/assets/1464656/81bd3959-2dc4-4bc5-b8ee-b076e165a1b4)
![image](https://github.com/hassio-addons/addon-ssh/assets/1464656/44f151fc-efa7-4599-9822-b7adc3468152)
![image](https://github.com/hassio-addons/addon-ssh/assets/1464656/eec215a0-6e2c-43b6-beb9-8f290b1a9b76)

> (Why the issue was filed)
Addon Runs  But Doesn't Work
## Expected behavior

> (What you expected to happen)
Working Terminal
## Actual behavior

> (What actually happened)
502 Bad Gateway
## Steps to reproduce

Install Addon
> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
Please click the one that says Log:

![image](https://github.com/hassio-addons/addon-ssh/assets/24625998/a3121896-8676-4e1f-91e9-401735e8dbf5)

**Comment by Emerica** [comment]
That sure shows a bit more info,  maybe a setup config should run through setting keys or passwords or at least alert the user, was hung up there wanting config information which I had assumed should work with defaults.
