### ISSUE TITLE
SFTP doesn't work

### ISSUE THREAD

**Issue by DoubleBoba** [hassio-addons/addon-ssh#646]
# Problem/Motivation

SFTP crashes the addon

## Expected behavior

I should be able to connect at least

## Actual behavior

Addon crashes

## Steps to reproduce

Enable SFTP and see it crashes

I don't know how to get logs yet, but will post them here too as soon as I find them.

**Comment by sinclairpaul** [comment]
![image](https://github.com/hassio-addons/addon-ssh/assets/24625998/61880091-aa38-4133-8740-82e8fe55d759)


I would also suggest looking at the Documentation tab

**Comment by DoubleBoba** [comment]
@sinclairpaul thanks, i will check
