### ISSUE TITLE
Can't set or save password in config - 502 Gateway Error

### ISSUE THREAD

**Issue by Tracchy** [hassio-addons/addon-ssh#647]
# Problem/Motivation

Attempting to set a password or username in the config will not save.  Hitting save at the bottom does nothing.  Changing tabs at the top to start/stop/restart the service, returns the same message in the logs about needing to set a password.  This is the HA .OVA package on ESXi.  I've tried Edge, Chrome, and Firefox.

## Expected behavior

Save the password.

## Actual behavior

Doesn't save the password.

## Steps to reproduce

Attempt to configure.

## Proposed changes

Why is this very important step hidden away and not a pop-up or reminder banner?

############ Log Below #####################

-----------------------------------------------------------
 Add-on: Advanced SSH & Web Terminal
 A supercharged SSH & Web Terminal access to your Home Assistant instance
-----------------------------------------------------------
 Add-on version: 16.0.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.1  (amd64 / qemux86-64)
 Home Assistant Core: 2023.11.3
 Home Assistant Supervisor: 2023.11.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-user: starting
s6-rc: info: service init-ssh: starting
s6-rc: info: service init-mysql: starting
s6-rc: info: service init-mosquitto: starting
s6-rc: info: service init-docker: starting
s6-rc: info: service init-docker successfully started
s6-rc: info: service init-mosquitto successfully started
s6-rc: info: service init-mysql successfully started
[14:00:12] NOTICE: Session sharing has been disabled!
s6-rc: info: service init-user successfully started
s6-rc: info: service ttyd: starting
s6-rc: info: service ttyd successfully started
[14:00:12] INFO: Starting the ttyd daemon...
[14:00:12] FATAL: 
[14:00:12] FATAL: Configuration of this add-on is incomplete.
[14:00:12] FATAL: 
[14:00:12] FATAL: Please be sure to set at least an SSH password
[14:00:12] FATAL: or at least one authorized key!
[14:00:12] FATAL: 
[14:00:12] FATAL: You can configure this using the "ssh.password"
[14:00:12] FATAL: or the "ssh.authorized_keys" option in the
[14:00:12] FATAL: add-on configuration.
[14:00:12] FATAL: 
s6-rc: warning: unable to start service init-ssh: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service init-mysql: stopping
s6-rc: info: service init-mosquitto: stopping
s6-rc: info: service init-docker: stopping
s6-rc: info: service ttyd: stopping
s6-rc: info: service init-mysql successfully stopped
s6-rc: info: service init-mosquitto successfully stopped
s6-rc: info: service init-docker successfully stopped
[14:00:12] INFO: Service ttyd exited with code 256 (by signal 15)
s6-rc: info: service ttyd successfully stopped
s6-rc: info: service init-user: stopping
s6-rc: info: service init-user successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by frenck** [comment]
> Attempting to set a password or username in the config will not save. Hitting save at the bottom does nothing. Changing tabs at the top to start/stop/restart the service, returns the same message in the logs about needing to set a password.

Sorry, that is not an add-on issue, but an Home Assistant issue. Please report the issue with the Home Assistant project instead.

../Frenck
