### ISSUE TITLE
Not connecting

### ISSUE THREAD

**Issue by doobes** [hassio-addons/addon-ssh#651]
When starting, first, I get this, even though it's already running.

![start](https://github.com/hassio-addons/addon-ssh/assets/23409761/0569d527-dcdb-4d41-9274-e2e71bdac479)

Then after clicking start, I get this:

![bad](https://github.com/hassio-addons/addon-ssh/assets/23409761/d9ad475f-b206-43c4-b278-b121dd329f92)

Putty also refuses to connect.

Any idea what's wrong?

Thank

Chris

**Comment by sinclairpaul** [comment]
Check the Log and Documentation tabs

**Comment by doobes** [comment]
Got it thanks.

Needed to set a password and then reboot HA
