### ISSUE TITLE
SSH addon failed to start on Raspberry PI

### ISSUE THREAD

**Issue by robinpecha** [hassio-addons/addon-ssh#654]
# Problem/Motivation

> Doesnt start on HAOS installed on Raspberry PI 3B 1GB RAM (3GB free storage), HAOS version  2023.11.3 

## Expected behavior

> ssh access

## Actual behavior

> SSH access reports Bad Gateway
![image](https://github.com/hassio-addons/addon-ssh/assets/9316280/3527822d-a275-45d0-80f5-a40f57685a88)

## Steps to reproduce

> Open Settings > addons > install this addon > start, Then after while trying access it and error shows up. Trying with and without privileged access. After rebooting whole HAOS, etc

**Comment by frenck** [comment]
Anything in the logs?

**Comment by robinpecha** [comment]
![sxpra](https://github.com/hassio-addons/addon-ssh/assets/9316280/b78b0cae-d240-4fc1-a73e-10a761474123)

Problem solved.

Maybe is worthy, for clever guys like me, mention this setup step with UPPERCASE BILD LETTERS somewhere high in descriptions.
Sorry for wasting your time and thank you for your help.
Btw, excelent tool, this should be native part of haos.
