### ISSUE TITLE
Unable to update Advanced SSH

### ISSUE THREAD

**Issue by lcbester** [hassio-addons/addon-ssh#657]
# Problem/Motivation
I suffered a power failure while updating Advanced SSH to 17.0.0.

After system restarted, I tried the update again, it failed again.

I removed 16.0.0.2 and restarted HA
I then tried to do a fresh install of Advanced SSH, and it failed.

> (Why the issue was filed)

Unable to update, and now install

## Expected behavior

> (What you expected to happen)

I expected the install to work at least.

## Actual behavior

Can't install ghcr.io/hassio-addons/ssh/aarch64:17.0.0: 404 Client Error for http+docker://localhost/v1.43/images/ghcr.io/hassio-addons/ssh/aarch64:17.0.0/json: Not Found ("No such image: ghcr.io/hassio-addons/ssh/aarch64:17.0.0")

> (What actually happened)

## Steps to reproduce

Unsure

> (How can someone else make/see it happen)

Try a power failure while updating, I am not sure it is related though.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by lcbester** [comment]
By restoring the backup prior to the upgrade attempt, I managed to get the previous version running again.  

I will monitor here to see if a solution is found or otherwise I will try again in a week or so.

**Comment by frenck** [comment]
> Can't install ghcr.io/hassio-addons/ssh/aarch64:17.0.0: 404 Client Error for http+docker://localhost/v1.43/images/ghcr.io/hassio-addons/ssh/aarch64:17.0.0/json: Not Found ("No such image: ghcr.io/hassio-addons/ssh/aarch64:17.0.0")

This is not an add-on error, but an issue with Home Assistant. 

You could try running `ha supervisor repair` to address it. If the error remains, please report an issue with the Home Assistant Supervisor project; as from an add-on perspective, there is nothing I can do.

../Frenck

**Comment by lcbester** [comment]
Thank you Frenck

I have already tried running ha supervisor repair.  Unfortunately it says nothing to repair.

For the time being I will remain on version, 16, it is still great and do what I need it to do.
