### ISSUE TITLE
Cannot Copy And Paste Using iOS HA App

### ISSUE THREAD

**Issue by LordNex** [hassio-addons/addon-ssh#658]
I cannot turn on the add on, have a script in my clipboard of my iPhone, and paste it into the built in add on inside the iOS app. It's been this way ever since I've used it and that's been several years. I'm not running in protected mode or anything and can copy and paste in other parts of Home Assistant fine. 

Currently running version 2023.12.1

**Comment by LordNex** [comment]
Still an issue

**Comment by frenck** [comment]
Yup, that won't work.
Won't fix either, this isn't gonna fly.

**Comment by LordNex** [comment]
A simple copy and paste can't be done?  Works everywhere else. Is there a reason why you won't even try?

It makes it really hard when there is a long string of code I need to drop in and have to try and keep switching back and forth between windows. Usually resulting in the client crashing.
