### ISSUE TITLE
Can't install addon on hass.io

### ISSUE THREAD

**Issue by bahuma20** [hassio-addons/addon-ssh#66]
# Problem/Motivation

After the update to hassos 2.11, when trying to install the addon via the addon store it can't be installed.

## Expected behavior

It should install the addon.

## Actual behavior

The addon isn't installed, in the system logs you see:
`19-03-26 18:34:50 ERROR (SyncWorker_2) [hassio.docker.interface] Can't install homeassistant/armv7-addon-ssh:5.3 -> 500 Server Error: Internal Server Error ("layer does not exist").`

## Steps to reproduce

Install hass.io 0.90.1 on hassos 2.11, go to the addon store, find the ssh addon, click on install

**Comment by frenck** [comment]
Hi there,

You've mixed up the community SSH & Web Terminal add-on with the core add-on.

`homeassistant/armv7-addon-ssh:5.3` -> Indicates your are trying to install the Core SSH add-on. Please report this issue with Home Assistant.

Thanks.
