### ISSUE TITLE
Provide a more helpful hint than "502 Bad Gateway"

### ISSUE THREAD

**Issue by GfEW** [hassio-addons/addon-ssh#662]
**The problem**

After freshly installing and starting up the Advanced SSH and WebTerminal add-on, the "Open Web UI" link leads to a "502 Bad Gateway" message rather than to the expected web terminal. There is a popup asking "The add-on seems to not be ready, it might still be starting, Do you want to try again?" 

I've tried both answers ("no" or "retry"), to no avail, and spent nearly an hour trying to resolve the issue, restarting the add-on with various changes of configurations, web research on the topic, etc., to finally only find out this:

_Originally posted by @robytudd in https://github.com/hassio-addons/addon-ssh/issues/370#issuecomment-1023544950_
> turns out leaving it for 5 mins works wonders! 
Resolved itself

Hm OK. Waiting ... 15 minutes, still 502! Only in the course of more research, I learned that - although apparently, the addon had been installed -, there was one step in the installation guide (step 3) asking to 
> Configure the username and password/authorized_keys options.

However, at no point in the installation procedure I was asked for username or password/keys! What a weird discrepancy. Perhaps the guide was outdated? Or did the installation procedure skip username/password/keys entry, for some reason?

**Note**

I am aware these troubles may appear benign if you already know how to get around them. You might even think of them as legitimate compounds of the overall learning curve. However, I'm confident the problems I've managed to understand and solve in these 90 minutes could easily be understood and solved in 5 minutes instead. Hence I'm providing this feedback (regardless of me obviously being none of the potential profiteers of the suggested improvement anymore), to allow future new users to waste less time on their initial learning curve than I have on mine.

**Suggested solution**

As long as the web terminal is not ready yet, the add-on should provide a more comprehensive error message, clearly informing the user that 
1. addon-ssh needs to be configured in the configure tab of the add-on page _prior_ to using the web terminal
2. the readily configured web terminal then may need several (up to 10?) minutes to get up and running

Such an improved message could save first time users lots of testing and elaborate research (multiplied by the number of affected users) that are actually pointless if "configure, sit and keep waiting" suffices for the web terminal to start up.

**Comment by frenck** [comment]
This is not in the control of the addon.

Home Assistant will display an 502 when it isn't started yet.

Feel free to post a feature request at the Home Assistant project.

**Comment by GfEW** [comment]
Thanks for the pointer - and sorry to bother you if there's nothing you can do about it.

Just to make sure I'm understanding you correctly:

1. There is no way for an add-on to provide a custom "waiting/loading" info page that is shown instead of the 502 before the main popup webUI has finished starting up.
2. The popup message currently reading "The add-on seems to not be ready, it might still be starting, Do you want to try again?" is not specified/modified by the add-on but by Home Assistent alone.

Are both statements correct?

**Comment by Xinnony** [comment]
Same for me, I lost a little time but thanks to you I was able to access it, thank you @GfEW!

**Comment by GfEW** [comment]
> Are these two statements correct?

Assuming "yes", I've posted the issue there: https://github.com/home-assistant/frontend/discussions/19147 . 

@frenck
Should my assumption be wrong, please let me know.

**Comment by frenck** [comment]
Again, you are emit in the correct place, this is not a scope the add-on cornrows.
