### ISSUE TITLE
Feature Request: Ability to limit what IP/interfaces this listens on

### ISSUE THREAD

**Issue by Gillingham** [hassio-addons/addon-ssh#664]
# Problem/Motivation

I have HA listening on both my normal LAN and the IoT LAN just because some multicast stuff that IoT things tend to use doesnt play nice with ubiquiti. So I would like to be able to limit the ssh binding to only be on my primary LAN interface or address and not the one exposed to the IoT LAN.

## Expected behavior

There was an option to tell the addon to only bind to specific interfaces (or IPs)

## Actual behavior

Binds to everything

## Steps to reproduce

Create two interfaces on an HA system, then start the adddon.

## Proposed changes

A new option to tell the addon to only bind to specific interfaces (or IPs)

**Comment by Gillingham** [comment]
Bump to keep open

**Comment by frenck** [comment]
While I understand your request/use case, I've not seen this request before. The need/demand for it is thus really small.

For now, I'm not planning on adding this. Nevertheless, thanks for your suggestion 👍 

../Frenck
