### ISSUE TITLE
trouble starting addon

### ISSUE THREAD

**Issue by penguinpatrol** [hassio-addons/addon-ssh#665]
# Problem/Motivation

the addon refuses to start any time i try to start it up - if i go into the tab it also tries to start it up to no avail

## Expected behavior

it to start

## Actual behavior

it didnt start

**Comment by frenck** [comment]
Anything in the log?

**Comment by penguinpatrol** [comment]
sorry im new to this where would that be? can't find any information in the logbook on the side bar

**Comment by frenck** [comment]
Navigate to the configuration panel -> add-ons -> select the SSH add-on -> logs tab.

**Comment by penguinpatrol** [comment]
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: Advanced SSH & Web Terminal
 A supercharged SSH & Web Terminal access to your Home Assistant instance
-----------------------------------------------------------
 Add-on version: 17.0.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.2  (aarch64 / green)
 Home Assistant Core: 2023.12.3
 Home Assistant Supervisor: 2023.12.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-user: starting
s6-rc: info: service init-ssh: starting
s6-rc: info: service init-mysql: starting
s6-rc: info: service init-mosquitto: starting
s6-rc: info: service init-docker: starting
s6-rc: info: service init-mysql successfully started
s6-rc: info: service init-mosquitto successfully started
s6-rc: info: service init-docker successfully started
[07:00:28] NOTICE: Session sharing has been disabled!
[07:00:28] FATAL: 
[07:00:28] FATAL: Configuration of this add-on is incomplete.
[07:00:28] FATAL: 
[07:00:28] FATAL: Please be sure to set at least an SSH password
[07:00:28] FATAL: or at least one authorized key!
[07:00:28] FATAL: 
[07:00:28] FATAL: You can configure this using the "ssh.password"
[07:00:28] FATAL: or the "ssh.authorized_keys" option in the
[07:00:28] FATAL: add-on configuration.
[07:00:28] FATAL: 
s6-rc: warning: unable to start service init-ssh: command exited 1
s6-rc: info: service init-user successfully started
s6-rc: info: service ttyd: starting
s6-rc: info: service ttyd successfully started
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service init-mysql: stopping
s6-rc: info: service init-mosquitto: stopping
s6-rc: info: service init-docker: stopping
s6-rc: info: service ttyd: stopping
s6-rc: info: service init-mysql successfully stopped
s6-rc: info: service init-docker successfully stopped
s6-rc: info: service init-mosquitto successfully stopped
[07:00:28] INFO: Service ttyd exited with code 256 (by signal 15)
s6-rc: info: service ttyd successfully stopped
s6-rc: info: service init-user: stopping
s6-rc: info: service init-user successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

sorry for the lump text but this is all of it

**Comment by frenck** [comment]
The issue and solution is in the above logs you pasted. Additionally it means you didn't read the add-on installation instructions.

Please read both.

../Frenck
