### ISSUE TITLE
!secrets doesn't work to config password

### ISSUE THREAD

**Issue by crug80** [hassio-addons/addon-ssh#668]
# Problem/Motivation

> I saw a similar old [issue ](https://github.com/hassio-addons/addon-ssh/issues/318)closed, but the problem I see it seems different. 
   The addon, in fact, won't save the config when I use !secret keyword. 

## Expected behavior

> correctly manage !secret keyword to avoid to store plain password in addon config

## Actual behavior

> Error message: `Impossible to save the config of the addon, Missing option 'ssh' in root in Advanced SSH & Web Terminal (a0d7b954_ssh). Got {'zsh': False, 'share_sessions': False, 'packages': [], 'init_commands': [], 'log_level': 'info'}`

## Steps to reproduce

> configure SSH as the following: 
  `username: myNick
  password: !secret pswd_ssh
  authorized_keys: []
  sftp: false
  compatibility_mode: false
  allow_agent_forwarding: false
  allow_remote_port_forwarding: false
  allow_tcp_forwarding: false
  `

## Proposed changes

>

**Comment by frenck** [comment]
As also written in the issue you've linked:

Secrets are handled by the Home Assistant Supervisor, not the add-on.

If you encounter issues with the use of them, please report the issue with the Home Assistant project. From an add-on perspective, there is not much we can do.

../Frenck

**Comment by crug80** [comment]
Thanks Frenck. I though that it was an error of the "saving procedure" of the configuration file of the addon.

**Comment by frenck** [comment]
There is no such thing as a "saving procedure" of the add-on.

**Comment by crug80** [comment]
> There is no such thing as a "saving procedure" of the add-on.

Understood. It is the supervisor who is saving. Sorry.
