### ISSUE TITLE
Feature Request: Set permission to access services/mqtt in Hassio API

### ISSUE THREAD

**Issue by gregod** [hassio-addons/addon-ssh#67]
I'm proposing to add a "services mqtt" permission to the config. Currently the script has full host access but is not allowed to access the services endpoint of the hassio api.

Doing so would help with debugging scripts that rely on this endpoint, especially as this service permission seems not to be documented very extensively.

**Comment by frenck** [comment]
There is no such permission...

It already has the max level permission it needs. Furthermore, the services & discovery API endpoint are available freely.

**Comment by gregod** [comment]
`curl hassio/services/mqtt -H "X-HASSIO-KEY: $HASSIO_TOKEN"` in the terminal
results in  `{"result": "error", "message" : "No access to mqtt service!"}`

A permission check seems to be here: https://github.com/home-assistant/hassio/blob/e5451973bd47bd5ff31f2aba8836e82f62911af9/hassio/api/services.py#L68.

Which references the service property of an addon:

services | list | no | A list of services they will be provided or consumed with this Add-on. Format is service:function and functions are: provide (this add-on can provide this service), want (this add-on can use this service) or need (this add-on need this service to work correctly).
-- | -- | -- | --

I cant get the addon to build locally right now to verify, but looking at the source giving a property of 
`services : ["mqtt:want"]` would result in the necessary access rights.
