### ISSUE TITLE
Documentation feedback

### ISSUE THREAD

**Issue by morrismichaelc** [hassio-addons/addon-ssh#671]
# Problem/Motivation

> Experienced linux admin, but new to HA. First thing I did was install  this add-on. (THANK YOU :) But being new to HA, I did not notice the "Configuration" tab at the top of the info page.

## Expected behavior

> I expected there to be an input field for username/password in the Info area, along with the toggles like "Start on boot", etc. Failing that, I though perhaps the initial SSH connection would ask for user info...

## Actual behavior

> I stumbled around [quite] a bit  until I noticed the "Configuration" option at the top of the page.

## Steps to reproduce

> This is as intended, but may I suggested:

## Proposed changes

> At the end of step #2 under Installation, please add "found on the "Configuration" tab, above" to yield:

> 2. Configure the username and password/authorized_keys options. These are in the HA "Settings" section, on the "Configuration" tab at the top of the Advanced SSH & Web Terminal info page.

> I've seen other complaints of people who couldn't find this setting, so it seems a trivial effort to reduce nuisance requests for assistance :) 

> Just my 2 cents :)

**Comment by sinclairpaul** [comment]
Minor Pull Requests (like docs) are pretty easy to do in Github, would suggest just submitting a PR

**Comment by morrismichaelc** [comment]
Ahhh.... today is as good a day as any to learn how to do that :) 

Thanks for the guidance, 

MikeM 

On 2024-01-06 18:08, Paul Sinclair wrote:

> Minor Pull Requests (like docs) are pretty easy to do in Github, would suggest just submitting a PR 
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
> You are receiving this because you authored the thread.Message ID: ***@***.***>
 

Links:
------
[1]
https://github.com/hassio-addons/addon-ssh/issues/671#issuecomment-1879914475
[2]

**Comment by sinclairpaul** [comment]
As a hint :)

![image](https://github.com/hassio-addons/addon-ssh/assets/24625998/4e55a2dc-93be-4fb6-84ae-4687fec1b608)

**Comment by morrismichaelc** [comment]
Thank you sir! 

On 2024-01-06 18:39, Paul Sinclair wrote:

> As a hint :) 
> 
> image.png (view on web) [1] 
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].
> You are receiving this because you authored the thread.Message ID: ***@***.***>
 

Links:
------
[1]
https://github.com/hassio-addons/addon-ssh/assets/24625998/4e55a2dc-93be-4fb6-84ae-4687fec1b608
[2]
https://github.com/hassio-addons/addon-ssh/issues/671#issuecomment-1879919368
[3]
