### ISSUE TITLE
fail to start the Advanced SSH & Web Terminal

### ISSUE THREAD

**Issue by barovar** [hassio-addons/addon-ssh#678]
# Problem/Motivation

Failed to start add-on

## Expected behavior

to just start

## Actual behavior

I get this mesage when press START:

Can't create container from addon_a0d7b954_ssh: 400 Client Error for http+docker://localhost/v1.43/containers/create?name=addon_a0d7b954_ssh: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /var/log/journal")

## Steps to reproduce

not sure, but all is set in the configurations section, password and so on, tried different ports too, no help, by the way there is nothing in the LOG as by the looks of it the application just cant start

## Proposed changes

not sure

**Comment by sinclairpaul** [comment]
It's not an addon issue, what OS are you running?

**Comment by barovar** [comment]
hi, this is the OS

Linux Debian 5.10.100-g304c70ad206a-dirty #82 SMP Thu Nov 16 13:13:14 CST 2023 aarch64

**Comment by barovar** [comment]
> It's not an addon issue, what OS are you running?

hi, this is the OS

Linux Debian 5.10.100-g304c70ad206a-dirty https://github.com/hassio-addons/addon-ssh/issues/82 SMP Thu Nov 16 13:13:14 CST 2023 aarch64

**Comment by sinclairpaul** [comment]
I was trying to find out if this is a Supervised or HAOS install, I'm going to guess it's supervised, in which case I would suggest that you double check the documentation for installing.

If it is indeed a HAOS install then you would need to seek help with the Home Assistant project, as this is not an issue with the addon.

**Comment by barovar** [comment]
Ok, thanks for the help. I believe it is a supervised version. Almost sure it is not HAOS.

**Comment by churchofnoise** [comment]
> Ok, thanks for the help. I believe it is a supervised version. Almost sure it is not HAOS.

Did you find a solution for this? Facing the same issue on ha supervised on debian

**Comment by barovar** [comment]
Not unfortunately. WIll be looking at installing the OS again on the device i have.
