### ISSUE TITLE
Addon says it is stopped, but it is actually running (Wrong status reporting)

### ISSUE THREAD

**Issue by dodancs** [hassio-addons/addon-ssh#679]
# Problem/Motivation

When I press "Start", the Docker container is created and started and I can successfully connect to HA via SSH. But, the addon still shows that it is "Stopped" in the Addon management.

This causes multiple issues:
- Web terminal cannot be accessed - it always just shows the popup that the addon must be started before, then if you press start it just hangs, and if you press no, then you get redirected away.
- After config is changed, you cannot apply it
- If you press "Start" again, it just spits out in the supervisor logs that the container is already running and it won't start it again. So no restarts of the container/addon.

The addon is running, don't let the picture deceive you:
![image](https://github.com/hassio-addons/addon-ssh/assets/1970811/4ae6acc7-8bcc-4a23-874c-bcaf63bacf28)

## Expected behavior

I press "Start", the Docker container starts, and I get a green light and am able to access the web terminal and so on.

## Actual behavior

I press "Start", the Docker container starts, and I get a red light and am not able to access the web terminal.

## Steps to reproduce

- Install the addon
- Configure it
- Press start

## Proposed changes

- Fix it plz?

## Logs

```
24-01-22 20:00:22 INFO (MainThread) [supervisor.addons.addon] Creating Home Assistant add-on data folder /data/addons/data/a0d7b954_ssh
24-01-22 20:00:22 INFO (MainThread) [supervisor.docker.interface] Downloading docker image ghcr.io/hassio-addons/ssh/amd64 with tag 17.0.4.
24-01-22 20:00:41 INFO (MainThread) [supervisor.addons.manager] Add-on 'a0d7b954_ssh' successfully installed
24-01-22 19:48:45 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/ssh/amd64 with version 17.0.4
24-01-22 19:50:45 WARNING (MainThread) [supervisor.addons.addon] Timeout while waiting for addon Advanced SSH & Web Terminal to start, took more than 120 seconds
24-01-22 20:01:51 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from a0d7b954_ssh
24-01-22 20:01:51 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from a0d7b954_ssh
24-01-22 20:01:51 INFO (MainThread) [supervisor.api.middleware.security] /host/info access from a0d7b954_ssh
24-01-22 20:01:51 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from a0d7b954_ssh
24-01-22 20:02:26 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from a0d7b954_ssh
24-01-22 20:02:26 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from a0d7b954_ssh
24-01-22 20:02:26 INFO (MainThread) [supervisor.api.middleware.security] /host/info access from a0d7b954_ssh
24-01-22 20:02:26 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from a0d7b954_ssh
24-01-22 20:02:51 WARNING (MainThread) [supervisor.docker.addon] Advanced SSH & Web Terminal running with disabled protected mode!
```

**Comment by frenck** [comment]
Hi there @dodancs 👋 

Unfortunately, this is not an add-on issue, but an issue with the Home Assistant Supervisor itself. This is not something in control of the add-on.

Please report it with the issue tracker of the Home Assistant Supervisor project instead.

Thanks! 👍 

../Frenck
