### ISSUE TITLE
compatibility , what changed?

### ISSUE THREAD

**Issue by gnkarn** [hassio-addons/addon-ssh#68]
# Problem/Motivation
starting this week , i receive this message 
SSH & Web Terminal 5.0.0 is available
You are currently running version 4.1.0
This update is no longer compatible with your system.

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by rabbadab** [comment]
Also got that one on my hassos virtualbox machine and also on node red addon.

**Comment by rabbadab** [comment]
So I sis some digging and I was just running HA 0.91.1 so not the latest latest and after an update to 0.91.3 it all worked to update. Maybe should say something int he changelog that 0.9.3 is required to update the addon?

**Comment by frenck** [comment]
@rabbadab IMHO that would be a nice improvement to the Hass.io panel, since it is a requirement in the metadata. But yes, it needs at least Home Assistant 0.91.3.
