### ISSUE TITLE
bad gateway 502

### ISSUE THREAD

**Issue by McFcologne** [hassio-addons/addon-ssh#684]
# Problem/Motivation

It is not running. It only throws bad gateway 502

## Expected behavior

expected the plugin to work

## Actual behavior

see above

## Steps to reproduce

install it, run it

## Proposed changes

i have no idea

**Comment by frenck** [comment]
Anything in the logs?

../Frenck

**Comment by pebie** [comment]
Same issue,
@frenck i've got no log

**Comment by frenck** [comment]
@pebie if there are no logs, you haven't started it or something else is wrong. If the add-on did even an mild attempt to start, it would have had logs. 

So, if you really have no logs, your issue isn't add-on related.

../Frenck

**Comment by Dan-Ross** [comment]
Had this issue as well on a fresh install of HAOS and this add on

The Logs tab of the Add-on config say this on a boot. Try setting these and seeing if the issue resolves.

[10:59:43] FATAL: 
[10:59:43] FATAL: Configuration of this add-on is incomplete.
[10:59:43] FATAL: 
[10:59:43] FATAL: Please be sure to set at least an SSH password
[10:59:43] FATAL: or at least one authorized key!
[10:59:43] FATAL: 
[10:59:43] FATAL: You can configure this using the "ssh.password"
[10:59:43] FATAL: or the "ssh.authorized_keys" option in the
[10:59:43] FATAL: add-on configuration.

@McFcologne @pebie

**Comment by frenck** [comment]
That exactly states what to do. Also, if you run into this, it also means you didn't read the install instructions of the add-on 🤷

**Comment by Dan-Ross** [comment]
100%, but being brand new to HAOS, I didn't know where to find the logs initially. Following the steps in the config fixed the issue. I shared the above to try to help other users who may not have knowledge or experience on how to view logs or configs like I did.

**Comment by frenck** [comment]
You wouldn't need logs if you read the installation instructions?

**Comment by Dan-Ross** [comment]
Hey man, was just trying to help out some users who were struggling with the install like I did and give some guidance that might help them (and maybe future users) solve the issue. 

Us users are imperfect creatures and won't get it right 100% of the time. Considering there are several reports([1,](https://github.com/hassio-addons/addon-ssh/issues/684) [2,](https://github.com/hassio-addons/addon-ssh/issues/667) [3,](https://github.com/hassio-addons/addon-ssh/issues/643) [4,](https://github.com/hassio-addons/addon-ssh/issues/662))  in a relatively short time frame for this issue, perhaps it might be worth copying the snippet of the initial setup docs for that startup config to the Readme that everyone hits when finding the addon instead of it only existing in a link that is easy to miss? Apparently, lots of us as missing it and you must be tired of asking "Anything in the logs?" by now.

If you're into that idea, I can figure out how to make a PR to edit the readme to help out future users.

**Comment by frenck** [comment]
> Us users are imperfect creatures and won't get it right 100% of the time

I can't help if they don't read 🤷 

> erhaps it might be worth copying the snippet of the initial setup docs for that startup config to the Readme that everyone hits when finding the addon instead of it only existing in a link that is easy to miss?

It is listed directly inside Home Assistant. The main page links to the documentation directly as well.

Even if they have issues, that can happen, sure. They A) don't take a moment to read or find documentation, instead, they create an issue (without looking at past issues).

Lucky I've also added logs to also provide information on what went wrong... which many don't see either...

Like... 🤷 

I'm not planning on doing more than this. If all of the above doesn't help someone, than IMHO, this is maybe not for them.

> Apparently, lots of us as missing it and you must be tired of asking "Anything in the logs?" by now.

No, not really to be honest, happy to help.

> If you're into that idea, I can figure out how to make a PR to edit the readme to help out future users.

There is nothing to add? See above.

../Frenck

**Comment by geerlingguy** [comment]
(Just wanted to drop a note that I didn't realize I had to do any extra configuration with the addon either — maybe having a 'Quick Start Guide' that appears in the readme / docs section that appears directly within the HA Addons UI would be helpful, basically say "Install this Add-on" then step two "Click the Configuration tab and add a password or authorized key".)

**Comment by kupietools** [comment]
Developer: thank you for creating and sharing this much-needed tool, but, respectfully, you're displaying a really terrible attitude here. The documentation, configuration tab, and logs tab are all much harder for a newbie to find than you seem to believe they are, they're very easily overlooked by someone unfamiliar with community add-ins or who rarely does back-end work on their HA instance, and, when we do find the documentation (which can be found here in this repo without even realizing there's links at the top of the page in HA, making you totally confused as to what it's talking about with "logs" and "configuration" and "tabs"), it is extremely vague. Much clearer information is needed. I'm a software engineer and web developer and even I had a lot of trouble working out what was actually needed from the documentation and this issue thread. A few sentences of clear explanation (sometimes known the biz as "good documentation") would be much more helpful than the above load of condescension.  

## For those here with this problem, here is the "quickstart" documentation this package is missing:

1.) After install, the tabs for the documentation, configuration, and logs are at the top of the page:

![image](https://github.com/hassio-addons/addon-ssh/assets/26891995/6ba311a2-dfa0-410a-b676-0bab619e4d29)

2.)  **fill in a username and password in the Configuration tab**. 

*Note: The Documentation tab (also available in this repo at https://github.com/hassio-addons/addon-ssh/blob/main/ssh/DOCS.md) gives more info about options you can use here. To be extra-secure you really should set up keys, which you can find info about in the Documentation, but this is a quickstart, so to get this mother love bone rolling we'll just pick a username and password.*

![image](https://github.com/hassio-addons/addon-ssh/assets/26891995/900b07f2-3a41-44d5-b6b0-a5e0809b9e73)

3.) After entering a username and password, be sure to **scroll to the bottom of that Options block and click 'save'.** 

*Note: Be careful!  There are several "save" buttons on that tab, one for each block. If you click the wrong 'save' button, it won't tell you there's a problem, but it won't save your chosen username & password! If you have problems later in this process, come back to this step and make sure you saved your username and password correctly.* 

![image](https://github.com/hassio-addons/addon-ssh/assets/26891995/271eddb4-7629-44e4-a65f-54135c554cbb)

4.) Go back to the Info tab, then **click 'Start'.** 

![image](https://github.com/hassio-addons/addon-ssh/assets/26891995/fc5edda3-c5e5-485e-92ed-edbb2967f36b)

5.) Some CPU & RAM meters and a link for "Open Web UI" will appear. **Click "Open Web UI".** 

![image](https://github.com/hassio-addons/addon-ssh/assets/26891995/c08b29ca-ae36-400b-9202-af60142230b3)
6.) Ta-daa! **You're in**. Or, at least, I was, by following those steps. YMMV.

![image](https://github.com/hassio-addons/addon-ssh/assets/26891995/78ce66ac-4cd6-4fe3-b196-8974aee13da9)

You can now SSH in from a normal SSH client, using the name and password you set up in step 2.

![image](https://github.com/hassio-addons/addon-ssh/assets/26891995/4ff659de-5961-4c3f-ab6c-64bb493ab866)

In case anything happens to this issue thread, I have these instructions permanently archived on my website at [https://www.kupietz.com/2024/02/17/the-missing-quickstart-guide-to-the-home-assistant-advanced-ssh-web-terminal-community-add-on/](https://www.kupietz.com/2024/02/17/the-missing-quickstart-guide-to-the-home-assistant-advanced-ssh-web-terminal-community-add-on/).

**Comment by xwl** [comment]
Big thanks for the hint of clicking the correct `Save` button, I used the one at the bottom wrongly multiple times, wondering why it was not saved..

**Comment by kupietools** [comment]
> I used the one at the bottom wrongly multiple times,

Yeah, I made sure to mention it because I got tripped up by that a few times myself before I caught it.

**Comment by bradkemper** [comment]
@kupietools Thank you so much. That was a big help.
