### ISSUE TITLE
VSCode desktop won't connect to Remote SSH after upgrading VSCode to version 1.86.0

### ISSUE THREAD

**Issue by ekain-fr** [hassio-addons/addon-ssh#686]
# Problem/Motivation

After the automatic upgrade of VSCode desktop to version 1.86.0, I'm no longer able to connect to HA using the Remote SSH extension.

> This issue is discussed at length on vscode GitHub: [vscode server won’t start: “Waiting for server log…” #203967](https://github.com/microsoft/vscode/issues/203967)

The underlying issue seems to be that an updated dependency on some libraries on HA add-on’s side (minimum GLIBC >= 2.28 apparently from the comments in the GitHub issues) is preventing VS Code 1.86.0 from connecting successfully over SSH.
> See also: [Clarify platform requirements for 1.86 release #201129](https://github.com/microsoft/vscode/issues/201129)

The current workaround is to downgrade remote-ssh extension to version 0.107, disable updates, and also downgrade VS Code desktop to version 1.85.2.
> See also: [Workaround for machines that do not have glibc >= 2.28 #203375](https://github.com/microsoft/vscode/issues/203375)

See my post [here](https://community.home-assistant.io/t/how-to-connect-local-vscode-instance-to-vs-code-ha-add-on-via-ssh/227697/20?u=eugene78).

## Expected behavior

> Using VS Code desktop to open a Remote connection to my HA instance should display my config folder and allow me to load & edit files.

## Actual behavior

> vscode server won't start: lots of messages in the terminal "Waiting for server log...", then failure message.

## Steps to reproduce

> Upgrade VSCode desktop to version 1.86.0, then try to start a Remote SSH connection to HA.

## Proposed changes

> Update the libraries / distribution to VS Code's requirements.

**Comment by frenck** [comment]
> The underlying issue seems to be that an updated dependency on some libraries on HA add-on’s side (minimum GLIBC >= 2.28 apparently from the comments in the GitHub issues) 

This add-on runs on Alpine Linux, which is musl-based, not GLIBC-based. Thus that doesn't apply here.

What does apply, is that there is a gcompat package installed in this add-on, that should make up for the missing glibc. Probably there is a similar requirements change upstream upstream in VSCode. However, this add-on runs the latest gcompat available...

../Frenck

**Comment by frenck** [comment]
> I don't think Remote SSH will work with Alpine now that the libraries are a requirement.

That didn't change. It was always listed as such.

**Comment by chatziko** [comment]
Here's the corresponding open vscode issue, hopefully a workaround for vscode 1.86 will be found soon: https://github.com/microsoft/vscode-remote-release/issues/6347

If not, maybe we can resurrect the good old debian-based [addon-vscode-remote](https://github.com/hassio-addons/addon-vscode-remote).

**Comment by L3v3L** [comment]
Vscode will be rolling back this requirement later this week, and delaying its release to later this year.

**Comment by chatziko** [comment]
> Vscode will be rolling back this requirement later this week, and delaying its release to later this year.

Best news I had all day :smile:

**Comment by L3v3L** [comment]
https://github.com/microsoft/vscode/issues/203375#issuecomment-1927893504

**Comment by ekain-fr** [comment]
Good news, thanks for the info & the link.

The comment states however that:
> We have discussed this more in the VS Code team and we have decided to allow VS Code to connect to an OS that is not supported by VS Code (no support for glibc >= 2.28) for **12 more months**.
> We hope this will provide the needed time for you and your companies to migrate to newer Linux distributions. 

So while the issue is solved in the short term, we still need a proper solution for the longer term.

Cheers!

**Comment by chatziko** [comment]
I tested vscode 1.86.1, it works fine, so for now this issue can be closed. In a year for now maybe they'll add proper alpine support without the need for gcompat.

**Comment by chatziko** [comment]
For anyone getting the following error after upgrading to vscode 1.88:

```
> ps: unrecognized option: p
> BusyBox v1.36.1 (2023-11-07 18:53:09 UTC) multi-call binary.
> 
> Usage: ps [-o COL1,COL2=HEADER] [-T]
> 
> Show list of processes
> 
> 	-o COL1,COL2=HEADER	Select columns for display
> 	-T			Show threads
[21:43:39.087] > Exec server process not found
> 4dc7d0c17f11: start
```

The problem is an incompatibility with the busybox version of `ps`  installed by default on Alpine. You just need to `apk add procps-ng` to solve it (or add `procps-ng` to the list of automatically installed packages).

Maybe `procps-ng` can be installed by default (similarly to `gcompat`) to make life easier.

**Comment by klaasnicolaas** [comment]
Or disable the exec server mode 😉

**Comment by chatziko** [comment]
First time I hear about "exec server mode" :smile: 
Setting `remote.SSH.useExecServer: false` does solve the problem indeed.

Interestingly, with `useExecServer: true` the annoying "unsupported OS version" ribbon doesn't appear at all.
