### ISSUE TITLE
Connection closed

### ISSUE THREAD

**Issue by BartEngelen** [hassio-addons/addon-ssh#69]
# Problem/Motivation

> Today I updated to SSH & Web Terminal 5.0.0
When I want to open the add-on via Open Web UI I get the
message Connection closed and a blank screen is showing

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by BartEngelen** [comment]
Here are my config and the log files:
![image](https://user-images.githubusercontent.com/17978789/56148971-c8895300-5fab-11e9-8293-327b68b33f28.png)
![image](https://user-images.githubusercontent.com/17978789/56148991-d2ab5180-5fab-11e9-9c74-f5147c3c11de.png)
![image](https://user-images.githubusercontent.com/17978789/56149015-dfc84080-5fab-11e9-8c17-59253d0985f5.png)

**Comment by BartEngelen** [comment]
This is what I get when I click on the Open Web UI
![image](https://user-images.githubusercontent.com/17978789/56149255-6d0b9500-5fac-11e9-870e-d8502af1202b.png)

**Comment by frenck** [comment]
Are you using Firefox or any firefox based browser?
If so, could you try Chrome for a sec?

**Comment by lbouriez** [comment]
Hello, I have a similar issue since the update:
`/usr/lib/bashio/config.sh: line 53: printf: write error: Broken pipe
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.`
So container is not starting

**Comment by lbouriez** [comment]
> Are you using Firefox or any firefox based browser?
> If so, could you try Chrome for a sec?

In my case I am using Brave (chromium based)

**Comment by macrojames** [comment]
Chrome logs the following error for me:
```
WebSocket connection to 'wss://xxxxx.duckdns.org/api/hassio_ingress/xxxxx/ws' failed: One or more reserved bits are on: reserved1 = 0, reserved2 = 1, reserved3 = 1
Websocket connection closed with code: 1006
```
But local Websocket config seems ok according to http://websocketstest.com

**Comment by BartEngelen** [comment]
> Are you using Firefox or any firefox based browser?
> If so, could you try Chrome for a sec?

I use Chrome

**Comment by frenck** [comment]
Please try upgrading to Home Assistant 0.91.4, which addresses a couple of WebSocket handling issues with Ingress.

**Comment by lbouriez** [comment]
Working after the update :)

**Comment by lbouriez** [comment]
I did more tests, for me it seems fixes after the HA update.

**Comment by BartEngelen** [comment]
After the upgrading of Home Assistant to version 0.91.4 it works perfect !
Thanks !

**Comment by frenck** [comment]
:tada: Nice! Thanks for letting me know!
