### ISSUE TITLE
SSh addon don't start

### ISSUE THREAD

**Issue by ediazrod** [hassio-addons/addon-ssh#694]
# Problem/Motivation

I upgrade the addon but don't workanymore.
Terminal & SSH
Current version: 9.9.0

## Expected behavior

The addon to start

## Actual behavior

Get a error.
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/apks.sh
Error relocating /usr/lib/libonig.so.5: unsupported relocation type 4412
Error relocating /usr/lib/libonig.so.5: unsupported relocation type 4412
Error relocating /usr/lib/libonig.so.5: unsupported relocation type 4412
cont-init: info: /etc/cont-init.d/apks.sh exited 0
cont-init: info: running /etc/cont-init.d/keygen.sh
[19:11:56] INFO: Restoring host keys...
cont-init: info: /etc/cont-init.d/keygen.sh exited 0
cont-init: info: running /etc/cont-init.d/profile.sh
Error relocating /usr/lib/libonig.so.5: unsupported relocation type 4412
[19:11:56] ERROR: Failed to escape string
2024/02/12 19:11:56 EOF
cont-init: info: /etc/cont-init.d/profile.sh exited 1
cont-init: info: running /etc/cont-init.d/ssh.sh
Error relocating /usr/lib/libonig.so.5: unsupported relocation type 4412
[19:11:56] ERROR: Failed to escape string
2024/02/12 19:11:56 EOF
cont-init: info: /etc/cont-init.d/ssh.sh exited 1
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

## Steps to reproduce
upgrade the addon..

## Proposed changes

maybe reinstall (I do it but don't work)
Maybe remove liboning and reinstall the the containers or rebuild...

**Comment by frenck** [comment]
Hi there @ediazrod 👋 

You are reporting this issue in the wrong place. This is the issue tracker / repository of the community SSH add-on: Advanced SSH & Web Terminal.

However, your issue report is for the version maintained by the Home Assistant project.

Please report issues with their add-ons in the their issue tracker instead.

../Frenck
