### ISSUE TITLE
no longer updating 

### ISSUE THREAD

**Issue by gnkarn** [hassio-addons/addon-ssh#70]
# Problem/Motivation
SSH & Web Terminal 5.0.0 is available
You are currently running version 4.1.0
This update is no longer compatible with your system.

my setup : 
`

arch | x86_64
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.7.2
timezone | America/Argentina/Buenos_Aires
version | 0.91.2
virtualenv | false

`

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
The add-on needs at least Home Assistant 0.91.3 for v5.0.0
