### ISSUE TITLE
update to 5.0 breaks silently as ssh port is not honored

### ISSUE THREAD

**Issue by maxandersen** [hassio-addons/addon-ssh#71]
# Problem/Motivation

> (Why the issue was filed)

updating to latest version 5.0 result in 502: gateway errorr when using ingress because
5.0 now seem to ignore "port" specified in settings and instead fully listens to the UI specified network setting.

## Expected behavior

> (What you expected to happen)
would have expected it would at least use the same value in json "port" if it exists rather than just ignore it OR at least have it mentioned in the release notes.

## Proposed changes

Document the change or even better honor json settings if they exist to avoid update/migration errors.

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Port and ingress have nothing to do with each other. Hence I don't get your issue. Could please clarify?

**Comment by maxandersen** [comment]
Before 5.0 SSH port was defined In JSON now it's defined in the network settings. 

After update where I had JSON stating "port: 2222" the new network section had port 22 listed. 

That means the update breaks/don't honor the config from past version.

**Comment by frenck** [comment]
Correct, that is why it got a major version number.
So it works?

**Comment by maxandersen** [comment]
It works but I saw zero mention about it in release notes so zero warning. 

is the assumption to follow for hassio community major revisions that the update will break ? (And to guess what broke ? :)

**Comment by frenck** [comment]
The release notes state it implements Hass.io Ingress.

There is an announcement on the homepage of Home Assistant on the introduction of the Ingress feature, what is it and what it means.

Since there is no issue, I'm closing this.

**Comment by frenck** [comment]
Oh yes, major revisions will break updates, see:

https://github.com/hassio-addons/addon-ssh#changelog--releases

<blockquote><img src="https://avatars1.githubusercontent.com/u/30772201?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/hassio-addons/addon-ssh">hassio-addons/addon-ssh</a></strong></div><div>SSH & Web Terminal - Community Hass.io Add-on for Home Assistant - hassio-addons/addon-ssh</div></blockquote>

**Comment by maxandersen** [comment]
Okey - maybe I'm blind but at no place did I Spot info on the ssh port info now being ignored during the update. 

Anyway good to know - lesson learned: don't update to major versions of hassio community add-ons unless I have time to guess the config changes needed.

At least it's now documented in the issues for others to learn from. Thanks.

**Comment by frenck** [comment]
Please uninstall. Thanks.
