### ISSUE TITLE
Typing commands (in terminal add-on) in Home Assistant Companion does not work under Mac OS Ventura

### ISSUE THREAD

**Issue by amordicus** [hassio-addons/addon-ssh#711]
# Problem/Motivation
Cannot run any command in terminal from HA Companion if running on my mac OS Ventura, it is fine on Big Sur.

> It would be nice if it work, although the work around is to use a web browser.
## Expected behavior
Should let me execute the commands; CR and backspace don't work

> (What you expected to happen)
Works when running HA companion in Mac OS Big Sur so I expected terminal to work on Ventura

## Actual behavior
 I can type some text such ls -la but nothing happen when pressing the Enter key.
This happens only on my mac running Ventura it is fine on Big Sur.

## Steps to reproduce
Type any command followed by enter and nothing happen, when running companion on Ventura.
Sorry, I have only these 2 systems to test on.

## Proposed changes
I expect terminal to work on any OSs.  BTW, all my other add-ons seems to be fine ,so far, when running under Ventura.

my configuration:
ssh:
  username:
  password: 
  authorized_keys: 
  sftp: false
  compatibility_mode: false
  allow_agent_forwarding: false
  allow_remote_port_forwarding: false
  allow_tcp_forwarding: false
zsh: true
share_sessions: true
packages: []
init_commands:

**Comment by frenck** [comment]
🤷 Please report it with the app.
