### ISSUE TITLE
Remapped tmux bindings not documented

### ISSUE THREAD

**Issue by sorenisanerd** [hassio-addons/addon-ssh#720]
https://github.com/hassio-addons/addon-ssh/blob/b1db0a64eb5b7ae726397d4be8a2d51dace38c92/ssh/rootfs/root/.tmux.conf#L12-L14

I'm confused why C-b is remapped to C-b, but having it documented would have been really nice.

**Comment by ross-kleiman** [comment]
I'm experiencing the same error. Though I just went to set this up today for the first time and so I can't confirm prior functionality. I'll be attempting to rollback my VSCode to an earlier version and see if I can get it to work that way.

**Comment by frenck** [comment]
it is compatibility with the original screen binding. I think we can just remove the unbind C-b and leave the C-a additionally.

**Comment by dekimsey** [comment]
> it is compatibility with the original screen binding. I think we can just remove the unbind C-b and leave the C-a additionally.

@frenck is this still a possibility? I ran into this myself only because I was leaning on "oh-tmux-muscle-memory" than anything else and was confused :)
