### ISSUE TITLE
Make mouse mode configurable

### ISSUE THREAD

**Issue by sorenisanerd** [hassio-addons/addon-ssh#721]
https://github.com/hassio-addons/addon-ssh/blob/b1db0a64eb5b7ae726397d4be8a2d51dace38c92/ssh/rootfs/root/.tmux.conf#L11

Please, please, please make this configurable. Alternatively, maybe add an environment variable to ttyd, and make mouse mode conditional on it not being set? It completely breaks copy/paste in browsers.

**Comment by tjorim** [comment]
This sounds more like a feature request, feel free to submit a PR.

**Comment by sorenisanerd** [comment]
When mouse mode is enabled, copy/paste doesn't work in browsers. If you have a better way to fix that, great.

I can do a PR, but I don't have a hass dev environment set up, and have a lot on my plate, so it could be days, weeks, or years, depending on my ADHD 🤷‍♂️ I really shouldn't be in the critical path for this.

**Comment by frenck** [comment]
Closing, as it is a feature request. Feel free to make a PR.
