### ISSUE TITLE
Please add hass-cli (https://github.com/home-assistant-ecosystem/home-assistant-cli) package to build

### ISSUE THREAD

**Issue by xitation** [hassio-addons/addon-ssh#728]
# Problem/Motivation

The hass-cli package is very useful to interact with HA via an cli interface, allowing for bulk rename of entities using script etc. It's not currently included in this image as far as I can tell. I've worked out the steps needed to build and install the required dependencies and then the python package. And I'll submit this as  a PR shortly.

## Expected behavior

When you run hass-cli from the cli it exists and runs, allowing use of the utility.

## Actual behavior

You are unable to hass-cli as it's not installed.

## Steps to reproduce

Attempt to run hass-cli utility results in command not found error.

## Proposed changes

Add the build dependencies to Dockerfile:
        python3-dev \
        libc-dev \
        gcc \

Add the homeassistant-cli package to requierments.txt, which would install it using pip as per inspections on project page - https://github.com/home-assistant-ecosystem/home-assistant-cli
        homeassistant-cli==0.9.6

**Comment by frenck** [comment]
This package used to be part of this add-on, but has been removed. It caused compatibility issues in the past, preventing add-on updates to be shipped.

You can manually add it in your add-on configuration is you prefer to use it.

../Frenck
