### ISSUE TITLE
Error: Address in use

### ISSUE THREAD

**Issue by sim-san** [hassio-addons/addon-ssh#73]
# Problem/Motivation

After the update to version 5.0.0, i get the following error:

## Actual behavior

debug1: rexec_argv[0]='/usr/sbin/sshd'
debug1: rexec_argv[1]='-D'
debug1: rexec_argv[2]='-e'
debug1: rexec_argv[3]='-d'
debug1: Set /proc/self/oom_score_adj from 0 to -1000
debug1: Bind to port 22 on 0.0.0.0.
Bind to port 22 on 0.0.0.0 failed: Address in use.
debug1: Bind to port 22 on ::.
Bind to port 22 on :: failed: Address in use.
Cannot bind any address.
[2019/04/19 12:32:41:2454] NOTICE: Creating Vhost 'default' path "/var/run/ttyd.sock", 2 protocols
[2019/04/19 12:32:41:2491] NOTICE: received signal: SIGTERM (15), exiting...
[2019/04/19 12:32:41:2492] NOTICE: send ^C to force exit.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
/usr/lib/bashio/config.sh: line 53: printf: write error: Broken pipe
[s6-finish] sending all processes the TERM signal.

## Steps to reproduce

 Add-on version: 5.0.0
 You are running the latest version of this add-on.
 System: Raspbian GNU/Linux 9 (stretch)  (armv7 / raspberrypi3)
 Home Assistant version: 0.91.4
 Supervisor version: 160

**Comment by sim-san** [comment]
### Complete Log:
_replace private keys with ... _

[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Hass.io Add-on: SSH & Web Terminal
 SSH & Web Terminal access to your Home Assistant instance
-----------------------------------------------------------
 Add-on version: 5.0.0
 You are running the latest version of this add-on.
 System: Raspbian GNU/Linux 9 (stretch)  (armv7 / raspberrypi3)
 Home Assistant version: 0.91.4
 Supervisor version: 160
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to DEBUG
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] docker.sh: executing... 
[cont-init.d] docker.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] ssh.sh: executing... 
[12:32:30] NOTICE: RSA host key missing, generating one...
Generating public/private rsa key pair.
Your identification has been saved in /data/ssh_host_rsa_key.
Your public key has been saved in /data/ssh_host_rsa_key.pub.
The key fingerprint is:
...
The key's randomart image is:
+---[RSA 2048]----+
...
+----[SHA256]-----+
[12:32:37] NOTICE: ED25519 host key missing, generating one...
Generating public/private ed25519 key pair.
Your identification has been saved in /data/ssh_host_ed25519_key.
Your public key has been saved in /data/ssh_host_ed25519_key.pub.
The key fingerprint is:
...
The key's randomart image is:
+--[ED25519 256]--+
...
+----[SHA256]-----+
[cont-init.d] ssh.sh: exited 0.
[cont-init.d] user.sh: executing... 
[cont-init.d] user.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[12:32:41] INFO: Starting the ttyd daemon...
[12:32:41] INFO: Starting the SSH daemon...
[12:32:41] INFO: Starting NGinx...
[2019/04/19 12:32:41:2197] NOTICE: ttyd 1.4.2-1f6a6c7 (libwebsockets 3.0.1)
[2019/04/19 12:32:41:2197] NOTICE: tty configuration:
[2019/04/19 12:32:41:2198] NOTICE:   start command: tmux -u new -A -s hassio zsh
[2019/04/19 12:32:41:2198] NOTICE:   close signal: SIGHUP (1)
[2019/04/19 12:32:41:2198] NOTICE:   terminal type: xterm-256color
[2019/04/19 12:32:41:2198] NOTICE:   reconnect timeout: 30s
debug1: sshd version OpenSSH_7.9, OpenSSL 1.1.1b  26 Feb 2019
debug1: private host key #0: ssh-rsa ...
debug1: private host key #1: ssh-ed25519 ....
debug1: rexec_argv[0]='/usr/sbin/sshd'
debug1: rexec_argv[1]='-D'
debug1: rexec_argv[2]='-e'
debug1: rexec_argv[3]='-d'
debug1: Set /proc/self/oom_score_adj from 0 to -1000
debug1: Bind to port 22 on 0.0.0.0.
Bind to port 22 on 0.0.0.0 failed: Address in use.
debug1: Bind to port 22 on ::.
Bind to port 22 on :: failed: Address in use.
Cannot bind any address.
[2019/04/19 12:32:41:2454] NOTICE: Creating Vhost 'default' path "/var/run/ttyd.sock", 2 protocols
[2019/04/19 12:32:41:2491] NOTICE: received signal: SIGTERM (15), exiting...
[2019/04/19 12:32:41:2492] NOTICE: send ^C to force exit.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
/usr/lib/bashio/config.sh: line 53: printf: write error: Broken pipe
[s6-finish] sending all processes the TERM signal.

**Comment by tjorim** [comment]
`Bind to port 22 on :: failed: Address in use.`
there seems to be something else on port 22 already?

**Comment by sim-san** [comment]
How can i check which program use the port 22 ?

**Comment by sim-san** [comment]
On the homeassistant/raspberrypi3-homeassistant docker container i get the following information:

bash-4.4# netstat -tulpn | grep LISTEN
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      -
tcp        0      0 192.168.178.50:51827    0.0.0.0:*               LISTEN      6/python3
tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:61208           0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:61209         0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:8123            0.0.0.0:*               LISTEN      6/python3
tcp        0      0 0.0.0.0:8443            0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:17276         0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:445             0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:4865            0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:4711          0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:139             0.0.0.0:*               LISTEN      -
tcp6       0      0 :::80                   :::*                    LISTEN      -
tcp6       0      0 :::53                   :::*                    LISTEN      -
tcp6       0      0 :::22                   :::*                    LISTEN      -
tcp6       0      0 :::445                  :::*                    LISTEN      -
tcp6       0      0 :::7777                 :::*                    LISTEN      -
tcp6       0      0 :::4865                 :::*                    LISTEN      -
tcp6       0      0 ::1:4711                :::*                    LISTEN      -
tcp6       0      0 :::139                  :::*                    LISTEN      -

**Comment by frenck** [comment]
@sim-san Looks like you have a generic linux installation type of Hass.io.
This means you have a custom linux (raspbian in your case so it seem), which has SSH already out of the box, also using port 22.

You might want to consider placing the add-on or the host OS SSH on a different port.

**Comment by nickm324** [comment]
I had this same issue because I forgot I had installed the other SSH server first and it was already binding to that address and port. I removed it and all worked fine.

**Comment by chriscrowe** [comment]
It seems to me that this add-on no longer has the `ssh.port` option available? I have the same issue where my host OS (Linux) is listening on 22 and this add-on was listening on 2222, but now my config is trying to listen on 22 despite my config still saying 2222. Did this option get removed?

**Comment by frenck** [comment]
@chriscrowe  It has been moved to a general configuration option:

![image](https://user-images.githubusercontent.com/195327/56756871-0ef06600-6793-11e9-9ee2-df3476248b05.png)

**Comment by frenck** [comment]
Closing issue, since it is not an issue.
