### ISSUE TITLE
Mouse wheel scroll no more scroll terminal output

### ISSUE THREAD

**Issue by nepozs** [hassio-addons/addon-ssh#742]
# Problem/Motivation

Impossible to scroll up  terminal output with mouse wheel

## Expected behavior

scroll up  terminal output with mouse wheel
like in 17.2.0 or 17.1.1 (or any older version and yes, I know about the other mouse copy problem, but the solution to the copy problem induces new with scrolling)

## Actual behavior

Mouse wheel scrolls command history (which is already really easy available with `cursor up`) instead output window

## Steps to reproduce

update to 17.3.0 or 18.0.0 
use any command with really long output (`dmesg` is really good example)
try to scroll up

## Proposed changes

Revert changes that change scrolling behavior
or if possible create options to change behavior available to end user

**Comment by kevdogg** [comment]
Is there a keyboard shortcut of button you can hold while scolling? I'm just using a trackpad on macbook and scrolling on trackpad just scrolls command history

**Comment by nepozs** [comment]
This was the first thing I tried but I can't find any modifier key combination that would help. So I've downgraded the addon to a working version, but it isn't solution.

**Comment by nepozs** [comment]
still no changes, no developer answer…

**Comment by csutiperec** [comment]
https://github.com/hassio-addons/addon-ssh/commit/a9140d5009e6cff2144d681442190dd190739f61

It was this commit, that removed mouse scroll when running under ttyd

**Comment by nepozs** [comment]
Still do not work, so I don't understand why this is closed…
