### ISSUE TITLE
auto-completion of bash shell commands are not working

### ISSUE THREAD

**Issue by simonepittis** [hassio-addons/addon-ssh#743]
auto-completion of bash shell commands are not working on v18.0.0

auto-completion command with TAB work on 17.3.0

**Comment by bakerkj** [comment]
I can confirm I am seeing a related problem in that my `.bash_profile` is no longer running in 18.0.0.

I suspect the default shell is different between 17.3.0 and 18.0.0.

Having a configuration option to select `bash`, `zsh`, etc might be a reasonable path forward.

**Comment by NodeJSmith** [comment]
Same issue here on version 18.0.0, it seems that I get dropped in a `sh` shell instead of a `zsh` shell. Everything works normal if I run zsh to get into a proper zsh shell. Not sure what happened in the latest update

**Comment by aodtcr** [comment]
Same here- autocompletion, as well as other commands and aliases are not working. It seems the default `ash` shell is loaded instead of `zsh`, although `zsh` is installed and works when its run manually (as mentioned by @NodeJSmith). 
Somehow `zsh` is not started when a new terminal session is opened. 
Restarting the addon, or uninstalling and reinstalling the addon, does not solve the issue for me. Going back to v17.3.0 does run `zsh` as default shell.

**Comment by VlastiBroucek** [comment]
Same issue for me - unfortunately,  I've created https://github.com/hassio-addons/addon-ssh/issues/744#issue-2320081388 before reading this one as the title did not suggest similarity.

**Comment by simonepittis** [comment]
ok fixed :-)

easy:
- edit the file /etc/passwd
- change from "/bin/sh" to "/bin/zsh" the shell of user root
- logout

**Comment by VlastiBroucek** [comment]
> ok fixed :-)
> 
> easy:
> 
> * edit the file /etc/passwd
> * change from "/bin/sh" to "/bin/zsh" the shell of user root
> * logout

Only until you restart your HA instance or the add-on... Don't think that etc/passwd is persistent... Or did you try it?

**Comment by simonepittis** [comment]
/etc/passwd need to be persistent

**Comment by VlastiBroucek** [comment]
> /etc/passwd need to be persistent

https://github.com/hassio-addons/addon-ssh/issues/744

**Comment by simonepittis** [comment]
ufff :-(

**Comment by simonepittis** [comment]
I see this https://github.com/hassio-addons/addon-ssh/pull/755 but not implemented... we waiting
