### ISSUE TITLE
Failed to start add-on - Unknown error, see supervisor

### ISSUE THREAD

**Issue by DBorello** [hassio-addons/addon-ssh#754]
# Problem/Motivation

I am unable to get the add-on to start.  

The only error message is the log is:

`2024-06-22 19:52:14.949 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/a0d7b954_ssh/start - Unknown error, see supervisor`

**Comment by frenck** [comment]
That is an Home Assistant error log, which is not really useful to see what is going on.

Anything in the add-on logs and Supervisor logs?

../Frenck

**Comment by DBorello** [comment]
Supervisor: 

`2024-06-23 20:59:44.449 ERROR (MainThread) [supervisor.utils.json] Can't write /data/addons/data/a0d7b954_ssh/options.json: [Errno 2] No such file or directory: '/data/addons/data/a0d7b954_ssh/tmpggh7_ihq'
2024-06-23 20:59:44.450 ERROR (MainThread) [supervisor.addons.addon] Add-on a0d7b954_ssh can't write options`

Nothing in the addon's log.

**Comment by theminor** [comment]
I get the same error. `Failed to to call /addons/a0d7b954_ssh/start - Unknown error, see supervisor`

**Comment by tjorim** [comment]
> I get the same error. `Failed to to call /addons/a0d7b954_ssh/start - Unknown error, see supervisor`

What do you see in the supervisor logs (like the error suggests to check)?
