### ISSUE TITLE
scp from remote host broken

### ISSUE THREAD

**Issue by pssc** [hassio-addons/addon-ssh#77]
The included .zprofile does not check for interactive session before invoking tmux, the following .zprofile fixes this and allows scp and other non-interactive sessions to work:-

    if [[ -z "$TMUX" ]]; then
       if [[ -o interactive ]]; then
          exec tmux -u new -A -s hassio zsh
       fi
    fi

**Comment by pssc** [comment]
Hi I have been running inserting this fix for a while and it seems good.

Phill.

**Comment by memed36** [comment]
Yes, please integrate in next release.

**Comment by pssc** [comment]
No it is not stale
