### ISSUE TITLE
Firefox Can’t Open This Page

### ISSUE THREAD

**Issue by menteb** [hassio-addons/addon-ssh#770]
# Problem/Motivation

Firefox blocks embedded frames by default, and it seems that this cannot be disabled. Also, opening the link in a new window is not possible as it opens the whole home assistant page.

![Screenshot 2024-08-03 at 1 06 22](https://github.com/user-attachments/assets/bb5a0128-602d-4088-bba3-f8d166971669)

## Proposed changes

An X-frame might be the solution from what I've seen online.

**Comment by sinclairpaul** [comment]
Can you post the output from the Dev Tools?, it isn't an iframe by default

**Comment by menteb** [comment]
![screenshot](https://github.com/user-attachments/assets/f22ba086-0ef9-4ae6-a053-3789ecfb8b1d)

This is what I see in the console.

**Comment by sinclairpaul** [comment]
Then it needs to be logged against the HomeAssistant Supervisor repo, the addon doesn't control the behavior of that proxy.
