### ISSUE TITLE
Can SSH, can't SCP <<Solved>>

### ISSUE THREAD

**Issue by Pedulla** [hassio-addons/addon-ssh#783]
# Problem
v18.0.0
ssh works, scp doesn't

## Expected behavior
scp to copy the file
## Actual behavior

I can ssh in just fine.  But when I scp...
`scp bob@192.168.0.23:./test.txt ./
`
`subsystem request failed on channel 0
`
`scp: Connection closed
`

**Comment by IngmarStein** [comment]
Does `scp -O` work?

**Comment by Pedulla** [comment]
Bingo, that worked.
Thanks!
