### ISSUE TITLE
cannot change settings

### ISSUE THREAD

**Issue by luciandf** [hassio-addons/addon-ssh#791]
# Problem/Motivation
I am trying to change some settings: set user name to root, set sftp to true and set an init command to ls -la but after I click save (with the process stopped) and start the process, the settings are back to what they were before.

## Expected behavior

> the settings to be changed

## Actual behavior

> settings revert to the initial values

## Steps to reproduce

> just as above but unsure that this is happening to everyone

**Comment by Robsi01** [comment]
I am also seeing this issue.

**Comment by SiteRelEnby** [comment]
+1 on this.

Just migrated my homeassistant install to a new host, imported the config backup, and I can not login via SSH (key not accepted) or edit the config.

**Comment by regunakyle** [comment]
Bump, I am also having this issue.
