### ISSUE TITLE
default terminal ssh in windows won't connect

### ISSUE THREAD

**Issue by dougransom** [hassio-addons/addon-ssh#792]
# Problem/Motivation
Use  the ssh available in powershell in windows 11.  Some sort of MAC error ocurrs.

## Expected behavior

> (What you expected to happen)
ssh connection
## Actual behavior
```
PS C:\Users\doug> ssh ha.local
Corrupted MAC on input.
```

## Steps to reproduce
attempt to connect to home assistant via ssh in terminal (power shell, windows 11)

## Proposed changes
Configure ssh on HA so that the ssh on terminal will connect without mac error.

The work around on Windows is `ssh -m hmac-sha2-256-etm@openssh.com ha.local` but that is too much for more mortal windows users.  instead ssh should be configured on HA to negotiate whatever needs with windows terminal ssh.

**Comment by sinclairpaul** [comment]
You can also put it in the local ssh config file, I doubt it would be wise to lower the security of the server based on the configuration of a client.
