### ISSUE TITLE
api.pwnedpasswords.com query

### ISSUE THREAD

**Issue by tiix95** [hassio-addons/addon-ssh#807]
Hello,

Is the behavior of querying api.pwnedpasswords.com documented somewhere ? I was not able to make the app work for some reason, and after investigation it appears that if I block the request to "api.pwnedpasswords.com" on my network, the application can't save it's config

**Comment by sinclairpaul** [comment]
It's a function provided by the Homeassistant Supervisor, would suggest logging the question there.
