### ISSUE TITLE
Cannot install on HASSIO

### ISSUE THREAD

**Issue by bigbigblue** [hassio-addons/addon-ssh#81]
# Problem/Motivation
I cannot install the ssh/web terminal plugin in Hassio. First attempt took a very long time > 1 hour and seemed to fail. Subsequent attempts, the Install button goes blue for a few seconds then red.

## Expected behavior
Install completes OK

## Actual behavior
Install fails, following messages in log:

dd-mm-yy hh:mm:ss INFO (SyncWorker_13) [hassio.docker.interface] Pull image hassioaddons/ssh-armv7 tag 5.0.2.
dd-mm-yy hh:mm:ss ERROR (SyncWorker_13) [hassio.docker.interface] Can't install hassioaddons/ssh-armv7:5.0.2 -> 500 Server Error: Internal Server Error ("readlink /mnt/data/docker/overlay2/l: invalid argument").

**Comment by frenck** [comment]
That seems like a corrupted file system. Unfortunately, from an add-on perspective, there is nothing I can do.
