### ISSUE TITLE
State of PR #756

### ISSUE THREAD

**Issue by frispete** [hassio-addons/addon-ssh#812]
Hmm, wonder, where's PR #756 is going.

Needless to say, I'm looking for exactly, what the PR is about to solve. 
Having an ordinary ssh user and being able to use scp/sftp..

The PR is flagged as stale, and comments are closed. 

Any chance to have it applied some time soon? That would be really awesome!

**Comment by frenck** [comment]
Closing this here... issues about asking for progress are not real issues, but more poking or nudging, which is not what an issue tracker is for :)

../Frenck
