### ISSUE TITLE
ssh keys / known hosts are not persisted

### ISSUE THREAD

**Issue by scutaru** [hassio-addons/addon-ssh#82]
# Problem/Motivation

> After a reboot (by this I mean running the "reboot" command while being connected via ssh to the RPi), the /root/.ssh/ folder contains only the authorized_keys file, nothing else.
The private/public key and the known_hosts file are missing completely.
So it seems that some files are persisted while others aren't.

## Expectation

> The keys and the known_hosts files are persisted between reboots.

## Actual behavior

> If I login via ssh and launch the "reboot" command, the server is rebooted and the above mentioned files are removed.

## Steps to reproduce

> Create the known_hosts file manually in the /root/.ssh/ folder (or by confirming a ssh connection). Then run "reboot" or reboot the system from the UI. Log in again and you will see that the file has disappeared. It's the same for the private/public keys.

## Proposed changes

Not sure how to fix this, sorry.

Also, please let me know if you need any kind of logs and I will provide them. For the moment I don't know what might be helpful.
![Selection_377](https://user-images.githubusercontent.com/4253181/59850650-7251db00-9373-11e9-910a-5f3010bc81b1.png)

core-ssh:~# hassio info 
arch: armv7
channel: stable
hassos: "2.12"
homeassistant: 0.94.4
hostname: hassio
logging: info
machine: raspberrypi3
supervisor: "166"
supported_arch:
- armv7
- armhf

**Comment by scutaru** [comment]
core-ssh:~# ls -la ~/.ssh
total 12
drwxr-xr-x    2 root     root          4096 Jun 20 15:30 .
drwx------    1 root     root          4096 Jun 20 15:30 ..
-rw-------    1 root     root           386 Jun 20 15:30 authorized_keys

**Comment by frenck** [comment]
As concluded on Discord, this is the issues tracker for the community SSH & Web Terminal add-on, while the add-on you are using is the Core SSH (official) add-on.
