### ISSUE TITLE
502: Bad Gateway

### ISSUE THREAD

**Issue by bdileo35** [hassio-addons/addon-ssh#83]
# Problem/Motivation

>despues de instalarlo y arrancarlo tira mensaje de error al abrir la webUI.
![Captura](https://user-images.githubusercontent.com/25931160/59921055-eb4c4380-9402-11e9-9ff9-6d108724903f.JPG)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

![Captura](https://user-images.githubusercontent.com/25931160/59921408-f0f65900-9403-11e9-9773-9db909c6cd23.JPG)

**Comment by chorob** [comment]
I am having the same issue.  I am not using public keys, just a password.  Any ideas?

**Comment by frenck** [comment]
Please provide logs.

**Comment by aporzio1** [comment]
This is the log at the bottom of the page. Also, when I hit start it looks like it starts because I see the buttons change to restart and stop, but if i reload the page it changes back to start and the dot in the upr right corner goes red

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] permissions: applying... 
[fix-attrs.d] permissions: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
[cont-init.d] 00-banner.sh: exited 267.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
s6-maximumtime: warning: child process crashed
[cont-finish.d] 99-message.sh: exited 111.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by hlycklama** [comment]
Having the same issue with the exact same logs. With loglevel trace I get a slightly different order (could be a coincidence):

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] permissions: applying... 
[fix-attrs.d] permissions: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
[cont-init.d] 00-banner.sh: exited 267.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
[cont-finish.d] 99-message.sh: exited 111.
[cont-finish.d] done.
s6-maximumtime: warning: child process crashed
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.`

**Comment by frenck** [comment]
Could any of you provide the first section of the logs? It contains hardware and all kinds of version information, that might enable me to reproduce the issue. Thanks :+1:

**Comment by hlycklama** [comment]
How do I get this part? I've tried installing log viewer but it doesn't seem to show add-on logs.

**Comment by sinclairpaul** [comment]
The section isn't there as the banner is failing I believe.

[cont-init.d] 00-banner.sh: executing... 
[cont-init.d] 00-banner.sh: exited 267.

What hardware platform/os are you running on, is there a firewall installed.  Under Supervisor logs do you see any errors.  This looks similar to a previous issue where connections to the Hassio API were being blocked.

**Comment by hlycklama** [comment]
I'm running on a Raspberry Pi Zero W with HassOS. There shouldn't be any firewalls, but I'll check this when I get home as well as the Supervisor logs. Also, the plugin used to work fine until several months ago.

**Comment by sinclairpaul** [comment]
@hlycklama You can ignore the Firewall comment if its HassOS, but the supervisor log would be good.

**Comment by hlycklama** [comment]
Are these the supervisor logs? Upon starting the addon I get these two lines:

```
19-07-19 15:57:21 INFO (SyncWorker_2) [hassio.docker.interface] Clean addon_a0d7b954_ssh application
19-07-19 15:57:27 INFO (SyncWorker_2) [hassio.docker.addon] Start Docker add-on hassioaddons/ssh-armhf with version v6.1.0
```

**Comment by sinclairpaul** [comment]
@hlycklama Thanks, I will try to find my Pi Zero to test, could you confirm if you run any other addons?, if not could you possible test the Node-Red addon to see if you get a similar result?

**Comment by sinclairpaul** [comment]
I can confirm that I can duplicate this on a Pi Zero W (after waiting for the hour long install :) ).  I would like the other users to confirm if this is the same hardware platform.  The challenge is that the Zero is really only a test platform, and not recommended for any kind of production usage.

**Comment by frenck** [comment]
I'm not going to spend time on a Raspberry Pi Zero (W/WH). Please use the core SSH add-on.
