### ISSUE TITLE
persist the .gitconfig file

### ISSUE THREAD

**Issue by scutaru** [hassio-addons/addon-ssh#84]
# Problem/Motivation
> After a reboot, the /home/hassio/.gitconfig file (containing my aliases, my user.name and user.email values) gets removed. These configurations should be persisted, as they are used every time we work with git.

## Expectation
> The configurations should be persisted to be available even after a reboot.

## Actual behavior
> The .gitconfig file gets removed after each reboot.

## Steps to reproduce
> Create the /home/hassio/.gitconfig file and then reboot. The file will be gone when the server starts.

## Proposed changes
> Sorry, cannot help here.

**Comment by MarkJenniskens** [comment]
Proposed change:
Persistant user configs should be storable in a location outside of the Add-on, i.e. in /config
Make the location part of the add-on configuration.

**Comment by frenck** [comment]
@MarkJenniskens no, `/config` is not the right place for that.

**Comment by MarkJenniskens** [comment]
> @MarkJenniskens no, `/config` is not the right place for that.

I agree, but something similar but for user configs of add-ons. Putting it all in the config page of the add-on would be to cumbersome is imagine.

**Comment by frenck** [comment]
@MarkJenniskens ? Who was saying that is all should go into the add-on config?!

**Comment by frenck** [comment]
Added to the current development version, will be part of the next release.

Thanks for the suggestion @scutaru! 👍
