### ISSUE TITLE
Can't start addon

### ISSUE THREAD

**Issue by fantomnotabene** [hassio-addons/addon-ssh#85]
# Problem/Motivation

Can't start addon

## Expected behavior

Running addon

## Actual behavior

Can't start addon

## Steps to reproduce

hassio 0.95, I just restarted the addon and got this:
```
19-06-28 10:36:21 ERROR (SyncWorker_2) [hassio.docker] Can't start addon_core_ssh: 500 Server Error: Internal Server Error ("driver failed programming external connectivity on endpoint addon_core_ssh (a7b57d06a4d98bdfc581e3d6eebd711ad7f491a0c10675e9b96a41658c631620):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 9122 -j DNAT --to-destination 172.30.33.1:22 ! -i hassio: iptables v1.8.2 (nf_tables): unknown option "--dport"
Try `iptables -h' or 'iptables --help' for more information.
 (exit status 2))")
```

I'm on raspbian stretch running hassio in docker.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
This is unfortunately not the add-on itself failing, but something with Hass.io (unsure on what is wrong).
Please report this at the hassio GitHub repository.

**Comment by fantomnotabene** [comment]
Okay, thank you.
