### ISSUE TITLE
502: Bad gateway error 

### ISSUE THREAD

**Issue by r3mcos3** [hassio-addons/addon-ssh#88]
# Problem/Motivation

Bad gateway error on the latest version

`2019/07/21 10:06:13 [crit] 694#694: *1 connect() to unix:/var/run/ttyd.sock failed (2: No such file or directory) while connecting to upstream, client: 172.30.32.2, server: a0d7b954-ssh, request: "GET / HTTP/1.1", upstream: "http://unix:/var/run/ttyd.sock:/", host: "10.10.50.90:8123", referrer: "http://10.10.50.90:8123/a0d7b954_ssh"`

## Actual behavior

![2019-07-21 10 41 27 10 10 50 90 6f02ad882e38](https://user-images.githubusercontent.com/45529818/61588995-6b053380-aba4-11e9-966d-5a04f69c60a6.jpg)

## Steps to reproduce

I don't know if it's applicable for everyone on the latest version

**Comment by frenck** [comment]
Seems like `ttyd` 1.5.1 (included in this release) broke the unix socket behaviour, I'm reverting the ttyd upgrade.

**Comment by frenck** [comment]
Addressed in release v6.2.1.

Thanks for the report @r3mcos3! 👍
