### ISSUE TITLE
Bind to port 22 on 0.0.0.0 failed: Address in use

### ISSUE THREAD

**Issue by hazyitsm** [hassio-addons/addon-ssh#89]
# Problem/Motivation

> Add-on starts, but stops within a few seconds.

## Expected behavior

> Add-on starts and runs as expected

## Actual behavior

> Fails with the following log:

-----------------------------------------------------------
 Hass.io Add-on: SSH & Web Terminal
 SSH & Web Terminal access to your Home Assistant instance
-----------------------------------------------------------
 Add-on version: 6.2.1
 You are running the latest version of this add-on.
 System: Ubuntu 18.04.2 LTS  (amd64 / qemux86-64)
 Home Assistant version: 0.96.4
 Supervisor version: 170
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] docker.sh: executing... 
[cont-init.d] docker.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] ssh.sh: executing... 
[20:09:44] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[20:09:44] WARNING: 
[20:09:44] WARNING: Logging in with a SSH password is security wise, a bad idea!
[20:09:44] WARNING: Please, consider using a public/private key pair.
[20:09:44] WARNING: What is this? https://kb.iu.edu/d/aews
[20:09:44] WARNING: 
[cont-init.d] ssh.sh: exited 0.
[cont-init.d] user.sh: executing... 
[cont-init.d] user.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[20:09:45] INFO: Starting the ttyd daemon...
[20:09:45] INFO: Starting NGinx...
[20:09:45] INFO: Starting the SSH daemon...
Bind to port 22 on 0.0.0.0 failed: Address in use.
Bind to port 22 on :: failed: Address in use.
Cannot bind any address.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
/usr/lib/bashio/config.sh: line 53: printf: write error: Broken pipe
[s6-finish] sending all processes the TERM signal.
-----------------------------------------------------

This is my Config:
{
  "ssh": {
    "username": "!secret ssh_username",
    "password": "!secret ssh_pword",
    "authorized_keys": [],
    "sftp": false,
    "compatibility_mode": false,
    "allow_agent_forwarding": false,
    "allow_remote_port_forwarding": false,
    "allow_tcp_forwarding": false
  },
  "web": {
    "ssl": true,
    "certfile": "fullchain.pem",
    "keyfile": "privkey.pem"
  },
  "share_sessions": true,
  "packages": [],
  "init_commands": []
}

I hope I'm just missing something obvious in the config. Thanks!

**Comment by frenck** [comment]
This means port 22 is already in use.

2 options:
- Change port 22 to something else in the add-on "Network Config" section
- Free up or change the port of the service/application that currently uses port 22
