### ISSUE TITLE
Internet required to start

### ISSUE THREAD

**Issue by glmnet** [hassio-addons/addon-ssh#90]
# Problem/Motivation
Add on does not start, it is necessary to troubleshoot when stuff does not go well

## Expected behavior

Run add on without additional packages, have packages somehow cached

## Actual behavior
````
[22:35:19] FATAL: Failed updating Alpine packages repository indexes
[cont-init.d] user.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
````

## Steps to reproduce
Block internet with firewall, add additional packages like Network-Manager

## Proposed changes

It would be nice if it can ignore the problem and come up at least partially.

**Comment by frenck** [comment]
A) the network manager is already installed by default
B) Are you really complaining now about not being to install packages on startup when you block the internet? Where should it get its packages from in that case? Thin air?

Closing issue.

**Comment by glmnet** [comment]
I’m sorry my issue is not clear enough. 
Does that error message means this add on would never work if internet is not available?
I understand I cannot install addons without internet. But I am trying to hassio to come up to an usable state even if internet is not available after a cold boot. 

Thanks. 

Ps you don’t need to be rude.

**Comment by frenck** [comment]
"If I remove that will I still be able to do nmcli? " -> Yes, since Network Manager is baked into the add-on itself already. Basically, right now, you are just re-installing it...

Without any additional packages set, the add-on will be able to start without internet.

**Comment by glmnet** [comment]
Ahh yes! It works indeed. Thanks again!
