### ISSUE TITLE
[FATAL tini (6)] exec /init failed: Exec format error

### ISSUE THREAD

**Issue by radinsky** [hassio-addons/addon-ssh#93]
# Problem/Motivation
Start of addon docker fails with the following error:
`[FATAL tini (6)] exec /init failed: Exec format error`

Tried reinstalling the addon, but still the error reproduced the same.
Running on hassio on i386. All other addons work perfectly.
Homeassistant 0.97.1/0.97.2

**Comment by gumby2** [comment]
sweet!  BTW, still broken on rpi0

**Comment by frenck** [comment]
rpi0 is no longer a recommended device for Hass.io.

**Comment by gumby2** [comment]
Ouch!

**Comment by gumby2** [comment]
Mine works fine, is there any way to install a previous version that
works?  Maybe using portainer?

Thanks

**Comment by mzac** [comment]
@frenck I just upgraded to HassOS 3.7 (Raspberry Pi 3 32 bit) and updated this addon to 6.4.2 and I'm getting this error even after re-installing and setting the addon back to defaults:

```
[FATAL tini (6)] exec /init failed: Exec format error

or

[FATAL tini (7)] exec /init failed: Exec format error
```

**Comment by fxcoolby** [comment]
I am getting the same error post update

**Comment by 42hema** [comment]
Same here. Upgrade broke ssh.  RPi 4, 32 bit hass.io.

**Comment by simonbutton** [comment]
+1.  Upgraded SSH addon using RPi4, 32 but hassio and get error

**Comment by vlebourl** [comment]
+1

**Comment by thetux07** [comment]
+1

**Comment by frenck** [comment]
I need to know the architecture and other info.

Please go to the Home Assistant Frontend -> Developer tools -> Info tab.
Copy the block with "System Health" into this issue.

### Please stop adding `+1` and me to messages. Since that does not contribute to solving an issue. Instead, add a 👍 to the openings post of this issue. Thanks.

**Comment by berichta** [comment]
Trying to contribute here. This is my system health info:
```
arch | armv7l
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.7.5
timezone | Europe/Berlin
version | 0.103.0
virtualenv | false
```

**Comment by thetux07** [comment]
arch | armv7l
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.7.5
timezone | Europe/Paris
version | 0.103.0
virtualenv | false

**Comment by frenck** [comment]
Ok, so the instant common thing that stands out is, that you are all running armv7.

I'm preparing a device on that setup now.

**Comment by Golab** [comment]
I’m having same problem
![44132952-F071-4FD9-874D-739902449883](https://user-images.githubusercontent.com/1252745/71077238-5777ec00-2187-11ea-8c29-f170dc769421.jpeg)
![93BCF38C-4F8F-4431-964C-5E56A8AAAB08](https://user-images.githubusercontent.com/1252745/71077240-5777ec00-2187-11ea-93de-c2d2cc7aa76a.jpeg)

**Comment by frenck** [comment]
I see the issue, will update asap!

**Comment by frenck** [comment]
I'm pushing out add-on version v6.4.3 right now, that addresses this issue.
It should be available within 5 - 10 minutes.

Please note, if the update doesn't show up on your system: Go to the add-on store, hit the refresh icon in the top right. Reload the page after that and the update should appear!

Sorry about the trouble!

**Comment by vencakratky** [comment]
Now it´s working. Thank you.

**Comment by thetux07** [comment]
Yes it’s work thank you !

**Comment by mzac** [comment]
Awesome it works thanks!
