### ISSUE TITLE
nginx resolver error prevents startup

### ISSUE THREAD

**Issue by hunleyd** [hassio-addons/addon-ssh#94]
Add-on won't start suddenly.
Config:
{
  "ssh": {
    "username": "hassio",
    "password": "",
    "authorized_keys": [
      "ssh-rsa [redacted]"
    ],
    "sftp": false,
    "compatibility_mode": false,
    "allow_agent_forwarding": false,
    "allow_remote_port_forwarding": false,
    "allow_tcp_forwarding": false
  },
  "web": {
    "ssl": true,
    "certfile": "fullchain.pem",
    "keyfile": "privkey.pem"
  },
  "share_sessions": true,
  "packages": [],
  "init_commands": []
}

Log:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] permissions: applying... 
[fix-attrs.d] permissions: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Hass.io Add-on: SSH & Web Terminal
 SSH & Web Terminal access to your Home Assistant instance
-----------------------------------------------------------
 Add-on version: 6.3.3
 You are running the latest version of this add-on.
 System: Raspbian GNU/Linux 10 (buster)  (armv7 / raspberrypi3)
 Home Assistant version: 0.97.2
 Supervisor version: 169
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] docker.sh: executing... 
[cont-init.d] docker.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
parse error: Expected string key before ':' at line 1, column 4
[09:30:52] ERROR: Unknown HTTP error occured
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] ssh.sh: executing... 
[cont-init.d] ssh.sh: exited 0.
[cont-init.d] user.sh: executing... 
[cont-init.d] user.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[09:30:59] INFO: Starting NGinx...
[09:31:00] INFO: Starting the Home Assistant STDIN service...
[09:31:00] INFO: Starting the ttyd daemon...
[09:31:00] INFO: Starting the SSH daemon...
Server listening on 0.0.0.0 port 2222.
Server listening on :: port 2222.
nginx: [emerg] invalid number of arguments in "resolver" directive in /etc/nginx/includes/resolver.conf:1
Received signal 15; terminating.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
[09:31:00] INFO: STDIN service was stopped, restarting...
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

Network:
80/tcp disabled
22/tcp 2222

**Comment by sinclairpaul** [comment]
Please update your Hassio supervisor version

**Comment by frenck** [comment]
You need supervisor 183+ indeed.
Closing issue.

**Comment by hunleyd** [comment]
ok, but how does one get into this situation? shouldn't the ssh add-on check the version of the supervisor and throw an explicit 'i cant deal with this version' warning? or not upgrade when the supervisor isn't new enough?

**Comment by frenck** [comment]
The supervisor updates are pushed automatically. Unless there is something that is blocking that on your end, it should not be possible (hence no checks).  I would suggest on getting support on the HA discord.
